#NOTE: Use ${CMAKE_PROJECT_NAME} to reference the root parent project if needed

DKDEPEND(DKCef)
DKASSETS(DKCefChild)

#dk_set(QUEUE_BUILD ON)
ADDTO_DKPLUGIN_LIST(DKCefChild)
#DKEXECUTABLE(DKCefChild)


if(WIN)
	# Copy the DKCefChild into the app bundle
	if(DEBUG)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${DEBUG_DIR}/DKCefChild.exe ${DKPROJECT}/assets/DKCef/${OS}Debug TRUE)
	endif()
	if(RELEASE)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${RELEASE_DIR}/DKCefChild.exe ${DKPROJECT}/assets/DKCef/${OS}Release TRUE)
	endif()
endif()

if(MAC_64)
#	if(DEBUG)
#		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${DEBUG_DIR}/DKCefChild.app "${DKPROJECT}/assets/DKCef/${OS}Debug/${AppName} Helper.app" TRUE)
#		dk_rename(${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/DKCefChild "${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/${AppName} Helper")
#		dk_rename(${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app "${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app")
#	endif()
#	if(RELEASE)
#		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${RELEASE_DIR}/DKCefChild.app "${DKPROJECT}/assets/DKCef/${OS}Release/${AppName} Helper.app" TRUE)
#		dk_rename(${DKPROJECT}/${OS}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/DKCefChild "${DKPROJECT}/${OS}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/${AppName} Helper")
#		dk_rename(${DKPROJECT}/${OS}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app "${DKPROJECT}/${OS}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app")
#	endif()
#	MAC_DKQCOMMAND(install_name_tool -change "@executable_path/Chromium Embedded Framework" "@executable_path/../../../../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework" "${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app/Contents/MacOS/${AppName} Helper")
#	
#	FIXME - command does not work because app does not exist yet
#	MAC_DKQCOMMAND(install_name_tool -change "@executable_path/Chromium Embedded Framework" "@executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework" "${DKPROJECT}/${OS}/${DEBUG_DIR}/${AppName}.app/Contents/MacOS/${AppName}")
endif()

if(LINUX)
	dk_remove(${DKPROJECT}/assets/DKCef/DKCefChild)
	if(DEBUG)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${DEBUG_DIR}/DKCefChild ${DKPROJECT}/assets/DKCef TRUE)
	endif()
	if(RELEASE)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${RELEASE_DIR}/DKCefChild ${DKPROJECT}/assets/DKCef TRUE)
	endif()
endif()

if(RASPBERRY)
	dk_remove(${DKPROJECT}/assets/DKCef/DKCefChild)
	if(DEBUG)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${DEBUG_DIR}/DKCefChild ${DKPROJECT}/assets/DKCef TRUE)
	endif()
	if(RELEASE)
		dk_copy(${DKPLUGINS}/DKCefChild/${OS}/${RELEASE_DIR}/DKCefChild ${DKPROJECT}/assets/DKCef TRUE)
	endif()
endif()




## DKCefChild win
if(WIN)
	file(WRITE ${plugin_path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	DKAPPEND_CMAKE("### ${name} ###\n")
	DKAPPEND_CMAKE("cmake_minimum_required(VERSION 3.10)\n")
	DKAPPEND_CMAKE("cmake_policy(SET CMP0054 NEW)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Functions.cmake)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Variables.cmake)\n")
	DKAPPEND_CMAKE("project(DKCefChild)\n")
	DKAPPEND_CMAKE("include_directories(${CEF})\n")
	DKAPPEND_CMAKE("include_directories(${DKPLUGINS})\n")
	
	## DEBUG ##
	DKAPPEND_CMAKE("find_library(libcefD libcef.lib ${CEF}/${DEBUG_DIR})\n")
	DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcefD})\n")
	DKAPPEND_CMAKE("find_library(libcef_dll_wrapperD libcef_dll_wrapper.lib ${CEF}/${OS}/libcef_dll_wrapper/${DEBUG_DIR})\n")
	DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
	#DKAPPEND_CMAKE("find_library(libcef_sandboxD cef_sandbox.lib ${CEF}/${DEBUG_DIR})\n")
	#DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcef_sandboxD})\n")

	## RELEASE ##
	DKAPPEND_CMAKE("find_library(libcefR libcef.lib ${CEF}/${RELEASE_DIR})\n")
	DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcefR})\n")
	DKAPPEND_CMAKE("find_library(libcef_dll_wrapperR libcef_dll_wrapper.lib ${CEF}/${OS}/libcef_dll_wrapper/${RELEASE_DIR})\n")
	DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
	##DKAPPEND_CMAKE("find_library(libcef_sandboxR cef_sandbox.lib ${CEF}/${RELEASE_DIR})\n")
	#DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcef_sandboxR})\n")

	DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp ${DKPLUGINS}/DKCefChild/*.manifest)\n")	
	if(WIN_32)
		DKAPPEND_CMAKE("add_executable(DKCefChild WIN32 \${DKCefChild_SRC})\n")
	endif()
	if(WIN_64)
		DKAPPEND_CMAKE("add_executable(DKCefChild WIN64 \${DKCefChild_SRC})\n")
	endif()
	DKAPPEND_CMAKE("target_link_libraries(DKCefChild \${CEF_DEBUG_DKLIBS} \${CEF_RELEASE_DKLIBS} dbghelp.lib version.lib winmm.lib ws2_32.lib psapi.lib)\n")
	DKAPPEND_CMAKE("set_target_properties(DKCefChild PROPERTIES LINK_FLAGS_DEBUG \"/MANIFESTUAC:NO /SUBSYSTEM:CONSOLE /SAFESEH:NO\" LINK_FLAGS_RELEASE \"/INCREMENTAL:NO /OPT:NOREF /MANIFESTUAC:NO /SUBSYSTEM:CONSOLE /FORCE /SAFESEH:NO\")\n")
endif()


## DKCefChild mac
if(MAC)
	file(WRITE ${plugin_path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	DKAPPEND_CMAKE("### ${name} ###\n")
	DKAPPEND_CMAKE("cmake_minimum_required(VERSION 3.10)\n")
	DKAPPEND_CMAKE("cmake_policy(SET CMP0054 NEW)\n")
	DKAPPEND_CMAKE("cmake_policy(SET CMP0002 OLD)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Functions.cmake)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Variables.cmake)\n")
	DKAPPEND_CMAKE("project(DKCefChild)\n")
	DKAPPEND_CMAKE("include_directories(${CEF})\n")
	DKAPPEND_CMAKE("include_directories(${DKPLUGINS})\n")
	
	#if(DEBUG)
		#DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \"${CEF}/${DEBUG_DIR}/Chromium Embedded Framework.framework\")\n")
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF}/${OS}/libcef_dll_wrapper/${DEBUG_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		#DKAPPEND_CMAKE("find_library(AK AppKit)\n")
		#DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS ${AK})\n")
	#endif()
	#if(RELEASE)
		#DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \"${CEF}/${RELEASE_DIR}/Chromium Embedded Framework.framework\")\n")
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF}/${OS}/libcef_dll_wrapper/${RELEASE_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		#DKAPPEND_CMAKE("find_library(AK AppKit)\n")
		#DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS ${AK})\n")
	#endif()
	
	DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp)\n")
	if(MAC_32)
		DKAPPEND_CMAKE("SET(CMAKE_OSX_ARCHITECTURES \"i386\")\n")
	endif()
	if(MAC_64)
		DKAPPEND_CMAKE("SET(CMAKE_OSX_ARCHITECTURES \"x86_64\")\n")
	endif()
	DKAPPEND_CMAKE("add_executable(DKCefChild MACOSX_BUNDLE \${DKCefChild_SRC})\n")
	DKAPPEND_CMAKE("target_link_libraries(DKCefChild \${CEF_DEBUG_DKLIBS} \${CEF_RELEASE_DKLIBS})\n")
endif()


## DKCefChild linux
if(LINUX)
	file(WRITE ${plugin_path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	DKAPPEND_CMAKE("### ${name} ###\n")
	DKAPPEND_CMAKE("cmake_minimum_required(VERSION 3.10)\n")
	DKAPPEND_CMAKE("cmake_policy(SET CMP0054 NEW)\n")
	DKAPPEND_CMAKE("CMAKE_POLICY(SET CMP0002 OLD)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Functions.cmake)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Variables.cmake)\n")
	DKAPPEND_CMAKE("project(DKCefChild)\n")
	DKAPPEND_CMAKE("include_directories(${CEF})\n")
	DKAPPEND_CMAKE("include_directories(${DKPLUGINS})\n")
		
	if(DEBUG)
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF}/${OS}/${DEBUG_DIR}/libcef_dll_wrapper)\n")
		DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		DKAPPEND_CMAKE("find_library(libcefD libcef.so ${CEF}/${DEBUG_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcefD})\n")
		
		DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp)\n")
		DKAPPEND_CMAKE("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		DKAPPEND_CMAKE("target_link_libraries(DKCefChild  \${CEF_DEBUG_DKLIBS})\n")
	elseif(RELEASE)
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF}/${OS}/${RELEASE_DIR}/libcef_dll_wrapper)\n")
		DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		DKAPPEND_CMAKE("find_library(libcefR libcef.so ${CEF}/${RELEASE_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcefR})\n")
		
		DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp)\n")
		DKAPPEND_CMAKE("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		DKAPPEND_CMAKE("target_link_libraries(DKCefChild  \${CEF_RELEASE_DKLIBS})\n")
	endif()
endif()

## DKCefChild raspberry
if(RASPBERRY)
	file(WRITE ${plugin_path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	DKAPPEND_CMAKE("### ${name} ###\n")
	DKAPPEND_CMAKE("cmake_minimum_required(VERSION 3.10)\n")
	DKAPPEND_CMAKE("cmake_policy(SET CMP0054 NEW)\n")
	DKAPPEND_CMAKE("CMAKE_POLICY(SET CMP0002 OLD)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Functions.cmake)\n")
	DKAPPEND_CMAKE("include(${DKCMAKE}/Variables.cmake)\n")
	DKAPPEND_CMAKE("project(DKCefChild)\n")
	DKAPPEND_CMAKE("include_directories(${CEF})\n")
	DKAPPEND_CMAKE("include_directories(${DKPLUGINS})\n")
		
	if(DEBUG)
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF}/${OS}/${DEBUG_DIR}/libcef_dll_wrapper)\n")
		DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		DKAPPEND_CMAKE("find_library(libcefD libcef.so ${CEF}/${DEBUG_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_DEBUG_DKLIBS debug \${libcefD})\n")
		
		DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp)\n")
		DKAPPEND_CMAKE("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		DKAPPEND_CMAKE("target_link_libraries(DKCefChild  \${CEF_DEBUG_DKLIBS})\n")
	elseif(RELEASE)
		DKAPPEND_CMAKE("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF}/${OS}/${RELEASE_DIR}/libcef_dll_wrapper)\n")
		DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		DKAPPEND_CMAKE("find_library(libcefR libcef.so ${CEF}/${RELEASE_DIR})\n")
		DKAPPEND_CMAKE("list(APPEND CEF_RELEASE_DKLIBS optimized \${libcefR})\n")
		
		DKAPPEND_CMAKE("file(GLOB DKCefChild_SRC ${DKPLUGINS}/DKCefChild/*.cpp)\n")
		DKAPPEND_CMAKE("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		DKAPPEND_CMAKE("target_link_libraries(DKCefChild  \${CEF_RELEASE_DKLIBS})\n")
	endif()
endif()
