#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
	cmake_policy(SET CMP0009 NEW)
	file(GLOB_RECURSE DK.cmake "/DK.cmake")
	list(GET DK.cmake 0 DK.cmake)
	get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK.cmake}" DIRECTORY)
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()
#########################################################################

dk_importVariables(INSTALL_PATH "${CMAKE_CURRENT_LIST_DIR}")

############ DKCef ############
#NOTE: Use ${CMAKE_PROJECT_NAME} to reference the root parent project if needed
dk_validate(Target_Config  "dk_Target_Config()")
#if(Android OR IOS OR Iossim OR (Windows AND (NOT MSVC)))
	dk_disable(DKCef)
	dk_return()
#endif()


if(Linux)
	#dk_depend(libglib2.0-dev)
	#dk_depend(libgtk2.0-dev)
elseif(Mac)
	#dk_depend(appkit)
	#dk_depend(foundation)
elseif(Raspberry)
	dk_depend(libglib2.0-dev)
	dk_depend(libgtk2.0-dev)
elseif(Windows)
	dk_depend(winmm)
endif()
dk_depend(cef_binary)
dk_depend(DK)
dk_depend(DKDuktape)


############ DKCef ############
dk_generateCmake()
dk_assets()
dk_configure()
dk_build()


if(Windows_X86 AND MSVC)
	dk_copy(${CEF_BINARY}/Resources/ ${Target_App_Dir}/assets/DKCef OVERWRITE)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug/ ${Target_App_Dir}/assets/DKCef/Windows_X86_Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef/Windows_X86_Debug OVERWRITE)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Debug/cef_sandbox.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Debug/libcef.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Debug/wow_helper.exe)
	endif()
	if(Release)
		##UPX_COMPRESS(${CEF_BINARY}/Release/libcef.dll)
		dk_copy(${CEF_BINARY}/Release/ ${Target_App_Dir}/assets/DKCef/Windows_X86_Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef/Windows_X86_Release OVERWRITE)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Release/cef_sandbox.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Release/libcef.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_Release/wow_helper.exe)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/icudtl.dat)
	LIST(APPEND DEBUG_LINK_FLAGS /DELAYLOAD:libcef.dll)
	LIST(APPEND RELEASE_LINK_FLAGS /DELAYLOAD:libcef.dll)
	LIST(APPEND DEBUG_LINK_FLAGS /DELAYLOAD:chrome_elf.dll)
	LIST(APPEND RELEASE_LINK_FLAGS /DELAYLOAD:chrome_elf.dll)
endif()

if(Windows_X86_64 AND MSVC)
	dk_copy(${CEF_BINARY}/Resources/ ${Target_App_Dir}/assets/DKCef OVERWRITE)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug/ ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Debug OVERWRITE)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Debug/cef_sandbox.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Debug/libcef.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Debug/wow_helper.exe)
	endif()
	if(Release)
		#UPX_COMPRESS(${CEF_BINARY}/Release/libcef.dll)
		dk_copy(${CEF_BINARY}/Release/ ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Release OVERWRITE)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Release/cef_sandbox.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Release/libcef.lib)
		FILE(REMOVE ${Target_App_Dir}/assets/DKCef/Windows_X86_64_Release/wow_helper.exe)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/icudtl.dat)
	LIST(APPEND DEBUG_LINK_FLAGS /DELAYLOAD:libcef.dll)
	LIST(APPEND RELEASE_LINK_FLAGS /DELAYLOAD:libcef.dll)
	LIST(APPEND DEBUG_LINK_FLAGS /DELAYLOAD:chrome_elf.dll)
	LIST(APPEND RELEASE_LINK_FLAGS /DELAYLOAD:chrome_elf.dll)
endif()

#https://bitbucket.org/chromiumembedded/cef/wiki/Tutorial#markdown-header-mac-os-x-build-steps
if(Mac_X86_64)
	#dk_info("Adding Chromium Embedded Framework.framework to bundle . . .")
	#add_custom_command(
	#	TARGET DKCef
	#	POST_BUILD
	#	COMMAND ${CMAKE_COMMAND} -E copy_directory
	#		"${CEF_BINARY}/$<CONFIG>/Chromium Embedded Framework.framework"
	#		"$<TARGET_FILE_DIR:${CMAKE_PROJECT_NAME}>/../Frameworks/Chromium Embedded Framework.framework"
	#)
endif()

if(Linux_X86)
if(NOT Raspberry)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/Linux_X86/Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/Linux_X86/Debug OVERWRITE)
	endif()
	if(Release)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/Linux_X86/Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/Linux_X86/Release OVERWRITE)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/cef_sandbox.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/libcef.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/wow_helper.exe)
endif()
endif()
if(Linux_X86_64)
if(NOT Raspberry)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/Linux_X86_64/Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/Linux_X86_64/Debug OVERWRITE)
	endif()
	if(Release)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/Linux_X86_64/Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/Linux_X86_64/Release OVERWRITE)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/cef_sandbox.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/libcef.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/wow_helper.exe)
endif()
endif()

if(Raspberry_Arm32)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/raspberry_arm32/Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/raspberry_arm32/Debug OVERWRITE)
	endif()
	if(Release)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/raspberry_arm32/Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/raspberry_arm32/Release OVERWRITE)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/cef_sandbox.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/libcef.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/wow_helper.exe)
endif()
if(Raspberry_Arm64)
	if(Debug)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Debug ${Target_App_Dir}/raspberry_arm64/Debug OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/raspberry_arm64/Debug OVERWRITE)
	endif()
	if(Release)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources ${Target_App_Dir}/assets/DKCef OVERWRITE)
		dk_copy(${CEF_BINARY}/Release ${Target_App_Dir}/raspberry_arm64/Release OVERWRITE)
		dk_copy(${CEF_BINARY}/Resources/icudtl.dat ${Target_App_Dir}/raspberry_arm64/Release OVERWRITE)
	endif()
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/cef_sandbox.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/libcef.a)
	FILE(REMOVE ${Target_App_Dir}/assets/DKCef/wow_helper.exe)
endif()
