#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
	cmake_policy(SET CMP0009 NEW)
	file(GLOB_RECURSE DK.cmake "/DK.cmake")
	list(GET DK.cmake 0 DK.cmake)
	get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK.cmake}" DIRECTORY)
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()
#########################################################################


dk_validate(Host_Os "dk_Host_Os()")
dk_validate(Host_Arch "dk_Host_Arch()")
dk_Target_Os("${Host_Os}")
dk_Target_Arch("${Host_Arch}")
dk_Target_Env ("Clang")
dk_Target_Type("Debug")
dk_Target_Tuple()

############ APP ############
dk_set(Target_App_Dir "${CMAKE_CURRENT_LIST_DIR}")
dk_basename("${Target_App_Dir}")
dk_set(Target_App "${dk_basename}")
dk_validate(CONFIG_PATH "dk_CONFIG_PATH()")

###### DEPENDENCIES ######


###### CREATE ICONS ######
if(EXISTS "${Target_App_Dir}/icon.png")
	dk_createIcons("${Target_App_Dir}/icon.png")
	if(Windows)
		dk_copy(${DKCPP_PLUGINS_DIR}/_DKIMPORT/win/icon.h ${Target_App_Dir}/windows/icon.h)
		dk_copy(${DKCPP_PLUGINS_DIR}/_DKIMPORT/win/icon.rc ${Target_App_Dir}/windows/icon.rc)
	endif()
endif()

################# BACKUP USERDATA / INJECT ASSETS #####################
if(EXISTS "${Target_App_Dir}/assets")
	dk_copy(${Target_App_Dir}/assets/USER ${Target_App_Dir}/Backup/USER OVERWRITE NO_HALT)
	dk_delete(${Target_App_Dir}/assets/USER NO_HALT)
	#Compress the assets, they will be included by resource.rc
	dk_info("Creating assets.zip . . .")
	dk_compressAssets(${Target_App_Dir}/assets)
	# Restore the backed up files
	dk_copy(${Target_App_Dir}/Backup/ ${Target_App_Dir}/assets/ OVERWRITE NO_HALT)
	dk_delete(${Target_App_Dir}/Backup NO_HALT)
	#dummy assets.h file, or the builder wil complain about assets.h missing
	dk_assertPath(DKCPP_PLUGINS_DIR)
	dk_copy(${DKCPP_PLUGINS_DIR}/_DKIMPORT/assets.h ${Target_App_Dir}/assets.h OVERWRITE NO_HALT)
endif()

###################### Backup Executable ###########################
if(BACKUP_APP_EXECUTABLES)
	if(Debug)
		dk_rename(${Target_App_Dir}/${Target_Tuple}/${Debug_Dir}/${Target_App}.exe ${Target_App_Dir}/${Target_Tuple}/${Debug_Dir}/${Target_App}.exe.backup OVERWRITE NO_HALT)
	endif()
	if(Release)
		dk_rename(${Target_App_Dir}/${Target_Tuple}/${Release_Dir}/${Target_App}.exe ${Target_App_Dir}/${Target_Tuple}/${Release_Dir}/${Target_App}.exe.backup OVERWRITE NO_HALT)
	endif()
endif()




#	##set_source_files_properties($ENV{DIGITALKNOB_DIR}/stdafx.cpp PROPERTIES COMPILE_FLAGS "/Ycstdafx.h")
#	file(GLOB_RECURSE resources_SRC 
#		${Target_App_Dir}/*.manifest
#		${Target_App_Dir}/*.rc
#		${Target_App_Dir}/icons/windows/*.rc)
#	list(APPEND App_SRC ${resources_SRC})
#endif()
	
### dk_generateCmake("${CMAKE_CURRENT_LIST_DIR}") ###
 dk_fileWrite(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"\### This file is generated by DKCMake. Any Changes here, will be overwritten. ### \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt   	"cmake_minimum_required(VERSION 3.10) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"include(\$ENV{DKCMAKE_FUNCTIONS_DIR}/DK.cmake) \n\n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"### ${Target_App} ### \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"project(${Target_App}) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"include_directories(${CMAKE_CURRENT_LIST_DIR}) \n")
dk_validate(DKCPP_PLUGINS_DIR "dk_DKBRANCH_DIR()")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"include_directories(${DKCPP_PLUGINS_DIR}) \n")
foreach(each_include ${DKINCLUDES_LIST})
	dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  "include_directories(${each_include})\n")
endforeach()
foreach(each_define ${DKDEFINES_LIST})
	dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt	"add_definitions(-D${each_define})\n")
endforeach()
foreach(each_linkdir ${DKLINKDIRS_LIST})
	dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt 	"link_directories(${each_linkdir})\n")
endforeach()
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"file(GLOB App_SRC \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.h \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.hpp \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.c \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.cpp \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.manifest \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    ${CMAKE_CURRENT_LIST_DIR}/*.rc \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	") \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"list(FILTER App_SRC EXCLUDE REGEX \"${CMAKE_CURRENT_LIST_DIR}/assets/*\") \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"list(FILTER App_SRC EXCLUDE REGEX \"${CMAKE_CURRENT_LIST_DIR}/${Target_Tuple}/*\") \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"\n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"dk_validate(Target_Tuple \"dk_Target_Tuple()\") \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"\n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"if(MSVC) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    add_executable(${Target_App} WIN32 \${App_SRC}) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"else() \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    add_executable(${Target_App} \${App_SRC}) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"endif() \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"\n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"if(MULTI_CONFIG) \n")
dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt 		"    target_link_libraries(${Target_App} ${DEBUG_LIBS} ${RELEASE_LIBS} ${LIBS}) \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"else() \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    if(Debug) \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"        target_link_libraries(${Target_App} ${DEBUG_LIBS} ${LIBS}) \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    elseif(Release) \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"        target_link_libraries(${Target_App} ${RELEASE_LIBS} ${LIBS}) \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"    endif() \n")
#dk_fileAppend(${CMAKE_CURRENT_LIST_DIR}/CMakeLists.txt  	"endif() \n")

#dk_clearCmakeCache()

dk_set(CURRENT_PLUGIN 				${Target_App})
dk_set(${CURRENT_PLUGIN} 			${CMAKE_SOURCE_DIR})
dk_set(${CURRENT_PLUGIN}_CONFIG_DIR ${CMAKE_CURRENT_LIST_DIR}/${CONFIG_PATH})

dk_configure(${CMAKE_CURRENT_LIST_DIR} -DDKCMAKE_FUNCTIONS_DIR=${DKCMAKE_FUNCTIONS_DIR} -DTUPLE=${TUPLE})
dk_build(${CMAKE_CURRENT_LIST_DIR})
