
###### Global Script Variables ######
set(DKVERBOSE_ENABLED 1	CACHE INTERNAL "") 	# export LOG_VERBOSE=1
set(DKDEBUG_ENABLED	  1 CACHE INTERNAL "") 	# export LOG_DEBUG=1
# export TRACE_ON_WARNINGS=0
set(HALT_ON_WARNINGS  0 CACHE INTERNAL "")  # export HALT_ON_WARNINGS=1
set(HALT_ON_ERRORS    1	CACHE INTERNAL "")  # export CONTINUE_ON_ERRORS=0


#message("CMAKE_CURRENT_BINARY_DIR         = ${CMAKE_CURRENT_BINARY_DIR}")
#message("CMAKE_CURRENT_FUNCTION           = ${CMAKE_CURRENT_FUNCTION}")
#message("CMAKE_CURRENT_FUNCTION_LIST_DIR  = ${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
#message("CMAKE_CURRENT_FUNCTION_LIST_FILE = ${CMAKE_CURRENT_FUNCTION_LIST_FILE}")
#message("CMAKE_CURRENT_FUNCTION_LIST_LINE = ${CMAKE_CURRENT_FUNCTION_LIST_LINE}")
#message("CMAKE_CURRENT_LIST_DIR           = ${CMAKE_CURRENT_LIST_DIR}")
#message("CMAKE_CURRENT_LIST_FILE          = ${CMAKE_CURRENT_LIST_FILE}")
#message("CMAKE_CURRENT_LIST_LINE          = ${CMAKE_CURRENT_LIST_LINE}")
#message("CMAKE_CURRENT_SOURCE_DIR         = ${CMAKE_CURRENT_SOURCE_DIR}")
#message("CMAKE_PARENT_LIST_FILE           = ${CMAKE_PARENT_LIST_FILE}")
#message("CMAKE_SOURCE_DIR                 = ${CMAKE_SOURCE_DIR}")

###### get DKCMAKE_DIR ######
get_filename_component(DKCMAKE_DIR ${CMAKE_CURRENT_LIST_DIR} DIRECTORY CACHE INTERNAL "")
message("DKCMAKE_DIR                      = ${DKCMAKE_DIR}")

###### Script loader ######
include(${DKCMAKE_DIR}/functions/dk_load.cmake)
dk_load(DKDEBUGFUNC)
dk_load(dk_color)