include_guard()

###############################################################################
# dk_appendEnvPath(inputPath)
#
#	@path	- The CMake / style full path to append the the Environment Path variable
#
function(dk_appendEnvPath inputPath)
	dk_debug("dk_appendEnvPath(${ARGV})")
	if(NOT inputPath)
		dk_error("dk_appendEnvPath(): inputPath is invalid!")
		return()
	endif()
	if(NOT EXISTS ${inputPath})
		dk_warning("dk_appendEnvPath(): ${inputPath}: path does not exist")
		return()
	endif()
	if(WIN_HOST)
		dk_debug("Converting value to NATIVE_PATH")
		#file(TO_NATIVE_PATH "${inputPath}" nativePath)
		cmake_path(NATIVE_PATH inputPath NORMALIZE nativePath)
		#set(path_printable "${nativePath}" CACHE FILEPATH "")
		#string(REPLACE "/" "\\" path_printable "${path_printable}")
		#string(REPLACE "/" "\\" inputPath "${inputPath}")
	#else()
	#	set(path_printable "${nativePath}")
	endif()
	
	#dk_debug(ENV{PATH})
	string(FIND "$ENV{PATH}" "${nativePath}" hasPath)
	if(${hasPath} GREATER -1)
		dk_notice("${nativePath} is already in the PATH environment list\n")
	else()
		if(WIN_HOST)
			set(ENV{PATH} "$ENV{PATH};${nativePath}")
		else()
			set(ENV{PATH} "$ENV{PATH}:${nativePath}")
		endif()
		dk_info("appended \${nativePath} to the PATH environment list\n")
	endif()
	dk_debug(ENV{PATH})
endfunction()
