#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT DEFINED DKINIT_cmake)
	if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
		cmake_policy(SET CMP0009 NEW)
		file(GLOB_RECURSE DK_cmake "/DK.cmake")
		list(GET DK_cmake 0 DK_cmake)
		get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK_cmake}" DIRECTORY)
		set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
	endif()
	include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
endif()
#########################################################################

### TODO ###
# switch to using install() instead of file(INSTALL ...) so we can use cmake --install and so
# different dependencies are taken into account when installing everything
function(install_libs)
	if(INSTALL_DKLIBS)
		dk_info("Installing ${CURRENT_PLUGIN} Binary files")
		set(${CURRENT_PLUGIN}_DKBIN "${CMAKE_INSTALL_PREFIX}/${CURRENT_PLUGIN}")
		file(INSTALL DIRECTORY "${${CURRENT_PLUGIN}}/" DESTINATION "${${CURRENT_PLUGIN}_DKBIN}" FILES_MATCHING PATTERN "*.a")
		file(INSTALL DIRECTORY "${${CURRENT_PLUGIN}}/" DESTINATION "${${CURRENT_PLUGIN}_DKBIN}" FILES_MATCHING PATTERN "*.lib")
		file(INSTALL DIRECTORY "${${CURRENT_PLUGIN}}/" DESTINATION "${${CURRENT_PLUGIN}_DKBIN}" FILES_MATCHING PATTERN "*.exe")
		file(INSTALL DIRECTORY "${${CURRENT_PLUGIN}}/assets" DESTINATION "${${CURRENT_PLUGIN}_DKBIN}/assets" FILES_MATCHING PATTERN "*.*")
		#dk_deleteEmptyDirectories("${CMAKE_INSTALL_PREFIX}/include/${Plugin}")
	endif()
endfunction()
		
		
#########################################################################
# dk_build(Source_Dir, target, NO_HALT)
#
#	TODO
#
#	Source_Dir 			- path to the library root 	 I.E. ${MyLibrary_Dir} 
#	target (optional)	- The target name of the project to build
#
function(dk_build)
	dk_debugFunc(0 99)
	
	###### Source_Dir ######
	if(ARGV)
		set(Source_Dir "${ARGV0}")
	elseif(${CURRENT_PLUGIN})
		set(Source_Dir "${${CURRENT_PLUGIN}}")
	endif()
	dk_assertPath("${Source_Dir}")
	if(NOT "${Source_Dir}" STREQUAL "${${CURRENT_PLUGIN}}")
		dk_notice("dk_build(): Source_Dir:${Source_Dir} != ${CURRENT_PLUGIN}:${${CURRENT_PLUGIN}}")
	endif()
	dk_debug("Source_Dir = ${Source_Dir}")

	### target ###
	if(${ARGC} GREATER 1)
		set(target "${ARGV1}")
	endif()

	### Config_Dir ###
	dk_validate(${CURRENT_PLUGIN}_Config_Dir "dk_Target_Config()")
	set(Config_Dir "${${CURRENT_PLUGIN}_Config_Dir}")
	if(NOT EXISTS "${Config_Dir}")
		dk_mkdir("${Config_Dir}")
	endif()
	dk_assertVar(Config_Dir)
	dk_debug("Config_Dir = ${Config_Dir}")
	
	#if(NOT REBUILDALL)
		foreach(lib ${$ENV{CURRENT_PLUGIN}_LIBS})
			if(NOT DEFINED missing_libs)
				set(missing_libs 0)
			endif()
			if(NOT EXISTS "${lib}")
				set(missing_libs 1)
			else()
				dk_notice("${lib} already exists")
			endif()
		endforeach()
		if("${missing_libs}" EQUAL "0")
			dk_notice("$ENV{CURRENT_PLUGIN} libs already built. skipping...")
			return()
		endif()
	#endif()
	
	dk_getParameter(NO_HALT)
	
	# If we are in MULTI_CONFIG mode, we need to do a second pass to check for build files in SINGLE_CONFIG mode. Some libraries are
	# still built in SINGLE_CONFIG mode event though the main project isn't 
	#if(MULTI_CONFIG)
	#	list(APPEND BUILD_MODE multi_config)
	#endif()
	#list(APPEND BUILD_MODE single_config)
		#dk_assertVar(Target_Config)

		# Build with CMake		(multi_config / single_config)
		if(EXISTS "${Config_Dir}/cmake_install.cmake")
			dk_validate(cmake_exe "dk_depend(cmake)")
			if(target)
				if(Debug)
					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_${target}_Debug with CMake ######")
					dk_exec(${cmake_exe} --build "${Config_Dir}" --config Debug --target ${target} --verbose)# -- -d)
				endif()
				if(Release)
					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_${target}_Release with CMake ######")
					dk_exec(${cmake_exe} --build "${Config_Dir}" --config Release --target ${target} --verbose)# -- -d)
				endif()
			else()
				if(Debug)
					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Debug with CMake ######")
					dk_exec(${cmake_exe} --build "${Config_Dir}" --config Debug --verbose)# -- -d)
				endif()
				if(Release)
					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Release with CMake ######")
					dk_exec(${cmake_exe} --build "${Config_Dir}" --config Release --verbose)# -- -d)
				endif()
			endif()
			install_libs()
			dk_return()
		endif()
#		if(MULTI_CONFIG)
#			if(Debug)
#				ifdk_validate(cmake_exe "dk_depend(cmake)")
#					if(target)
#						dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_${target}_Debug with CMake (multi_config) ######")
#						dk_exec(${cmake_exe} --build "${Config_Dir}" --config Debug --target ${target} --verbose)
#					else()
#						dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Debug with CMake (multi_config) ######")
#						dk_exec(${cmake_exe} --build "${Config_Dir}" --config Debug --verbose)
#					endif()
#					dk_return()
#				endif()
#			elseif(Release)
#				if(EXISTS "${Config_Dir}/cmake_install.cmake")
#					dk_depend(cmake)
#					if(target)
#						dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_${target}_Release with CMake (multi_config) ######")
#						dk_exec(${cmake_exe} --build "${Config_Dir}" --config Release --target ${target} --verbose)
#					else()
#						dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Release with CMake (multi_config) ######")
#						dk_exec(${cmake_exe} --build "${Config_Dir}" --config Release --verbose)
#					endif()
#					dk_return()
#				endif()
#			endif()
#		endif()
		
		# Build with MSBuild
		file(GLOB sln "${Config_Dir}/*.sln")
		if(sln)
			dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${sln} ######")
			dk_visualStudio(${ARGV})
			install_libs()
			dk_return()
		endif()
		
		# Build with XCode
		file(GLOB xcodeproj "${Config_Dir}/*.xcodeproj")
		if(xcodeproj)
			dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${xcodeproj} ######")
			dk_xcode(${ARGV})
			install_libs()
			dk_return()
		endif()
		
		
		# Build with make
		file(GLOB Makefile "${Config_Dir}/Makefile")
		if(Makefile)
			dk_chdir("${Config_Dir}")
			dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${Makefile} ######")
			dk_make(${ARGV})
			install_libs()
			dk_return()
		endif()
		file(GLOB Makefile "${Source_Dir}/Makefile")
		if(Makefile)
			dk_chdir("${Source_Dir}")
			dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${Makefile} ######")
			dk_make(${ARGV})
			install_libs()
			dk_return()
		endif()
		
#		if(MULTI_CONFIG)
#			if(Debug)
#				if(EXISTS "${Config_Dir}/Makefile")
#					dk_chdir("${Config_Dir}")
#					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${Config_Dir}/Makefile ######")
#					dk_make(${ARGV})
#					dk_chdir("${Config_Dir}")
#					dk_return()
#				endif()
#			elseif(Release)
#				if(EXISTS "${Config_Dir}/Makefile")
#					dk_chdir("${Config_Dir}")
#					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${Config_Dir}/Makefile ######")
#					dk_make(${ARGV})
#					dk_chdir("${Config_Dir}")
#					dk_return()
#				endif()
#			endif()
#		endif()
		
		
		# Build with Android NDK	(single_config)
		file(GLOB AndroidManifest_xml "${Config_Dir}/AndroidManifest.xml")
		#if(EXISTS "${Config_Dir}/AndroidManifest.xml")
		if(AndroidManifest_xml)
			dk_echo("\n###### Building $ENV{CURRENT_PLUGIN} with ${AndroidManifest_xml} ######")
			dk_ndk(${ARGV})
			install_libs()
			dk_return()
		endif()
#		if(MULTI_CONFIG)
#			if(Debug)
#				if(EXISTS "${Config_Dir}/AndroidManifest.xml")
#					dk_chdir("${Config_Dir}")
#					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Debug with Android NDK ######")
#					dk_ndk(${ARGV})
#					dk_chdir("${Config_Dir}")
#					dk_return()
#				endif()
#			elseif(Release)
#				if(EXISTS "${Config_Dir}/AndroidManifest.xml")
#					dk_chdir("${Config_Dir}")
#					dk_echo("\n###### Building $ENV{CURRENT_PLUGIN}_Release with Android NDK ######")
#					dk_ndk(${ARGV})
#					dk_chdir("${Config_Dir}")
#					dk_return()
#				endif()
#			endif()
#		endif()
		
	#endforeach()
	install_libs()
	dk_assertPath("${Config_Dir}")
	dk_fatal("dk_build(): ${Config_Dir} has no buildable files")
endfunction()







###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_build(todo) #TODO
endfunction()