#!/usr/bin/cmake -P
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
	cmake_policy(SET CMP0009 NEW)
	file(GLOB_RECURSE DK.cmake "/DK.cmake")
	list(GET DK.cmake 0 DK.cmake)
	get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK.cmake}" DIRECTORY)
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()

###############################################################################
# dk_createIcons(image)
#
#	@image		- Full path of the image file to use (icon.png)
#	@outpath	- Full path of the output file to save to (.ico)
#
function(dk_createIcons)
	dk_debugFunc(1)
	
	if(NOT EXISTS "${ARGV0}")
		dk_error("dk_createIcons(): image:${ARGV0} not found.")
		return()
	endif()

	dk_assertVar(Target_App)
	dk_assertVar(Target_Os)
	dk_info("Building ${Target_Os} icons for ${Target_App} . . .")
	
	dk_assertPath("${Target_App_Dir}")
	dk_mkdir("${Target_App_Dir}/assets")
	dk_copy("${ARGV0}" "${Target_App_Dir}/assets/icon.png" OVERWRITE)
	
	if(Android)
		if(Debug)
			dk_resizeImage("${ARGV0}" 36 36   "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-ldpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 48 48   "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-mdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 72 72   "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-hdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 96 96   "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-xhdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 144 144 "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-xxhdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 192 192 "${Target_App_Dir}/${Target_Tuple}/Debug/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png")
		endif()
		if(Release)
			dk_resizeImage("${ARGV0}" 36 36   "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-ldpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 48 48   "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-mdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 72 72   "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-hdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 96 96   "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-xhdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 144 144 "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-xxhdpi/ic_launcher.png")
			dk_resizeImage("${ARGV0}" 192 192 "${Target_App_Dir}/${Target_Tuple}/Release/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png")
		endif()
		#dk_createFavIcon("${ARGV0}" "${Target_App_Dir}/assets/favicon.ico")
	endif()
	
	if(IOS OR Iossim)
		dk_mkdir("${Target_App_Dir}/icons/ios")
		dk_mkdir("${Target_App_Dir}/icons/ios/icons.iconset")
		dk_resizeImage("${ARGV0}" 16 16     "${Target_App_Dir}/icons/ios/icons.iconset/icon_16x16.png")
		dk_resizeImage("${ARGV0}" 32 32     "${Target_App_Dir}/icons/ios/icons.iconset/icon_16x16@2x.png")
		dk_resizeImage("${ARGV0}" 32 32     "${Target_App_Dir}/icons/ios/icons.iconset/icon_32x32.png")
		dk_resizeImage("${ARGV0}" 64 64     "${Target_App_Dir}/icons/ios/icons.iconset/icon_32x32@2x.png")
		dk_resizeImage("${ARGV0}" 128 128   "${Target_App_Dir}/icons/ios/icons.iconset/icon_128x128.png")
		dk_resizeImage("${ARGV0}" 256 256   "${Target_App_Dir}/icons/ios/icons.iconset/icon_128x128@2x.png")
		dk_resizeImage("${ARGV0}" 256 256   "${Target_App_Dir}/icons/ios/icons.iconset/icon_256x256.png")
		dk_resizeImage("${ARGV0}" 512 512   "${Target_App_Dir}/icons/ios/icons.iconset/icon_256x256@2x.png")
		dk_resizeImage("${ARGV0}" 512 512   "${Target_App_Dir}/icons/ios/icons.iconset/icon_512x512.png")
		dk_resizeImage("${ARGV0}" 1024 1024 "${Target_App_Dir}/icons/ios/icons.iconset/icon_512x512@2x.png")
		dk_exec(iconutil -c icns -o "${Target_App_Dir}/icons/ios/icons.icns" "${Target_App_Dir}/icons/ios/icons.iconset")
		set(MACOSX_BUNDLE_ICON_FILE icons.icns)
		set(app_ICONS "${Target_App_Dir}/icons/ios/icons.icns")
		set_source_files_properties(${app_ICONS} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")
		#dk_createFavIcon(${ARGV0} ${Target_App_Dir}/assets/favicon.ico)
	endif()
	
	if(Mac)
		dk_mkdir("${Target_App_Dir}/icons/mac")
		dk_mkdir("${Target_App_Dir}/icons/mac/icons.iconset")
		dk_resizeImage("${ARGV0}" 16 16     "${Target_App_Dir}/icons/mac/icons.iconset/icon_16x16.png")
		dk_resizeImage("${ARGV0}" 32 32     "${Target_App_Dir}/icons/mac/icons.iconset/icon_16x16@2x.png")
		dk_resizeImage("${ARGV0}" 32 32     "${Target_App_Dir}/icons/mac/icons.iconset/icon_32x32.png")
		dk_resizeImage("${ARGV0}" 64 64     "${Target_App_Dir}/icons/mac/icons.iconset/icon_32x32@2x.png")
		dk_resizeImage("${ARGV0}" 128 128   "${Target_App_Dir}/icons/mac/icons.iconset/icon_128x128.png")
		dk_resizeImage("${ARGV0}" 256 256   "${Target_App_Dir}/icons/mac/icons.iconset/icon_128x128@2x.png")
		dk_resizeImage("${ARGV0}" 256 256   "${Target_App_Dir}/icons/mac/icons.iconset/icon_256x256.png")
		dk_resizeImage("${ARGV0}" 512 512   "${Target_App_Dir}/icons/mac/icons.iconset/icon_256x256@2x.png")
		dk_resizeImage("${ARGV0}" 512 512   "${Target_App_Dir}/icons/mac/icons.iconset/icon_512x512.png")
		dk_resizeImage("${ARGV0}" 1024 1024 "${Target_App_Dir}/icons/mac/icons.iconset/icon_512x512@2x.png")
		dk_exec(iconutil -c icns -o "${Target_App_Dir}/icons/mac/icons.icns" "${Target_App_Dir}/icons/mac/icons.iconset")
		set(MACOSX_BUNDLE_ICON_FILE icons.icns)
		set(app_ICONS "${Target_App_Dir}/icons/mac/icons.icns")
		set_source_files_properties(${app_ICONS} PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")
		#dk_createFavIcon(${ARGV0} ${Target_App_Dir}/assets/favicon.ico)
	endif()
	
	if(Windows)
		dk_createWindowsIcon("${ARGV0}" "${Target_App_Dir}/icons/windows/icon.ico")
		dk_copy("${Target_App_Dir}/icons/windows/icon.ico" "${Target_App_Dir}/assets/icon.ico" OVERWRITE)
		dk_createFavIcon("${ARGV0}" "${Target_App_Dir}/assets/favicon.ico")
	endif()
endfunction()




###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_validate(Target_Tuple "dk_Target_Tuple()")
	dk_createIcons("${Target_App_Dir}/icons/icon.png")
endfunction()