#!/usr/bin/cmake -P
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()

####################################################################
# dk_CMAKE_GENERATOR()
#
#
function(dk_CMAKE_GENERATOR)
    dk_debugFunc()

	dk_validate(Target_Tuple "dk_Target_Tuple()")
	
	if(Android_Arm32)    
		set(CMAKE_GENERATOR "Unix Makefiles")
	elseif(android_arm64)
		set(CMAKE_GENERATOR "Unix Makefiles")
    elseif(android_x86)
		set(CMAKE_GENERATOR "Unix Makefiles")
	elseif(android_x86_64)
		set(CMAKE_GENERATOR "Unix Makefiles")
	elseif(emscripten_x86)          
		set(CMAKE_GENERATOR "Unix Makefiles")
    elseif(ios_arm32)           
		set(CMAKE_GENERATOR "Xcode")
    elseif(ios_arm64)           
		set(CMAKE_GENERATOR "Xcode")
    elseif(Iossim_X86)          
		set(CMAKE_GENERATOR "Xcode")
    elseif(iossim_x86_64)       
		set(CMAKE_GENERATOR "Xcode")
    elseif(linux_x86)           
		set(CMAKE_GENERATOR "Unix Makefiles")
    elseif(linux_x86_64)        
		set(CMAKE_GENERATOR "Unix Makefiles")
	elseif(mac_x86)             
		set(CMAKE_GENERATOR "Xcode")
    elseif(mac_x86_64)          
		set(CMAKE_GENERATOR "Xcode")
	elseif(raspberry_arm32)     
		set(CMAKE_GENERATOR "Unix Makefiles")
    elseif(raspberry_arm64)     
		set(CMAKE_GENERATOR "Unix Makefiles")
    elseif(Win_Arm64_Clang)     
		set(CMAKE_GENERATOR "MinGW Makefiles")
	elseif(Win_Arm64_Msvc)      
		set(CMAKE_GENERATOR "Visual Studio 17 2022")
		set(CMAKE_GENERATOR_PLATFORM ARM64)
		set(MSVC 1)
	elseif(Win_X86_Clang)       
		set(CMAKE_GENERATOR "MinGW Makefiles")
	elseif(Win_X86_Gcc)       
		set(CMAKE_GENERATOR "MinGW Makefiles")
	elseif(Win_X86_Msvc)        
		set(CMAKE_GENERATOR "Visual Studio 17 2022")
		set(CMAKE_GENERATOR_PLATFORM Win32)
		set(MSVC 1)
    elseif(Win_X86_64_Clang)    
		set(CMAKE_GENERATOR "MinGW Makefiles")
    elseif(Win_X86_64_Gcc)   
		set(CMAKE_GENERATOR "MinGW Makefiles")
    elseif(Win_X86_64_Msvc)     
		set(CMAKE_GENERATOR "Visual Studio 17 2022")
		set(CMAKE_GENERATOR_PLATFORM x64)
		set(MSVC 1)
    elseif(Win_X86_64_Ucrt)     
		set(CMAKE_GENERATOR "MinGW Makefiles")
	elseif(Cosmopolitan)     
		set(CMAKE_GENERATOR "MSYS Makefiles")
	else()
		dk_fatal("Could not get CMAKE_GENERATOR from Target_Tuple:${Target_Tuple}")
	endif()
endfunction()






###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
    dk_debugFunc(0)
 
    dk_CMAKE_GENERATOR()
    dk_printVar(CMAKE_GENERATOR)
endfunction()
