include_guard()

###############################################################################
# dk_createOsMacros(func)
#
#	Prefix a function with <OS>_ macros. Calling the <OS>_function will only be called if the current <OS> or <OS_HOST> is true
#
#	@func	- The func of the function to create aliases for
#
function(dk_createOsMacros func)
	#DKDEBUGFUNC(${ARGV})

	if(ext_string)
		dk_error("ext_string variable already in use")
	endif()
	
	### HOST Prefix functions ###
	dk_createPrefixMacro(${func} WIN_HOST)
	dk_createPrefixMacro(${func} WIN_ARM64_HOST)
	dk_createPrefixMacro(${func} WIN_X86_HOST)
	dk_createPrefixMacro(${func} WIN_X86_64_HOST)
	dk_createPrefixMacro(${func} UNIX_HOST)
	dk_createPrefixMacro(${func} MAC_HOST)
	dk_createPrefixMacro(${func} MAC_X86_HOST)
	dk_createPrefixMacro(${func} MAC_X86_64_HOST)
	dk_createPrefixMacro(${func} LINUX_HOST)
	dk_createPrefixMacro(${func} LINUX_ARM64_HOST)
	dk_createPrefixMacro(${func} LINUX_X86_HOST)
	dk_createPrefixMacro(${func} LINUX_X86_64_HOST)
	dk_createPrefixMacro(${func} ANDROID_HOST)
	
	### TARGET Prefix functions ###
	dk_createPrefixMacro(${func} WIN)
	dk_createPrefixMacro(${func} WIN_ARM64)
	dk_createPrefixMacro(${func} WIN_X86)
	dk_createPrefixMacro(${func} WIN_X86_64)
	dk_createPrefixMacro(${func} UNIX)
	dk_createPrefixMacro(${func} APPLE)
	dk_createPrefixMacro(${func} APPLE32)
	dk_createPrefixMacro(${func} APPLE64)
	dk_createPrefixMacro(${func} MAC)
	dk_createPrefixMacro(${func} MAC_X86)
	dk_createPrefixMacro(${func} MAC_X86_64)
	dk_createPrefixMacro(${func} IOS)
	dk_createPrefixMacro(${func} IOS_ARM32)
	dk_createPrefixMacro(${func} IOS_ARM64)
	dk_createPrefixMacro(${func} IOSSIM)
	dk_createPrefixMacro(${func} IOSSIM_X86)
	dk_createPrefixMacro(${func} IOSSIM_X86_64)
	dk_createPrefixMacro(${func} LINUX)
	dk_createPrefixMacro(${func} LINUX_ARM64)
	dk_createPrefixMacro(${func} LINUX_X86)
	dk_createPrefixMacro(${func} LINUX_X86_64)
	dk_createPrefixMacro(${func} RASPBERRY)
	dk_createPrefixMacro(${func} RASPBERRY_ARM32)
	dk_createPrefixMacro(${func} RASPBERRY_ARM64)
	dk_createPrefixMacro(${func} ANDROID)
	dk_createPrefixMacro(${func} ANDROID_ARM32)
	dk_createPrefixMacro(${func} ANDROID_ARM64)
	dk_createPrefixMacro(${func} EMSCRIPTEN)
	
	### TARGET / BUILD Prefix functions ###
	if(NOT "${ARGN}" STREQUAL "NO_DEBUG_RELEASE_TAGS")
		dk_createPrefixMacro(${func} DEBUG)
		dk_createPrefixMacro(${func} WIN DEBUG)
		dk_createPrefixMacro(${func} WIN_X86 DEBUG)
		dk_createPrefixMacro(${func} WIN_X86_64 DEBUG)
		dk_createPrefixMacro(${func} UNIX DEBUG)
		dk_createPrefixMacro(${func} APPLE DEBUG)
		dk_createPrefixMacro(${func} MAC DEBUG)
		dk_createPrefixMacro(${func} MAC_X86 DEBUG)
		dk_createPrefixMacro(${func} MAC_X86_64 DEBUG)
		dk_createPrefixMacro(${func} IOS DEBUG)
		dk_createPrefixMacro(${func} IOS_ARM32 DEBUG)
		dk_createPrefixMacro(${func} IOS_ARM64 DEBUG)
		dk_createPrefixMacro(${func} IOSSIM DEBUG)
		dk_createPrefixMacro(${func} IOSSIM_X86 DEBUG)
		dk_createPrefixMacro(${func} IOSSIM_X86_64 DEBUG)
		dk_createPrefixMacro(${func} LINUX DEBUG)
		dk_createPrefixMacro(${func} LINUX_X86 DEBUG)
		dk_createPrefixMacro(${func} LINUX_X86_64 DEBUG)
		dk_createPrefixMacro(${func} RASPBERRY DEBUG)
		dk_createPrefixMacro(${func} RASPBERRY_ARM32 DEBUG)
		dk_createPrefixMacro(${func} RASPBERRY_ARM64 DEBUG)
		dk_createPrefixMacro(${func} ANDROID DEBUG)
		dk_createPrefixMacro(${func} ANDROID_ARM32 DEBUG)
		dk_createPrefixMacro(${func} ANDROID_ARM64 DEBUG)
		dk_createPrefixMacro(${func} EMSCRIPTEN DEBUG)
		
		dk_createPrefixMacro(${func} RELEASE)
		dk_createPrefixMacro(${func} WIN RELEASE)
		dk_createPrefixMacro(${func} WIN_X86 RELEASE)
		dk_createPrefixMacro(${func} WIN_X86_64 RELEASE)
		dk_createPrefixMacro(${func} UNIX RELEASE)
		dk_createPrefixMacro(${func} APPLE RELEASE)
		dk_createPrefixMacro(${func} MAC RELEASE)
		dk_createPrefixMacro(${func} MAC_X86 RELEASE)
		dk_createPrefixMacro(${func} MAC_X86_64 RELEASE)
		dk_createPrefixMacro(${func} IOS RELEASE)
		dk_createPrefixMacro(${func} IOS_ARM32 RELEASE)
		dk_createPrefixMacro(${func} IOS_ARM64 RELEASE)
		dk_createPrefixMacro(${func} IOSSIM RELEASE)
		dk_createPrefixMacro(${func} IOSSIM_X86 RELEASE)
		dk_createPrefixMacro(${func} IOSSIM_X86_64 RELEASE)
		dk_createPrefixMacro(${func} LINUX RELEASE)
		dk_createPrefixMacro(${func} LINUX_X86 RELEASE)
		dk_createPrefixMacro(${func} LINUX_X86_64 RELEASE)
		dk_createPrefixMacro(${func} RASPBERRY RELEASE)
		dk_createPrefixMacro(${func} RASPBERRY_ARM32 RELEASE)
		dk_createPrefixMacro(${func} RASPBERRY_ARM64 RELEASE)
		dk_createPrefixMacro(${func} ANDROID RELEASE)
		dk_createPrefixMacro(${func} ANDROID_ARM32 RELEASE)
		dk_createPrefixMacro(${func} ANDROID_ARM64 RELEASE)
		dk_createPrefixMacro(${func} EMSCRIPTEN RELEASE)
	endif()
	
endfunction()
