#!/usr/bin/cmake -P
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
	cmake_policy(SET CMP0009 NEW)
	file(GLOB_RECURSE DK.cmake "/DK.cmake")
	list(GET DK.cmake 0 DK.cmake)
	get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK.cmake}" DIRECTORY)
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()

###############################################################################
# dk_generateAppCmake(Target_App_Dir) + DEPENDENCIES
#
#
function(dk_generateAppCmake Target_App_Dir)
	dk_debugFunc()
	set(Target_App_Dir ${ARGV0})
	set(DK_DEPENDENCIES ${ARGN})
	
	if(Target_App_Dir MATCHES "DKCMake")
		return()
	endif()
	dk_load(dk_builder)
	
	dk_basename(${Target_App_Dir} Target_App)
	
	dk_fileWrite(${Target_App_Dir}/CMakeLists.txt
####################################################
################## CMakeLists.txt ##################

"### This file is generated by DKCMake. Any Changes here, will be overwritten. ###
#include_guard()
message(\"\${ESC}[46m \${ESC}[30m ***\${CMAKE_CURRENT_LIST_FILE}*** \${ESC}[0m\")
cmake_minimum_required(VERSION 3.10)
include(\$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake)
	
###### DEPENDENCIES ######
foreach(dependency ${DK_DEPENDENCIES})
	message(\"added dependency \${dependency}\")
	dk_depend(\${dependency})
endforeach()
##########################
set(CMAKE_SYSTEM_NAME Generic)

project(${Target_App}_PROJECT)

dk_set(Target_App	${Target_App})
dk_configureApp(${Target_App_Dir})

###################################################
###################################################
\n")

endfunction()





###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc()
	
	dk_validate(DKCPP_APPS_DIR "dk_DKBRANCH_DIR()")
	dk_generateAppCmake("$ENV{DKCPP_APPS_DIR}/DKCore")
endfunction()