#!/usr/bin/cmake -P
include(${DKCMAKE_FUNCTIONS_DIR_}DK.cmake)
#include_guard()

###############################################################################
# dk_generateAppCmake(DK_PROJECT_DIR) + DEPENDENCIES
#
#
function(dk_generateAppCmake DK_PROJECT_DIR) # + DEPENDENCIES
	dk_debugFunc()
	
	dk_load(dk_builder)
	
	set(DK_PROJECT_DIR ${ARGV0})
	set(DK_DEPENDENCIES ${ARGN})
	dk_basename(${DK_PROJECT_DIR} APP_NAME)
	
dk_fileWrite(${CMAKE_SOURCE_DIR}/CMakeLists.txt

####################################################
################## CMakeLists.txt ##################

	"### This file is generated by DKCMake. Any Changes here, will be overwritten. ###
	cmake_minimum_required(VERSION 3.10)
	include(\${DKCMAKE_FUNCTIONS_DIR}/DK.cmake)
		
	###### DEPENDENCIES ######
	foreach(dependency ${DK_DEPENDENCIES})
		dk_depend(\${dependency})
    endforeach()
	##########################

	dk_set(APP_NAME	${APP_NAME}) 
	dk_configureApp(${DK_PROJECT_DIR})
	
###################################################
###################################################
\n")

endfunction()





###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc()
	
	dk_validate(DKAPPS_DIR "dk_DKAPPS_DIR()")
	dk_generateAppCmake("${DKAPPS_DIR}/DKCore")
endfunction()