#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT DEFINED DKINIT_cmake)
	if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
		cmake_policy(SET CMP0009 NEW)
		file(GLOB_RECURSE DK_cmake "/DK.cmake")
		list(GET DK_cmake 0 DK_cmake)
		get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK_cmake}" DIRECTORY)
		set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
	endif()
	include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
endif()
#########################################################################


#########################################################################
# dk_generateCmake(Source_Dir)
#
#	Generate a CMakeLists.txt for the given path
#
#	@Source_Dir	- TODO
#
function(dk_generateCmake)
	dk_debugFunc(0 1)

	dk_assertPath(${CURRENT_PLUGIN})
	dk_basename("${${CURRENT_PLUGIN}}")
	set(Plugin_Name "${dk_basename}")
	
	if(ARGV)
		set(Source_Dir "${ARGV0}")
	else()
		set(Source_Dir "${${CURRENT_PLUGIN}}")
	endif()
	dk_assertPath(Source_Dir)

	if(NOT "${SOURCE_DIR}" STREQUAL "${${CURRENT_PLUGIN}}")
		dk_notice("dk_generateCmake(): Source_Dir:${Source_Dir} != CURRENT_PLUGIN:${${CURRENT_PLUGIN}}")
	endif()
	
	# enclose list items in quotes " "
	set(DKINCLUDES_LIST_quoted "")
	foreach(item IN LISTS DKINCLUDES_LIST)
		list(APPEND DKINCLUDES_LIST_quoted "\"${item}\"")
	endforeach()

	# enclose list items in quotes " "
	set(DKLINKDIRS_LIST_quoted "")
	foreach(item IN LISTS DKLINKDIRS_LIST)
		list(APPEND DKLINKDIRS_LIST_quoted "\"${item}\"")
	endforeach()



	###### Create CmakeLists.txt file ######
	dk_delete(${Source_Dir}/CMakeLists.txt)
	dk_fileWrite("${Source_Dir}/CMakeLists.txt" " 
### This file is generated by DKCMake. Any Changes here, will be overwritten. ###
### ${Plugin_Name} ###
cmake_minimum_required(VERSION 3.10)
# cmake_policy(SET CMP0054 NEW)
project(${Plugin_Name})


include_directories(\"${DKCPP_PLUGINS_DIR}\")
include_directories("${DKINCLUDES_LIST_quoted}")
add_definitions("${DKDEFINES_LIST}")
link_directories("${DKLINKDIRS_LIST_quoted}")
file(GLOB ${Plugin_Name}_SRC
    \"${Source_Dir}/*.h\"
	\"${Source_Dir}/*.c\"
	\"${Source_Dir}/*.cpp\"
)

if(Windows)
	file(GLOB WIN_SRC
		\"${Source_Dir}/*.rc\"
		\"${Source_Dir}/*.manifest\"
	)
	list(APPEND ${Plugin_Name}_SRC \${WIN_SRC})
endif()
if(Ios OR Iossim)
	file(GLOB IOS_SRC
		\"${Source_Dir}/*.mm\"
	)
	list(APPEND ${Plugin_Name}_SRC \${IOS_SRC})
endif()

add_library(${Plugin_Name} STATIC \${${Plugin_Name}_SRC})

"
[=[
	#target_compile_options(${Plugin_Name} PRIVATE \${CMAKE_CXX_FLAGS} $<$<CONFIG:Debug>:\${CMAKE_CXX_FLAGS_DEBUG}> $<$<CONFIG:Release>:\${CMAKE_CXX_FLAGS_RELEASE}>)
]=]
"

if(MSVC)
	set_target_properties(${Plugin_Name} PROPERTIES LINKER_LANGUAGE CPP)
	set_property(DIRECTORY \"\${CMAKE_CURRENT_SOURCE_DIR}\" PROPERTY VS_STARTUP_PROJECT ${Plugin_Name})
endif()
" 
)


# install(TARGETS ${Plugin_Name} DESTINATION lib/\${Target_Tuple})"
# file(GLOB HEADER_FILES ${Source_Dir}/*.h)"
# install(FILES \${HEADER_FILES} DESTINATION include/${Plugin_Name})"
# if(NOT DKAPP)"
#	set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT ${Plugin_Name})"
# endif()"
# add headers to DKPlugins.h
# if(${Plugin_Name} STREQUAL DK OR STATIC)
# if(${Plugin_Name} STREQUAL DK OR BUILD_STATIC_LIBS)

		
	file(GLOB HEADER_FILES RELATIVE ${DKCPP_PLUGINS_DIR} ${Source_Dir}/*.h)
	foreach(header ${HEADER_FILES})
		if(NOT PLUGINS_FILE MATCHES "${header}")
			dk_info("Adding ${header} to header file.")
			dk_set(PLUGINS_FILE ${PLUGINS_FILE} "#include \"${header}\"\n")
		endif()
		#if(NOT PLUGINS_FILE MATCHES "DKHAVE_${Plugin_Name}")
		#	dk_info("Adding #define DKHAVE_${Plugin_Name} 1 to header file.")
		#	dk_set(PLUGINS_FILE ${PLUGINS_FILE} "#define DKHAVE_${Plugin_Name} 1\"
		#endif()
	endforeach()
	#endif()
	
	dk_enable				(${Plugin_Name})
	if(MSVC)
		dk_if(Windows		"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/${Plugin_Name}.lib\")")
		dk_if(Windows		"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/${Plugin_Name}.lib\")")
	else()
		dk_if(Windows		"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
		dk_if(Windows		"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")
	endif()
	dk_if(Mac				"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Mac				"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Ios				"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/Debug-iphoneos/lib${Plugin_Name}.a\")")
	dk_if(Ios				"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/Release-iphoneos/lib${Plugin_Name}.a\")")
	dk_if(Iossim			"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/Debug-iphonesimulator/lib${Plugin_Name}.a\")")
	dk_if(Iossim			"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/Release-iphonesimulator/lib${Plugin_Name}.a\")")
	dk_if(Linux				"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Linux				"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Raspberry			"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Raspberry			"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Android			"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Android			"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Emscripten		"dk_libDebug(\"${Source_Dir}/${Target_Tuple}/${Debug_Dir}/lib${Plugin_Name}.a\")")
	dk_if(Emscripten		"dk_libRelease(\"${Source_Dir}/${Target_Tuple}/${Release_Dir}/lib${Plugin_Name}.a\")")

	dk_verbose("dk_append(DKPLUGIN_LIST ${Plugin_Name})  #Add to list")
	dk_append(DKPLUGIN_LIST ${Plugin_Name})  #Add to list
endfunction()





###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_generateCmake()
endfunction()