include(${DKCMAKE_FUNCTIONS_DIR}/DK.cmake)
##include_guard()

###############################################################################
# dk_printColors()
#
#	TODO
#
function(dk_printColors)
	dk_debugFunc(${ARGV})
	
	dk_echo("")
	dk_echo("${ESC}[101;93m STYLES ${clr}")
	dk_echo("\${clr}        ${clr}Reset${clr}")
	dk_echo("\${bold}       ${bold}Bold${clr}")
	dk_echo("\${underline}  ${underline}Underline${clr}")
	dk_echo("\${inverse}    ${inverse}Inverse${clr}")
	dk_echo("")
	dk_echo("${ESC}[101;93m NORMAL FOREGROUND COLORS ${clr}")
	dk_echo("\${black}      ${black}Black${clr}")
	dk_echo("\${red}        ${red}Red${clr}")
	dk_echo("\${green}      ${green}Green${clr}")
	dk_echo("\${yellow}     ${yellow}Yellow${clr}")
	dk_echo("\${blue}       ${blue}BLUE${clr}")
	dk_echo("\${magenta}    ${magenta}Magenta${clr}")
	dk_echo("\${cyan}       ${cyan}Cyan${clr}")
	dk_echo("\${white}      ${white}White${clr}")
	dk_echo("")
	dk_echo("${ESC}[101;93m NORMAL BACKGROUND COLORS ${clr}")
	dk_echo("\${bg_black}   ${bg_black}Black${clr}")
	dk_echo("\${bg_red}     ${bg_red}Red${clr}")
	dk_echo("\${bg_green}   ${bg_green}Green${clr}")
	dk_echo("\${bg_yellow}  ${bg_yellow}Yellow${clr}")
	dk_echo("\${bg_blue}    ${bg_blue}BLUE${clr}")
	dk_echo("\${bg_magenta} ${bg_magenta}Magenta${clr}")
	dk_echo("\${bg_cyan}    ${bg_cyan}Cyan${clr}")
	dk_echo("\${bg_white}   ${bg_white}White${clr}")
	dk_echo("")
	dk_echo("${ESC}[101;93m STRONG FOREGROUND COLORS ${clr}")
	dk_echo("\${BLACK}      ${BLACK}Black${clr}")
	dk_echo("\${RED}        ${RED}Red${clr}")
	dk_echo("\${GREEN}      ${GREEN}Green${clr}")
	dk_echo("\${YELLOW}     ${YELLOW}Yellow${clr}")
	dk_echo("\${BLUE}       ${BLUE}BLUE${clr}")
	dk_echo("\${MAGENTA}    ${MAGENTA}Magenta${clr}")
	dk_echo("\${CYAN}       ${CYAN}Cyan${clr}")
	dk_echo("\${WHITE}      ${WHITE}White${clr}")
	dk_echo("")
	dk_echo("${ESC}[101;93m STRONG BACKGROUND COLORS ${clr}")
	dk_echo("\${BG_BLACK}   ${BG_BLACK}Black${clr}")
	dk_echo("\${BG_RED}     ${BG_RED}Red${clr}")
	dk_echo("\${BG_GREEN}   ${BG_GREEN}Green${clr}")
	dk_echo("\${BG_YELLOW}  ${BG_YELLOW}Yellow${clr}")
	dk_echo("\${BG_BLUE}    ${BG_BLUE}BLUE${clr}")
	dk_echo("\${BG_MAGENTA} ${BG_MAGENTA}Magenta${clr}")
	dk_echo("\${BG_CYAN}    ${BG_CYAN}Cyan${clr}")
	dk_echo("\${BG_WHITE}   ${BG_WHITE}White${clr}")
	dk_echo("")
	dk_echo("${ESC}[101;93m COMBINATIONS ${clr}")
	dk_echo("\${ESC}[31m                       ${ESC}[31mred foreground color${clr}")
	dk_echo("\${ESC}[7m                        ${ESC}[7minverse foreground <-> background${clr}")
	dk_echo("\${ESC}[7;31m                     ${ESC}[7;31minverse red foreground color${clr}")
	dk_echo("\${ESC}[7m and nested \${ESC}[31m  ${ESC}[7mbefore ${ESC}[31mnested${clr}")
	dk_echo("\${ESC}[31m and nested \${ESC}[7m  ${ESC}[31mbefore ${ESC}[7mnested${clr}")
endfunction()




function(DKTEST) ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST #######
	dk_debugFunc(${ARGV})
	
	dk_printColors()
endfunction()