include_guard()

###############################################################################
# dk_printSettings()
#
#	TODO
#
#	https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html
#
function(dk_printSettings)
	DKDEBUGFUNC(${ARGV})
	
	dk_buildLog("#############  DigitalKnob  ############")
	dk_buildLog(DKBRANCH)
	dk_buildLog(DIGITALKNOB_DIR)
	dk_buildLog(DKTOOLS_DIR)
	dk_buildLog(DKBRANCH_DIR)
	dk_buildLog(DK3RDPARTY_DIR)
	dk_buildLog(DKIMPORTS_DIR)
	dk_buildLog(DKAPPS_DIR)
	dk_buildLog(DKPLUGINS_DIR)
	dk_buildLog(BUILD_DIR)
	
	dk_buildLog("#################  CMAKE VARIABLES  ################")
	#dk_getCmakeCommandLine(CMAKE_COMMAND_LINE)
	dk_buildLog(CMAKE_COMMAND_LINE)
	dk_buildLog(CMAKE_COMMAND)
	dk_buildLog(CMAKE_EXE)
	dk_buildLog(CMAKE_VERSION)
	
	dk_buildLog("#################  HOST VARIABLES  ################")
	dk_buildLog(CMAKE_HOST_SYSTEM_NAME)
	dk_buildLog(CMAKE_HOST_SYSTEM_VERSION)
	dk_buildLog(CMAKE_HOST_SYSTEM_PROCESSOR)
	dk_buildLog(CMAKE_LIBRARY_ARCHITECTURE)
	dk_buildLog(CMAKE_CPP_COMPILER_ID)
	dk_buildLog(CMAKE_CXX_COMPILER_ID)
	dk_buildLog(ENV{USERNAME})
	dk_buildLog(ENV{USER})
	#dk_buildLog(ENV{PATH})
	execute_process(COMMAND uname OUTPUT_VARIABLE UNAME OUTPUT_STRIP_TRAILING_WHITESPACE)
	dk_buildLog(UNAME)
	dk_buildLog(MINGW)
	dk_buildLog(MSYS)
	dk_buildLog(MSVC)
	#dk_buildLog(VISUAL_STUDIO)
	dk_buildLog(XCODE)
	
	dk_buildLog("#################  TARGET VARIABLES  ################")
	dk_buildLog(CMAKE_SYSTEM)
	dk_buildLog(CMAKE_SYSTEM_NAME)
	dk_buildLog(CMAKE_BINARY_DIR)
	dk_buildLog(CMAKE_ARCHIVE_OUTPUT_DIRECTORY)
	dk_buildLog(CMAKE_LIBRARY_OUTPUT_DIRECTORY)
	dk_buildLog(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
	dk_buildLog(CMAKE_GENERATOR)
	dk_buildLog(CMAKE_MAKE_PROGRAM)
	dk_buildLog(CMAKE_TOOLCHAIN_FILE)
	dk_buildLog(CMAKE_C_COMPILER)
	dk_buildLog(CMAKE_C_STANDARD)
	dk_buildLog(CMAKE_C_STANDARD_REQUIRED)
	dk_buildLog(CMAKE_C_EXTENSIONS)
	dk_buildLog(CMAKE_C_FLAGS)
	dk_buildLog(CMAKE_C_FLAGS_DEBUG)
	dk_buildLog(CMAKE_C_FLAGS_RELEASE)
	dk_buildLog(CMAKE_CXX_COMPILER)
	dk_buildLog(CMAKE_CXX_STANDARD)
	dk_buildLog(CMAKE_CXX_STANDARD_REQUIRED)
	dk_buildLog(CMAKE_CXX_EXTENSIONS)
	dk_buildLog(CMAKE_CXX_FLAGS)
	dk_buildLog(CMAKE_CXX_FLAGS_DEBUG)
	dk_buildLog(CMAKE_CXX_FLAGS_RELEASE)
	dk_buildLog(MULTI_CONFIG)
	dk_buildLog(SINGLE_CONFIG)
	dk_buildLog(APP_NAME)
	dk_buildLog(DK_PROJECT_DIR)
	dk_buildLog(DEBUG_DIR)
	dk_buildLog(RELEASE_DIR)
	dk_buildLog(VS_STARTUP_PROJECT)
	dk_buildLog(OS)
	dk_buildLog(DEBUG)
	dk_buildLog(RELEASE)
	dk_buildLog(BUILD)
	dk_buildLog(REBUILD)
	dk_buildLog(REBUILDALL)
	dk_buildLog(DKCEF)
	dk_buildLog(WIN)
	dk_buildLog(WIN_X86)
	dk_buildLog(WIN_X86_64)
	dk_buildLog(MAC)
	dk_buildLog(MAC_X86)
	dk_buildLog(MAC_X86_64)
	dk_buildLog(IOS)
	dk_buildLog(IOS_ARM32)
	dk_buildLog(IOS_ARM64)
	dk_buildLog(IOSSIM)
	dk_buildLog(IOSSIM_X86)
	dk_buildLog(IOSSIM_X86_64)
	dk_buildLog(LINUX)
	dk_buildLog(LINUX_X86)
	dk_buildLog(LINUX_X86_64)
	dk_buildLog(ANDROID)
	dk_buildLog(ANDROID_ARM32)
	dk_buildLog(ANDROID_ARM64)
	dk_buildLog(RASPBERRY)
	dk_buildLog(RASPBERRY_ARM32)
	dk_buildLog(RASPBERRY_ARM64)
	dk_buildLog(EMSCRIPTEN)
	dk_buildLog("")
endfunction()