#!/usr/bin/cmake -P
include(${DKCMAKE_FUNCTIONS_DIR_}DK.cmake)
#include_guard()

##################################################################################
# dk_pickOS()
#
#
function(dk_pickOS)
	dk_debugFunc()

	dk_echo("")
	dk_echo("${APP} ${target_triple} ${TYPE}")
	dk_echo("")
    dk_echo(" 1) ${host_triple}")
	dk_echo("")
	dk_echo(" 2) cosmopolitan")
	dk_echo(" 3) Android arm32")
	dk_echo(" 4) Android arm64")
	dk_echo(" 5) Android x86")
	dk_echo(" 6) Android x86_64")
	dk_echo(" 7) Emscripten")
	dk_echo(" 8) Ios arm32")
	dk_echo(" 9) Ios arm64")
	dk_echo("10) Ios x86")
	dk_echo("11) Ios x86_64")
	dk_echo("12) Iossim arm32")
	dk_echo("13) Iossim arm64")
	dk_echo("14) Iossim x86")
	dk_echo("15) Iossim x86_64")
	dk_echo("16) Linux arm32")
	dk_echo("17) Linux arm64")
	dk_echo("18) Linux x86")
	dk_echo("19) Linux x86_64")
	dk_echo("20) Mac arm32")
	dk_echo("21) Mac arm64")
	dk_echo("22) Mac x86")
	dk_echo("23) Mac x86_64")
	dk_echo("24) Raspberry arm32")
	dk_echo("25) Raspberry arm64")
	dk_echo("26) Raspberry x86")
	dk_echo("27) Raspberry x86_64")
	dk_echo("28) Windows arm32")
	dk_echo("29) Windows arm64 (clang)")
	dk_echo("30) Windows x86 (gcc)")
	dk_echo("31) Windows x86 (clang)")
	dk_echo("32) Windows x86 (msvc)")
	dk_echo("33) Windows x86_64 (gcc)")
    dk_echo("34) Windows x86_64 (clang)")
    dk_echo("35) Windows x86_64 (ucrt)")
    dk_echo("36) Windows x86_64 (msvc)")
	dk_echo("37) Clear Screen")
	dk_echo("38) Go Back")
	dk_echo("39) Exit")
	dk_echo("")
	
	dk_keyboardInput(input)
	if("${input}" EQUAL "0")
		dk_echo("repeating last selection")
		dk_set(APP ${_APP_})
		dk_set(target_triple ${_target_triple_})
		dk_set(TYPE ${_TYPE_})
		dk_set(UPDATE 1)
	elseif("${input}" EQUAL "1")
		dk_set(target_triple "${host_triple}")
	elseif("${input}" EQUAL "2")
		dk_set(target_triple "cosmo")
	elseif("${input}" EQUAL "3")
		dk_set(target_triple "android_arm32")
	elseif("${input}" EQUAL "4")
		dk_set(target_triple "android_arm64")
	elseif("${input}" EQUAL "5")
		dk_set(target_triple "android_x86")
	elseif("${input}" EQUAL "6")
		dk_set(target_triple "android_x86_64")
	elseif("${input}" EQUAL "7")
		dk_set(target_triple "emscripten")
	elseif("${input}" EQUAL "8")
		dk_set(target_triple "ios_arm32")
	elseif("${input}" EQUAL "9")
		dk_set(target_triple "ios_arm64")
	elseif("${input}" EQUAL "10")
		dk_set(target_triple "ios_x86")
	elseif("${input}" EQUAL "11")
		dk_set(target_triple "ios_x86_64")
	elseif("${input}" EQUAL "12")
		dk_set(target_triple "iossim_arm32")
	elseif("${input}" EQUAL "13")
		dk_set(target_triple "iossim_arm64")
	elseif("${input}" EQUAL "14")
		dk_set(target_triple "iossim_x86")
	elseif("${input}" EQUAL "15")
		dk_set(target_triple "iossim_x86_64")
	elseif("${input}" EQUAL "16")
		dk_set(target_triple "linux_arm32")
	elseif("${input}" EQUAL "17")
		dk_set(target_triple "linux_arm64")
	elseif("${input}" EQUAL "18")
		dk_set(target_triple "linux_x86")
	elseif("${input}" EQUAL "19")
		dk_set(target_triple "linux_x86_64")
	elseif("${input}" EQUAL "20")
		dk_set(target_triple "mac_arm32")
	elseif("${input}" EQUAL "21")
		dk_set(target_triple "mac_arm64")
	elseif("${input}" EQUAL "22")
		dk_set(target_triple "mac_x86")
	elseif("${input}" EQUAL "23")
		dk_set(target_triple "mac_x86_64")
	elseif("${input}" EQUAL "24")
		dk_set(target_triple "raspberry_arm32")
	elseif("${input}" EQUAL "25")
		dk_set(target_triple "raspberry_arm64")
	elseif("${input}" EQUAL "26")
		dk_set(target_triple "raspberry_x86")
	elseif("${input}" EQUAL "27")
		dk_set(target_triple "raspberry_x64")
	elseif("${input}" EQUAL "28")
		dk_set(target_triple "win_arm32")
	elseif("${input}" EQUAL "29")
		dk_set(target_triple "win_arm64_clang")
	elseif("${input}" EQUAL "30")
		dk_set(target_triple "win_x86_mingw")
	elseif("${input}" EQUAL "31")
		dk_set(target_triple "win_x86_clang")
	elseif("${input}" EQUAL "32")
		dk_set(target_triple "win_x86_msvc")
	elseif("${input}" EQUAL "33")
		dk_set(target_triple "win_x86_64_mingw")
	elseif("${input}" EQUAL "34")
		dk_set(target_triple "win_x86_64_clang")
	elseif("${input}" EQUAL "35")
		dk_set(target_triple "win_x86_64_ucrt")
	elseif("${input}" EQUAL "36")
		dk_set(target_triple "win_x86_64_msvc")
	elseif("${input}" EQUAL "37")
		dk_clearScreen()
	elseif("${input}" EQUAL "38")
		dk_unset(APP)
	elseif("${input}" EQUAL "39")
		dk_exit(0)
	else()
		dk_warning("invalid selection")
	endif()
endfunction()



###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_pickOS()
endfunction()