include(${DKCMAKE_FUNCTIONS_DIR}/DK.cmake)
#include_guard()

###############################################################################
# dk_setTargetTriple()
#
#
function(dk_setTargetTriple)
	dk_debugFunc(${ARGV})
	
	dk_validate(HOST_TRIPLE "dk_getHostTriple()")
	dk_assert(HOST_TRIPLE)
	
	dk_echo()
    dk_echo(" 1) ${HOST_TRIPLE}")
	dk_echo()
	dk_echo(" 2) Android arm32")
	dk_echo(" 3) Android arm64")
	dk_echo(" 4) Android x86")
	dk_echo(" 5) Android x86_64")
	dk_echo(" 6) Emscripten")
	dk_echo(" 7) Ios arm32")
	dk_echo(" 8) Ios arm64")
	dk_echo(" 9) Ios x86")
	dk_echo("10) Ios x86_64")
	dk_echo("11) Iossim arm32")
	dk_echo("12) Iossim arm64")
	dk_echo("13) Iossim x86")
	dk_echo("14) Iossim x86_64")
	dk_echo("15) Linux arm32")
	dk_echo("16) Linux arm64")
	dk_echo("17) Linux x86")
	dk_echo("18) Linux x86_64")
	dk_echo("19) Mac arm32")
	dk_echo("20) Mac arm64")
	dk_echo("21) Mac x86")
	dk_echo("22) Mac x86_64")
	dk_echo("23) Raspberry arm32")
	dk_echo("24) Raspberry arm64")
	dk_echo("25) Raspberry x86")
	dk_echo("26) Raspberry x86_64")
	dk_echo("27) Windows arm32")
	dk_echo("28) Windows arm64 (clang)")
	dk_echo("29) Windows x86 (gcc)")
	dk_echo("30) Windows x86 (clang)")
	dk_echo("31) Windows x86 (msvc)")
	dk_echo("32) Windows x86_64 (gcc)")
    dk_echo("33) Windows x86_64 (clang)")
    dk_echo("34) Windows x86_64 (ucrt)")
    dk_echo("35) Windows x86_64 (msvc)")
	dk_echo("38) Exit")
	dk_echo()
	
	dk_keyboardInput(input)
	if("${input}" EQUAL "0")
		#dk_echo("repeating last selection")
		#dk_set(APP ${_APP_})
		#dk_set(dk_getTargetTriple ${_TARGET_OS_})
		#dk_set(TYPE ${_TYPE_})
	elseif("${input}" EQUAL "1")
		dk_set(DK_TARGET_OS "${HOST_TRIPLE-}")
	elseif("${input}" EQUAL "2")
		dk_set(DK_TARGET_OS "android")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "3")
		dk_set(DK_TARGET_OS "android")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "4")
		dk_set(DK_TARGET_OS "android")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "5")
		dk_set(DK_TARGET_OS "android")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "6")
		dk_set(DK_TARGET_OS "emscripten")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "7")
		dk_set(DK_TARGET_OS "ios")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "8")
		dk_set(DK_TARGET_OS "ios")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "9")
		dk_set(DK_TARGET_OS "ios")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "10")
		dk_set(DK_TARGET_OS "ios")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "11")
		dk_set(DK_TARGET_OS "iossim")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "12")
		dk_set(DK_TARGET_OS "iossim")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "13")
		dk_set(DK_TARGET_OS "iossim")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "14")
		dk_set(DK_TARGET_OS "iossim")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "15")
		dk_set(DK_TARGET_OS "linux")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "16")
		dk_set(DK_TARGET_OS "linux")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "17")
		dk_set(DK_TARGET_OS "linux")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "18")
		dk_set(DK_TARGET_OS "linux")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "19")
		dk_set(DK_TARGET_OS "mac")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "20")
		dk_set(DK_TARGET_OS "mac")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "21")
		dk_set(DK_TARGET_OS "mac")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "22")
		dk_set(DK_TARGET_OS "mac")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "23")
		dk_set(DK_TARGET_OS "raspberry")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "24")
		dk_set(DK_TARGET_OS "raspberry")
		dk_set(DK_TARGET_ARCH "arm64")
	elseif("${input}" EQUAL "25")
		dk_set(DK_TARGET_OS "raspberry")
		dk_set(DK_TARGET_ARCH "x86")
	elseif("${input}" EQUAL "26")
		dk_set(DK_TARGET_OS "raspberry")
		dk_set(DK_TARGET_ARCH "x86_64")
	elseif("${input}" EQUAL "27")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "arm32")
	elseif("${input}" EQUAL "28")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "arm64")
		dk_set(DK_TARGET_ENV "clang")
	elseif("${input}" EQUAL "29")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86")
		dk_set(DK_TARGET_ENV "mingw")
	elseif("${input}" EQUAL "30")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86")
		dk_set(DK_TARGET_ENV "clang")
	elseif("${input}" EQUAL "31")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86")
		dk_set(DK_TARGET_ENV "msvc")
	elseif("${input}" EQUAL "32")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86_64")
		dk_set(DK_TARGET_ENV "mingw")
	elseif("${input}" EQUAL "33")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86_64")
		dk_set(DK_TARGET_ENV "clang")
	elseif("${input}" EQUAL "34")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86_64")
		dk_set(DK_TARGET_ENV "ucrt")
	elseif("${input}" EQUAL "35")
		dk_set(DK_TARGET_OS "win")
		dk_set(DK_TARGET_ARCH "x86_64")
		dk_set(DK_TARGET_ENV "msvc")
	elseif("${input}" EQUAL "38")
		dk_exit(0)
	else()
		dk_warning("invalid selection")
	endif()
	
	if(DK_TARGET_ENV)
		dk_set(DK_TARGET_TRIPLE "${DK_TARGET_OS}_${DK_TARGET_ARCH}_${DK_TARGET_ENV}")
	else()
		dk_set(DK_TARGET_TRIPLE "${DK_TARGET_OS}_${DK_TARGET_ARCH}")
	endif()
	
	dk_printVar(DKSCRIPT_PATH)
	dk_pause()
endfunction()






###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(${ARGV})
	
	dk_setTargetTriple()
endfunction()