#!/usr/bin/cmake -P
include(${DKCMAKE_FUNCTIONS_DIR_}DK.cmake)
include_guard()

###############################################################################
# dk_target_triple_SET()
#
#
function(dk_target_triple_SET)
	dk_debugFunc()
	message("dk_target_triple_SET(${ARGV})")

	set(default_target_env "clang")

	if(CMAKE_SCRIPT_MODE_FILE)
		dk_validate(host_triple "dk_host_triple()")
		
		dk_echo()
		dk_echo(" 1) ${host_triple}_${default_target_env}")
		dk_echo()
		dk_echo(" 2) cosmopolitan")
		dk_echo(" 3) android_arm32_clang")
		dk_echo(" 4) android_arm64_clang")
		dk_echo(" 5) android_x86_clang")
		dk_echo(" 6) android_x86_64_clang")
		dk_echo(" 7) emscripten_x86_clang")
		dk_echo(" 8) ios_arm32_clang")
		dk_echo(" 9) ios_arm64_clang")
		dk_echo("10) ios_x86_clang")
		dk_echo("11) ios_x86_64_clang")
		dk_echo("12) iossim_arm32_clang")
		dk_echo("13) iossim_arm64_clang")
		dk_echo("14) iossim_x86_clang")
		dk_echo("15) iossim_x86_64_clang")
		dk_echo("16) linux_arm32_clang")
		dk_echo("17) linux_arm64_clang")
		dk_echo("18) linux_x86_clang")
		dk_echo("19) linux_x86_64_clang")
		dk_echo("20) mac_arm32_clang")
		dk_echo("21) mac_arm64_clang")
		dk_echo("22) mac_x86_clang")
		dk_echo("23) mac_x86_64_clang")
		dk_echo("24) raspberry_arm32_clang")
		dk_echo("25) raspberry_arm64_clang")
		dk_echo("26) raspberry_x86_clang")
		dk_echo("27) raspberry_x86_64_clang")
		dk_echo("28) windows_arm32_clang")
		dk_echo("29) windows_arm64_clang")
		dk_echo("30) windows_x86_clang")
		dk_echo("31) windows_x86_gcc")
		dk_echo("32) windows_x86_msvc")
		dk_echo("33) windows_x86_64_clang")
		dk_echo("34) windows_x86_64_gcc")
		dk_echo("35) windows_x86_64_msvc")
		dk_echo("36) windows_x86_64_ucrt")
		dk_echo("37) Exit")
		dk_echo()
		
		dk_keyboardInput(input)
		if("${input}" STREQUAL "0")
			#dk_echo("repeating last selection")
			#dk_set(target_app 		${_target_app_})
			#dk_set(target_os 		${_target_os_})
			#dk_set(target_type 	${_target_type_})
		elseif("${input}" STREQUAL "1")
			dk_set(target_triple 	"${host_triple}")
			dk_set(target_os     	"${host_os}")
			dk_set(target_arch  	"${host_arch}")
			if(default_target_env)
				dk_set(target_env  "${default_target_env}")
			endif()
		elseif("${input}" STREQUAL "2")
			dk_set(target_os "cosmopolitan")
			dk_set(target_arch "cosmopolitan")
			dk_set(target_env "cosmopolitan")
		elseif("${input}" STREQUAL "3")
			dk_set(target_os "android")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "4")
			dk_set(target_os "android")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "5")
			dk_set(target_os "android")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "6")
			dk_set(target_os "android")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "7")
			dk_set(target_os "emscripten")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "8")
			dk_set(target_os "ios")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "9")
			dk_set(target_os "ios")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "10")
			dk_set(target_os "ios")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "11")
			dk_set(target_os "ios")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "12")
			dk_set(target_os "iossim")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "13")
			dk_set(target_os "iossim")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "14")
			dk_set(target_os "iossim")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "15")
			dk_set(target_os "iossim")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "16")
			dk_set(target_os "linux")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "17")
			dk_set(target_os "linux")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "18")
			dk_set(target_os "linux")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "19")
			dk_set(target_os "linux")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "20")
			dk_set(target_os "mac")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "21")
			dk_set(target_os "mac")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "22")
			dk_set(target_os "mac")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "23")
			dk_set(target_os "mac")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "24")
			dk_set(target_os "raspberry")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "25")
			dk_set(target_os "raspberry")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "26")
			dk_set(target_os "raspberry")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "27")
			dk_set(target_os "raspberry")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "28")
			dk_set(target_os "win")
			dk_set(target_arch "arm32")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "29")
			dk_set(target_os "win")
			dk_set(target_arch "arm64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "30")
			dk_set(target_os "win")
			dk_set(target_arch "x86")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "31")
			dk_set(target_os "win")
			dk_set(target_arch "x86")
			dk_set(target_env "gcc")
		elseif("${input}" STREQUAL "32")
			dk_set(target_os "win")
			dk_set(target_arch "x86")
			dk_set(target_env "msvc")
		elseif("${input}" STREQUAL "33")
			dk_set(target_os "win")
			dk_set(target_arch "x86_64")
			dk_set(target_env "clang")
		elseif("${input}" STREQUAL "34")
			dk_set(target_os "win")
			dk_set(target_arch "x86_64")
			dk_set(target_env "gcc")
		elseif("${input}" STREQUAL "35")
			dk_set(target_os "win")
			dk_set(target_arch "x86_64")
			dk_set(target_env "msvc")
		elseif("${input}" STREQUAL "36")
			dk_set(target_os "win")
			dk_set(target_arch "x86_64")
			dk_set(target_env "ucrt")
		elseif("${input}" STREQUAL "37")
			dk_exit(0)
		else()
			dk_warning("invalid selection")
		endif()
		
		dk_assertVar(target_os)
		dk_toLower(${target_os} target_os)
		dk_toUpper(${target_os} TARGET_OS)
		dk_set(target_os ${target_os})
		dk_set(TARGET_OS ${TARGET_OS})
		dk_set(${target_os} 1)
		dk_set(${TARGET_OS} 1)
		dk_assertVar(TARGET_OS)
		dk_printVar(target_os)
		dk_printVar(TARGET_OS)
		dk_printVar(${target_os})
		dk_printVar(${TARGET_OS})

		dk_assertVar(target_arch)
		dk_toLower(${target_arch} target_arch)
		dk_toUpper(${target_arch} TARGET_ARCH)
		dk_set(target_arch ${target_arch})
		dk_set(TARGET_ARCH ${TARGET_ARCH})
		dk_set(${target_arch} 1)
		dk_set(${TARGET_ARCH} 1)
		dk_assertVar(TARGET_ARCH)
		dk_printVar(target_arch)
		dk_printVar(TARGET_ARCH)
		dk_printVar(${target_arch})
		dk_printVar(${TARGET_ARCH})
		
		if(target_env)
			dk_toLower(${target_env} target_env)
			dk_toUpper(${target_env} TARGET_ENV)
			dk_set(target_env ${target_env})
			dk_set(TARGET_ENV ${TARGET_ENV})
			dk_set(${target_env} 1)
			dk_set(${TARGET_ENV} 1)
			dk_printVar(target_env)
			dk_printVar(TARGET_ENV)
			dk_printVar(${target_env})
			dk_printVar(${TARGET_ENV})
		endif()
		
		if(target_env)
			dk_set(target_triple "${target_os}_${target_arch}_${target_env}")
			dk_set(TARGET_TRIPLE "${TARGET_OS}_${TARGET_ARCH}_${TARGET_ENV}")
		else()
			dk_set(target_triple "${target_os}_${target_arch}")
			dk_set(TARGET_TRIPLE "${TARGET_OS}_${TARGET_ARCH}")
		endif()
		dk_assertVar(target_triple)
		dk_assertVar(TARGET_TRIPLE)
		dk_set(target_triple ${target_triple})
		dk_set(TARGET_TRIPLE ${TARGET_TRIPLE})
		dk_set(${target_triple} 1)	
		dk_set(${TARGET_TRIPLE} 1)
		dk_printVar(target_triple)
		dk_printVar(TARGET_TRIPLE)
		dk_printVar(${target_triple})
		dk_printVar(${TARGET_TRIPLE})	
		
		### Set DEBUG_DIR and RELEASE_DIR variables
		if(IOS)
			dk_set(DEBUG_DIR Debug-iphoneos)
			dk_set(RELEASE_DIR Release-iphoneos)
		elseif(IOSSIM)
			dk_set(DEBUG_DIR Debug-iphonesimulator)
			dk_set(RELEASE_DIR Release-iphonesimulator)
		else()
			dk_set(DEBUG_DIR Debug)
			dk_set(RELEASE_DIR Release)
		endif()
		dk_assertVar(DEBUG_DIR)
		dk_assertVar(RELEASE_DIR)
		dk_printVar(DEBUG_DIR)
		dk_printVar(RELEASE_DIR)
	else()
		dk_error("dk_target_triple must run in CMAKE_SCRIPT_MODE_FILE")
	endif()
endfunction()






###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_target_triple_SET()
endfunction()
