#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT DEFINED DKINIT_cmake)
	if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
		cmake_policy(SET CMP0009 NEW)
		file(GLOB_RECURSE DK_cmake "/DK.cmake")
		list(GET DK_cmake 0 DK_cmake)
		get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK_cmake}" DIRECTORY)
		set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
	endif()
	include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
endif()
#########################################################################


#########################################################################
# dk_testApp(Plugin_name)
#
#	TODO
#
#	@Plugin_name	- TODO
#
function(dk_testApp Plugin_name)
	dk_debugFunc()
	
	dk_getImportPath(${Plugin_name} PLUGIN_Import_Path)
	if(NOT EXISTS "${PLUGIN_Import_Path}/test")
		dk_info("dk_testApp(): ${Plugin_name}_test app NOT FOUND")
		dk_return()
	endif()
	dk_info("building ${Plugin_name}_test app")
	dk_set(test_path "${PLUGIN_Import_Path}/test")
	
	# Create CmakeLists.txt file
	dk_delete("${test_path}/CMakeLists.txt")
	dk_fileAppend(${test_path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	dk_fileAppend(${test_path}/CMakeLists.txt "### ${Plugin_name} ###\n")
	dk_fileAppend(${test_path}/CMakeLists.txt "cmake_minimum_required(VERSION 3.10)\n")
	#dk_fileAppend(${test_path}/CMakeLists.txt "cmake_policy(SET CMP0054 NEW)\n")
	dk_fileAppend(${test_path}/CMakeLists.txt "include(${DKCMAKE_DIR}/DKFunctions.cmake)\n")
	dk_fileAppend(${test_path}/CMakeLists.txt "include(${DKCMAKE_DIR}/DKVariables.cmake)\n")
	dk_appendCmake("project(${Plugin_name}_test)\n")
	dk_appendCmake("include_directories(${DKCPP_PLUGINS_DIR})\n")
		
	# TODO		
	dk_addToPluginList(${Plugin_name})
endfunction()





###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
function(DKTEST)
	dk_debugFunc(0)
	
	dk_todo()
endfunction()