#dk_depend(openssl)
dk_depend(curl)
dk_depend(DKFile)
#dk_depend(DKThread)
IF(HAVE_DKDuktape)
	dk_depend(DKDuktape)
ENDIF()
IF(HAVE_DKCef)
	dk_depend(DKCef)
ENDIF()

dk_generateCmake(DKCurl)
