#dk_depend(openssl)
dk_depend(curl)
dk_depend(DKFile)
#dk_depend(DKThread)
if(HAVE_DKDuktape)
	dk_depend(DKDuktape)
endif()
if(HAVE_DKCef)
	dk_depend(DKCef)
endif()

dk_generateCmake(DKCurl)
