# This source file is part of digitalknob, the cross-platform C/C++/Javascript/Html/Css Solution
#
# For the latest information, see https://github.com/aquawicket/DigitalKnob
#
# Copyright(c) 2010 - 2023 Digitalknob Team, and contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files(the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions :
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
include_guard()

# Extra Documentation
# https://asitdhal.medium.com/cmake-functions-and-macros-22293041519f
# https://foonathan.net/2016/03/cmake-install/ 

dk_load(dk_sleep)
dk_load(dk_get_option)
dk_load(DK)
dk_load(dk_call)
dk_load(dk_listReplace)
dk_load(dk_getArgIdentifiers)
dk_load(dk_debugFunc)
dk_load(dk_updateLogInfo)
dk_load(DKASSERT)
dk_load(dk_error)
dk_load(dk_warning)
dk_load(dk_info)
dk_load(dk_debug)
dk_load(dk_verbose)
dk_load(dk_trace)
dk_load(dk_todo)
dk_load(dk_pad)
dk_load(dk_includes)
dk_load(dk_getParameter)
dk_load(dk_remove)
dk_load(dk_createOsMacros)
dk_load(dk_return)
dk_load(dk_printAllVariables)
dk_load(dk_set)
dk_load(dk_append)
dk_load(dk_unset)
dk_load(dk_exit)
dk_load(dk_isNumber)
dk_load(dk_wait)
dk_load(dk_dump)
dk_load(dk_watch)
dk_load(dk_watchCallback)
dk_load(dk_setXcodeProperty)
dk_load(dk_deleteCache)
dk_load(dk_deleteTempFiles)
dk_load(dk_deleteEmptyDirectories)
dk_load(dk_getEnv)
dk_load(dk_download)
dk_load(dk_extract)
dk_load(dk_compress_assets)
dk_load(dk_copy)
dk_load(dk_filesMatch)
dk_load(dk_rename)
dk_load(dk_upxCompress)
dk_load(dk_enable)
dk_load(dk_disable)
dk_load(dk_define)
dk_load(dk_undefine)
dk_load(dk_include)
dk_load(dk_linkDir)
dk_load(dk_getCurrentDirectory)
dk_load(dk_makeDirectory)
dk_load(dk_getDirectory)
dk_load(dk_getFilename)
dk_load(dk_getExtension)
dk_load(dk_dirIsEmpty)
dk_load(dk_refreshIcons)
dk_load(dk_patch)
dk_load(dk_install)
dk_load(dk_validatePath)
dk_load(dk_getShortPath)
dk_load(dk_print_prefix_vars)
dk_load(dk_get_option_value)
dk_load(dk_get_option_values)
dk_load(dk_executeProcess)
dk_load(dk_setEnv)
dk_load(dk_setPath)
dk_load(dk_bash_env)
dk_load(dk_msys2)
dk_load(dk_msys2_bash)
dk_load(dk_mergeFlags)
dk_load(dk_command)
dk_load(dk_queueCommand)
dk_load(dk_visualStudioDebug)
dk_load(dk_visualStudioRelease)
dk_load(dk_visualStudioRelease)
dk_load(dk_xcodeDebug)
dk_load(dk_xcodeRelease)
dk_load(dk_xcode)
dk_load(dk_ndkDebug)
dk_load(dk_ndkRelease)
dk_load(dk_ndk)
dk_load(dk_make)
dk_load(dk_build)
dk_load(dk_lib)
dk_load(dk_libDebug)
dk_load(dk_libRelease)
dk_load(dk_generateCmake)
dk_load(dk_dll)
dk_load(dk_executable)
dk_load(dk_testApp)
dk_load(dk_addToPluginList)
dk_load(dk_appendCmake)
dk_load(dk_assets)
dk_load(dk_getPathToPlugin)
dk_load(dk_depend)
dk_load(dk_undepend)
dk_load(dk_runDepends)
dk_load(dk_require)
dk_load(dk_dependAll)
dk_load(dk_fileReplace)
dk_load(dk_updateAndroidName)
dk_load(dk_updateInfoPlist)
dk_load(dk_buildLog)
dk_load(dk_addSource)
dk_load(dk_removeSource)
dk_load(dk_wrapString)
dk_load(dk_bin2h)
dk_load(dk_getCmakeCommandLine)
dk_load(dk_printSettings)
dk_load(dk_addTarget)
dk_load(dk_removeTarget)
dk_load(dk_createSmartObject)
dk_load(dk_log)
dk_load(dk_removeSubstring)
dk_load(dk_findTarget)
dk_load(dk_setReadOnly)
dk_load(dk_readOnlyCallback)
dk_load(dk_prependFile)
dk_load(dk_addRegistryKey)
dk_load(dk_importGit)
dk_load(dk_importDownload)
dk_load(dk_import)
dk_load(dk_DownloadAll3rdParty)
dk_load(dk_getFileType)
dk_load(dk_getAppDirectory)
dk_load(dk_toLower)
dk_load(dk_toUpper)
dk_load(dk_removeExtension)
dk_load(dk_getAppName)
dk_load(dk_createPlugin)
dk_load(dk_getGitBranchName)	
dk_load(dk_printArgData)
dk_load(dk_printUrlData)
dk_load(dk_killProcess)
dk_load(dk_clearScreen)
dk_load(dk_findLibrary)
dk_load(dk_findFiles)
dk_load(dk_resizeImage)
dk_load(dk_createWindowsIcon)
dk_load(dk_createFavIcon)
dk_load(dk_pathContains)
dk_load(dk_addFirewallAllow)
dk_load(dk_getUnixPath)
dk_load(dk_applyPatch)
dk_load(dk_get_arg_count)
dk_load(dk_is_list)
