#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT DEFINED DKINIT_cmake)
	if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
		cmake_policy(SET CMP0009 NEW)
		file(GLOB_RECURSE DK_cmake "/DK.cmake")
		list(GET DK_cmake 0 DK_cmake)
		get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK_cmake}" DIRECTORY)
		set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
	endif()
	include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
endif()
#########################################################################


function(generateAndroidMK)
	if(ANDROID_LIBMK)
		dk_set(PLUGIN_Tuple_Dir ${${CURRENT_PLUGIN}}/${Target_Tuple})
		dk_mkdir(${PLUGIN_Tuple_Dir})
		if(Debug)
			dk_echo("Creating Debug Application.mk file for ${CURRENT_PLUGIN}....")
			dk_set(PLUGIN_Type ${${CURRENT_PLUGIN}}/${Target_Tuple}/Debug)
			dk_mkdir(${PLUGIN_Type})
			dk_mkdir(${PLUGIN_Type}/jni)
			
			dk_set(APPMK_FILE "APP_PLATFORM := android-15 \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_ABI      := armeabi-v7a \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_STL      := gnustl_static \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_OPTIM    := debug \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_CPPFLAGS := -fexceptions -frtti\n")
			dk_fileWrite(${PLUGIN_Type}/jni/Application.mk ${APPMK_FILE})
			
			dk_echo("Creating Debug Android.mk file for ${CURRENT_PLUGIN}....")
			foreach(_define ${DKDEFINES_LIST})
		        dk_set(ANDROID_LIBMK "${ANDROID_LIBMK} "LOCAL_LDFLAGS += ${_define}\n")
	        endforeach()
			dk_set(ANDROID_LIBMK ${ANDROID_LIBMK} "LOCAL_C_INCLUDES += ${DKCPP_PLUGINS_DIR}\n")
			foreach(_include ${DKINCLUDES_LIST})
				dk_set(ANDROID_LIBMK "${ANDROID_LIBMK} "LOCAL_C_INCLUDES += ${_include}\n")
			endforeach()
			dk_set(ANDROID_LIBMK ${ANDROID_LIBMK} "include $(BUILD_STATIC_LIBRARY) \n\n")
			dk_fileWrite(${PLUGIN_Type}/jni/Android.mk ${ANDROID_LIBMK})
			if(Windows_Host)
				dk_exec(${android-ndk}/ndk-build.cmd NDK_DEBUG=1 WORKING_DIRECTORY "${PLUGIN_Type}")
				#execute_process(COMMAND ${ANDROID_NDK}/ndk-build.cmd NDK_DEBUG=1 WORKING_DIRECTORY ${PLUGIN_Type})
			endif()
			if(UNIX_HOST)
				dk_exec(${android-ndk}/ndk-build NDK_DEBUG=1 WORKING_DIRECTORY "${PLUGIN_Type}")
				#execute_process(COMMAND ${android-ndk}/ndk-build NDK_DEBUG=1 WORKING_DIRECTORY ${PLUGIN_Type})
			endif()
		endif()
		if(Release)
			dk_echo("Creating Release Application.mk file for ${CURRENT_PLUGIN}....")
			dk_set(PLUGIN_Type ${${CURRENT_PLUGIN}}/${Target_Tuple}/Release)
			dk_mkdir(${PLUGIN_Type})
			dk_mkdir(${PLUGIN_Type}/jni)
			
			dk_set(APPMK_FILE "APP_PLATFORM := android-15 \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_ABI      := armeabi-v7a \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_STL      := gnustl_static \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_OPTIM    := release \n")
			dk_set(APPMK_FILE ${APPMK_FILE} "APP_CPPFLAGS := -fexceptions -frtti\n")
			dk_fileWrite(${PLUGIN_Type}/jni/Application.mk ${APPMK_FILE})
			
			dk_echo("Creating Release Android.mk file for ${CURRENT_PLUGIN}....")
            foreach(_define ${DKDEFINES_LIST})
		        dk_set(ANDROID_LIBMK "${ANDROID_LIBMK} "LOCAL_LDFLAGS += ${_define}\n")
	        endforeach()
			dk_set(ANDROID_LIBMK ${ANDROID_LIBMK} "LOCAL_C_INCLUDES += ${DKCPP_PLUGINS_DIR}\n")
			foreach(_include ${DKINCLUDES_LIST})
				dk_set(ANDROID_LIBMK "${ANDROID_LIBMK} "LOCAL_C_INCLUDES += ${_include}\n")
			endforeach()
			dk_set(ANDROID_LIBMK ${ANDROID_LIBMK} "include $(BUILD_STATIC_LIBRARY) \n\n")
			dk_fileWrite(${PLUGIN_Type}/jni/Android.mk ${ANDROID_LIBMK})
			if(Windows_Host)
				dk_exec(${android-ndk}/ndk-build.cmd NDK_DEBUG=0 WORKING_DIRECTORY ${PLUGIN_Type})
				#execute_process(COMMAND ${android-ndk}/ndk-build.cmd NDK_DEBUG=0 WORKING_DIRECTORY ${PLUGIN_Type})
			endif()
			if(UNIX_HOST)
				dk_exec(${android-ndk}/ndk-build NDK_DEBUG=0 WORKING_DIRECTORY ${PLUGIN_Type})
				#execute_process(COMMAND ${android-ndk}/ndk-build NDK_DEBUG=0 WORKING_DIRECTORY ${PLUGIN_Type})
			endif()
		endif()
	endif()
endfunction()
