### Setup missing systems for cmake ###

execute_process(COMMAND uname -a OUTPUT_VARIABLE uname)
if(uname MATCHES "^MINGW32")
	set(MINGW32 1)
    set(MSYS2 1)
endif()
if(uname MATCHES "^MINGW64")
	set(MINGW64 1)
    set(MSYS2 1)
endif()
#if(uname MATCHES "^CLANG32")
#	set(CLANG32 1)
#   set(MSYS2 1)
#endif()
#if(uname MATCHES "^CLANG64")
#	set(CLANG64 1)
#    set(MSYS2 1)
#endif()

get_cmake_property(vars VARIABLES)
list (SORT vars)
foreach (var ${vars})
	message(STATUS "${var}: ${${var}}")
endforeach()

