###### DKBuilder ######

#${ENABLE_dk_debugFunc} = 1

###### INIT ######
if(!${DKSCRIPT_PATH})							{ ${DKSCRIPT_PATH} = $Script:MyInvocation.MyCommand.Path }
Write-Host "DKSCRIPT_PATH = ${DKSCRIPT_PATH}"

if(!${DKHOME})									{ ${DKHOME} = "${env:USERPROFILE}" }
Write-Host "DKHOME = ${DKHOME}"
if(!${DKHTTP})									{ ${DKHTTP} = "https://raw.githubusercontent.com/aquawicket" }
Write-Host "DKHTTP = ${DKHTTP}"

if(!${DIGITALKNOB})								{ ${DIGITALKNOB} = "DigitalKnob" }
Write-Host "DIGITALKNOB = ${DIGITALKNOB}"
if(!${DIGITALKNOB_DIR})							{ ${DIGITALKNOB_DIR} = "${DKHOME}/${DIGITALKNOB}" }
Write-Host "DIGITALKNOB_DIR = ${DIGITALKNOB_DIR}"
if(!${DKHTTP_DIGITALKNOB_DIR})					{ ${DKHTTP_DIGITALKNOB_DIR} = "${DKHTTP}/${DIGITALKNOB}" }
Write-Host "DKHTTP_DIGITALKNOB_DIR = ${DKHTTP_DIGITALKNOB_DIR}"
if(!(Test-Path ${DIGITALKNOB_DIR}))				{ New-Item -Path ${DIGITALKNOB_DIR} -ItemType Directory }
Write-Host "DIGITALKNOB_DIR = ${DIGITALKNOB_DIR}"

if(!${DKBRANCH})								{ ${DKBRANCH} = "Development" }
Write-Host "DKBRANCH = ${DKBRANCH}"
if(!${DKBRANCH_DIR})							{ ${DKBRANCH_DIR} = "${DIGITALKNOB_DIR}/${DKBRANCH}" }
Write-Host "DKBRANCH_DIR = ${DKBRANCH_DIR}"
if(!${DKHTTP_DKBRANCH_DIR})						{ ${DKHTTP_DKBRANCH_DIR} = "${DKHTTP_DIGITALKNOB_DIR}/${DKBRANCH}" }
Write-Host "DKHTTP_DKBRANCH_DIR = ${DKHTTP_DKBRANCH_DIR}"
if(!(Test-Path ${DKBRANCH_DIR}))				{ New-Item -Path ${DKBRANCH_DIR} -ItemType Directory }

if(!${DKPOWERSHELL})							{ ${DKPOWERSHELL} = "DKPowershell" }
Write-Host "DKPOWERSHELL = ${DKPOWERSHELL}"
if(!${DKPOWERSHELL_DIR})						{ ${DKPOWERSHELL_DIR} = "${DKBRANCH_DIR}/${DKPOWERSHELL}" }
Write-Host "DKPOWERSHELL_DIR = ${DKPOWERSHELL_DIR}"
if(!${DKHTTP_DKPOWERSHELL_DIR})					{ ${DKHTTP_DKPOWERSHELL_DIR} = "${DKHTTP_DKBRANCH_DIR}/${DKPOWERSHELL}" }
Write-Host "DKHTTP_DKPOWERSHELL_DIR = ${DKHTTP_DKPOWERSHELL_DIR}"
if(!(Test-Path ${DKPOWERSHELL_DIR}))			{ New-Item -Path ${DKPOWERSHELL_DIR} -ItemType Directory }

if(!${DKPOWERSHELL_FUNCTIONS})					{ ${DKPOWERSHELL_FUNCTIONS} = "functions" }
Write-Host "DKPOWERSHELL_FUNCTIONS = ${DKPOWERSHELL_FUNCTIONS}"
if(!${DKPOWERSHELL_FUNCTIONS_DIR})				{ ${DKPOWERSHELL_FUNCTIONS_DIR} = "${DKPOWERSHELL_DIR}/${DKPOWERSHELL_FUNCTIONS}" }
Write-Host "DKPOWERSHELL_FUNCTIONS_DIR = ${DKPOWERSHELL_FUNCTIONS_DIR}"
if(!${DKPOWERSHELL_FUNCTIONS_DIR_})				{ ${DKPOWERSHELL_FUNCTIONS_DIR_} = "${DKPOWERSHELL_FUNCTIONS_DIR}/" }
Write-Host "DKPOWERSHELL_FUNCTIONS_DIR_ = ${DKPOWERSHELL_FUNCTIONS_DIR_}"
if(!${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR})		{ ${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR} = "${DKHTTP_DKPOWERSHELL_DIR}/${DKPOWERSHELL_FUNCTIONS}" }
Write-Host "DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR = ${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR}"
if(!${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR_})		{ ${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR_} = "${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR}/" }
Write-Host "DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR_ = ${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR_}"
if(!(Test-Path ${DKPOWERSHELL_FUNCTIONS_DIR}))	{ New-Item -Path ${DKPOWERSHELL_FUNCTIONS_DIR} -ItemType Directory }


if(!(Test-Path ${DKPOWERSHELL_FUNCTIONS_DIR_}DK.ps1)){ 
	Invoke-WebRequest -URI "${DKHTTP_DKPOWERSHELL_FUNCTIONS_DIR_}DK.ps1" -OutFile ${DKPOWERSHELL_FUNCTIONS_DIR_}DK.ps1 
}
. ${DKPOWERSHELL_FUNCTIONS_DIR_}DK.ps1
if(${DKLOADED}){ exit } else{ ${global:DKLOADED}=1 }	# ignore the fork process that will return from DK.ps1 above






###### Load Main Program ######
dk_call dk_buildMain
Read-Host -Prompt "Press Enter to exit"
