message(STATUS "####################################################################")
message(STATUS "################ android_arm32_toolchain.cmake #####################")
message(STATUS "####################################################################")

dk_validate(ANDROID_NDK					"dk_depend(android-ndk)")
dk_set(ANDROID_ABI						armeabi-v7a)
dk_set(ANDROID_CPP_FEATURES				"rtti exceptions")
dk_set(ANDROID_STL						c++_static)
dk_set(ANDROID_STL_FORCE_FEATURES		1)
dk_set(ANDROID_TOOLCHAIN				clang)



dk_set(CMAKE_TOOLCHAIN_FILE				"${ANDROID_TOOLCHAIN_FILE}")
dk_set(CMAKE_GENERATOR					"Unix Makefiles")
if(WIN_HOST)
	#dk_validate(MSYS2_MAKE_PROGRAM		"dk_depend(msys2)")
	#dk_set(CMAKE_MAKE_PROGRAM			"${MSYS2_MAKE_PROGRAM}")
	dk_set(CMAKE_MAKE_PROGRAM			"${ANDROID_MAKE_PROGRAM}")
else()
	dk_set(CMAKE_MAKE_PROGRAM			"make")
endif()
dk_set(CMAKE_C_COMPILER					"${ANDROID_C_COMPILER}")
dk_set(CMAKE_CXX_COMPILER				"${ANDROID_CXX_COMPILER}")
dk_set(CMAKE_ANDROID_STL_TYPE			${ANDROID_STL})
dk_append(CMAKE_C_FLAGS					-DANDROID -DANDROID_ARM64 -std=c17)
dk_append(CMAKE_CXX_FLAGS				-DANDROID -DANDROID_ARM64 -std=c++1z)
