message(STATUS "####################################################################")
message(STATUS "################ Android_Arm64_Clang_Toolchain.cmake ###############")
message(STATUS "####################################################################")
# https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md


dk_validate(android-ndk					"dk_depend(android-ndk)")
dk_validate(Android_Host_Tag			"dk_depend(android-ndk)")
dk_set(ANDROID_ABI						arm64-v8a)
dk_set(ANDROID_CPP_FEATURES				"rtti exceptions")
dk_set(ANDROID_STL						c++_static)
dk_set(ANDROID_STL_FORCE_FEATURES		1)
dk_set(ANDROID_TOOLCHAIN				clang)

dk_set(CMAKE_TOOLCHAIN_FILE				"${android-ndk}/build/cmake/android.toolchain.cmake")
dk_set(CMAKE_GENERATOR					"Unix Makefiles")
dk_assertVar(Android_Host_Tag)
if(Windows_Host)
	#dk_validate(msys2_MAKE_PROGRAM		"dk_depend(msys2)")
	#dk_set(CMAKE_MAKE_PROGRAM			"${msys2_bin}/make.exe")
	dk_set(CMAKE_MAKE_PROGRAM			"${android-ndk}/prebuilt/${Android_Host_Tag}/bin/make${exe}")
else()
	dk_set(CMAKE_MAKE_PROGRAM			"make")
endif()
dk_set(CMAKE_C_COMPILER					"${android-ndk}/toolchains/llvm/prebuilt/${Android_Host_Tag}/bin/clang${exe}")
dk_set(CMAKE_CXX_COMPILER				"${android-ndk}/toolchains/llvm/prebuilt/${Android_Host_Tag}/bin/clang++${exe}")
dk_set(CMAKE_ANDROID_STL_TYPE			${ANDROID_STL})
dk_append(CMAKE_C_FLAGS					-DANDROID -DANDROID_ARM64 -std=c17)
dk_append(CMAKE_CXX_FLAGS				-DANDROID -DANDROID_ARM64 -std=c++1z)
