dk_echo("#########################################################################")
dk_echo("################# Emscripten_X86_Clang_toolchain.cmake #####################")
dk_echo("#########################################################################")

if(Android_Host)
	dk_pause()
	dk_echo("paused in Emscripten toolchain because Android_Host")
	dk_exit()
endif()

dk_depend(emsdk)
dk_assertPath			(${emsdk})
dk_set					(CMAKE_GENERATOR "Unix Makefiles")

#if(Windows_Host)
	#dk_validate(msys2 "dk_depend(msys2)")
	#dk_installPackage	(make)
	#dk_findProgram		(CMAKE_MAKE_PROGRAM mingw32-make.exe "${msys2}/usr/bin")
	#dk_set				(CMAKE_MAKE_PROGRAM	"${emsdk}/upstream/emscripten/emmake${bat}")
	#dk_assertPath		(CMAKE_MAKE_PROGRAM)
#elseif(Linux_Host)
	#dk_set				(CMAKE_MAKE_PROGRAM	make)
#else()
	#dk_set				(CMAKE_MAKE_PROGRAM	"${emsdk}/upstream/emscripten/emmake${bat}")
#endif()

dk_set(CMAKE_TOOLCHAIN_FILE 				"${emsdk}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
dk_set(CMAKE_C_COMPILER						"${emsdk}/upstream/emscripten/emcc${bat}")
dk_set(CMAKE_CXX_COMPILER					"${emsdk}/upstream/emscripten/em++${bat}")
dk_append(CMAKE_C_FLAGS						-DEMSDK -std=gnu11)
dk_append(CMAKE_CXX_FLAGS					-DEMSDK -std=gnu++17)
dk_set(CMAKE_C_COMPILER_WORKS				1)
dk_set(CMAKE_CXX_COMPILER_WORKS				1)
#dk_set(CMAKE_EXECUTABLE_SUFFIX 			".html")
#dk_append(DKCMAKE_FLAGS					-DEMSDK=1)
#dk_append(CMAKE_EXE_LINKER_FLAGS			-static) # -s)
