message(STATUS "##############################################################")
message(STATUS "################# emscripten_toolchain.cmake #################")
message(STATUS "##############################################################")

dk_depend(emsdk)
dk_depend(make)
dk_set(bat ".bat")


if(WIN_HOST)
	dk_depend(msys2)
	#dk_installPackage(make)
	dk_findProgram(CMAKE_MAKE_PROGRAM make "${MSYS2_DIR}/usr/bin")
else()
	dk_findProgram(CMAKE_MAKE_PROGRAM make)
endif()
dk_set(CMAKE_TOOLCHAIN_FILE 		"${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
dk_set(CMAKE_C_COMPILER				"${EMSDK}/upstream/emscripten/emcc${bat}")
dk_set(CMAKE_CXX_COMPILER			"${EMSDK}/upstream/emscripten/em++${bat}")
dk_append(CMAKE_C_FLAGS				-DEMSDK -std=gnu11)
dk_append(CMAKE_CXX_FLAGS			-DEMSDK -std=gnu++17)
dk_set(CMAKE_C_COMPILER_WORKS		1)
dk_set(CMAKE_CXX_COMPILER_WORKS		1)
dk_append(DKCMAKE_FLAGS				-DEMSDK=1)
#dk_append(CMAKE_EXE_LINKER_FLAGS	-static) # -s)