message("############################################################################")
message("################# emscripten_x86_clang_toolchain.cmake #####################")
message("############################################################################")

if(Android_Host)
	dk_pause()
	message("paused in emscripten toolchain because Android_Host")
	dk_exit()
endif()

dk_validate(EMSDK							"dk_depend(emsdk)")

dk_set(CMAKE_GENERATOR						"Unix Makefiles")
if(Win_Host)
	dk_validate(MSYS2 						"dk_depend(msys2)")
	dk_installPackage(						make)
	dk_findProgram(CMAKE_MAKE_PROGRAM make 	"${MSYS2}/usr/bin")
elseif(Linux_Host)
	dk_set(CMAKE_MAKE_PROGRAM				make)
else()
	dk_set(CMAKE_MAKE_PROGRAM				"${EMSDK}/upstream/emscripten/emmake${bat}")
endif()
dk_set(CMAKE_TOOLCHAIN_FILE 				"${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake")
dk_set(CMAKE_C_COMPILER						"${EMSDK}/upstream/emscripten/emcc${bat}")
dk_set(CMAKE_CXX_COMPILER					"${EMSDK}/upstream/emscripten/em++${bat}")
dk_append(CMAKE_C_FLAGS						-DEMSDK -std=gnu11)
dk_append(CMAKE_CXX_FLAGS					-DEMSDK -std=gnu++17)
dk_set(CMAKE_C_COMPILER_WORKS				1)
dk_set(CMAKE_CXX_COMPILER_WORKS				1)
dk_append(DKCMAKE_FLAGS						-DEMSDK=1)
#dk_append(CMAKE_EXE_LINKER_FLAGS			-static) # -s)
