dk_enable(DKCef)

dk_depend(DK)
dk_depend(DKArchive)
dk_depend(DKAssets)
## dk_depend(DKDebug)
dk_depend(DKDuktape)
dk_depend(DKDuktapeDom)
dk_depend(DKCef)
dk_depend(DKCefChild)
dk_depend(DKFile)
dk_depend(DKGui)
