#include "dk_color.hpp"
#include "dk_echo.hpp"

//###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
#ifndef DKMAIN
#define DKMAIN 1
int main(int argc, char** argv) {
    dk_echo("\n");

    dk_echo("0    clr          "+ clr                 +"      clr            "+clr+"\n");
    dk_echo("1    bold         "+ bold                +"      bold           "+clr+"\n");
    dk_echo("2    dim          "+ dim                 +"      dim            "+clr+"\n");
    dk_echo("3    italic       "+ italic              +"      italic         "+clr+"\n");
    dk_echo("4    underline    "+ underline           +"      underline      "+clr+"\n");
    dk_echo("5    blink        "+ blink               +"      blink          "+clr+"\n");
    dk_echo("6    fblink       "+ fblink              +"      fblink         "+clr+"\n");
    dk_echo("7    negative     "+ negative            +"      negative       "+clr+"\n");
    dk_echo("8    invisible    "+ invisible           +"      invisible      "+clr+"\n");
    dk_echo("9    strike       "+ strike              +"      strike         "+clr+"\n");
    dk_echo("10   ANSI10       "+ ANSI10              +"      UNKNOWN        "+clr+"\n");
    dk_echo("11   ANSI11       "+ ANSI11              +"      UNKNOWN        "+clr+"\n");
    dk_echo("12   ANSI12       "+ ANSI12              +"      UNKNOWN        "+clr+"\n");
    dk_echo("13   ANSI13       "+ ANSI13              +"      UNKNOWN        "+clr+"\n");
    dk_echo("14   ANSI14       "+ ANSI14              +"      UNKNOWN        "+clr+"\n");
    dk_echo("15   ANSI15       "+ ANSI15              +"      UNKNOWN        "+clr+"\n");
    dk_echo("16   ANSI16       "+ ANSI16              +"      UNKNOWN        "+clr+"\n");
    dk_echo("17   ANSI17       "+ ANSI17              +"      UNKNOWN        "+clr+"\n");
    dk_echo("18   ANSI18       "+ ANSI18              +"      UNKNOWN        "+clr+"\n");
    dk_echo("19   ANSI19       "+ ANSI19              +"      UNKNOWN        "+clr+"\n");
    dk_echo("20   ANSI20       "+ ANSI20              +"      UNKNOWN        "+clr+"\n");
    dk_echo("21   ANSI21       "+ ANSI21              +"      UNKNOWN        "+clr+"\n");
    dk_echo("22   nobold       "+ nobold              +"      nobold         "+clr+"\n");
    dk_echo("23   noitalic     "+ noitalic            +"      noitalic       "+clr+"\n");
    dk_echo("24   nounderline  "+ nounderline         +"      nounderline    "+clr+"\n");
    dk_echo("25   noblink      "+ noblink             +"      noblink        "+clr+"\n");
    dk_echo("26   ANSI26       "+ ANSI26              +"      UNKNOWN        "+clr+"\n");
    dk_echo("27   nonegative   "+ nonegative          +"      nonegative     "+clr+"\n");
    dk_echo("28   visible      "+ visible             +"      visible        "+clr+"\n");
    dk_echo("29   nostrike     "+ nostrike            +"      nostrike       "+clr+"\n");
    dk_echo("30   black        "+ black + bg_lblack   +"      black          "+clr+"\n");
    dk_echo("31   red          "+ red                 +"      red            "+clr+"\n");
    dk_echo("32   green        "+ green               +"      green          "+clr+"\n");
    dk_echo("33   yellow       "+ yellow              +"      yellow         "+clr+"\n");
    dk_echo("34   blue         "+ blue                +"      blue           "+clr+"\n");
    dk_echo("35   magenta      "+ magenta             +"      magenta        "+clr+"\n");
    dk_echo("36   cyan         "+ cyan                +"      cyan           "+clr+"\n");
    dk_echo("37   white        "+ white               +"      white          "+clr+"\n");
	dk_echo("38   RGB          "+ RGB+"255;0;0m        R"+RGB+"0;255;0mG"+RGB+"0;0;255mB"+clr+"\n");
    dk_echo("39   default_     "+ default_            +"      default_       "+clr+"\n");
    dk_echo("40   bg_black     "+ bg_black   + white  +"      bg_black       "+clr+"\n");
    dk_echo("41   bg_red       "+ bg_red     + black  +"      bg_red         "+clr+"\n");
    dk_echo("42   bg_green     "+ bg_green   + black  +"      bg_green       "+clr+"\n");
    dk_echo("43   bg_yellow    "+ bg_yellow  + black  +"      bg_yellow      "+clr+"\n");
    dk_echo("44   bg_blue      "+ bg_blue    + black  +"      bg_blue        "+clr+"\n");
    dk_echo("45   bg_magenta   "+ bg_magenta + black  +"      bg_magenta     "+clr+"\n");
    dk_echo("46   bg_cyan      "+ bg_cyan    + black  +"      bg_cyan        "+clr+"\n");
    dk_echo("47   bg_white     "+ bg_white   + black  +"      bg_white       "+clr+"\n");
	dk_echo("48   bg_RGB               "+ bg_RGB+"255;0;0mR"+bg_RGB+"0;255;0mG"+bg_RGB+"0;0;255mB"+clr+"\n");
    dk_echo("49   bg_default   "+ bg_default + white  +"      bg_default     "+clr+"\n");
    dk_echo("50   ANSI50       "+ ANSI50              +"      UNKNOWN        "+clr+"\n");
    dk_echo("51   ANSI51       "+ ANSI51              +"      UNKNOWN        "+clr+"\n");
    dk_echo("52   ANSI52       "+ ANSI52              +"      UNKNOWN        "+clr+"\n");
    dk_echo("53   ANSI53       "+ ANSI53              +"      UNKNOWN        "+clr+"\n");
    dk_echo("54   ANSI54       "+ ANSI54              +"      UNKNOWN        "+clr+"\n");
    dk_echo("55   ANSI55       "+ ANSI55              +"      UNKNOWN        "+clr+"\n");
    dk_echo("56   ANSI56       "+ ANSI56              +"      UNKNOWN        "+clr+"\n");
    dk_echo("57   ANSI57       "+ ANSI57              +"      UNKNOWN        "+clr+"\n");
    dk_echo("58   ANSI58       "+ ANSI58              +"      UNKNOWN        "+clr+"\n");
    dk_echo("59   ANSI59       "+ ANSI59              +"      UNKNOWN        "+clr+"\n");
    dk_echo("60   ANSI60       "+ ANSI60              +"      UNKNOWN        "+clr+"\n");
    dk_echo("61   ANSI61       "+ ANSI61              +"      UNKNOWN        "+clr+"\n");
    dk_echo("62   ANSI62       "+ ANSI62              +"      UNKNOWN        "+clr+"\n");
    dk_echo("63   ANSI63       "+ ANSI63              +"      UNKNOWN        "+clr+"\n");
    dk_echo("64   ANSI64       "+ ANSI64              +"      UNKNOWN        "+clr+"\n");
    dk_echo("65   ANSI65       "+ ANSI65              +"      UNKNOWN        "+clr+"\n");
    dk_echo("66   ANSI66       "+ ANSI66              +"      UNKNOWN        "+clr+"\n");
    dk_echo("67   ANSI67       "+ ANSI67              +"      UNKNOWN        "+clr+"\n");
    dk_echo("68   ANSI68       "+ ANSI68              +"      UNKNOWN        "+clr+"\n");
    dk_echo("69   ANSI69       "+ ANSI69              +"      UNKNOWN        "+clr+"\n");
    dk_echo("70   ANSI70       "+ ANSI70              +"      UNKNOWN        "+clr+"\n");
    dk_echo("71   ANSI71       "+ ANSI71              +"      UNKNOWN        "+clr+"\n");
    dk_echo("72   ANSI72       "+ ANSI72              +"      UNKNOWN        "+clr+"\n");
    dk_echo("73   ANSI73       "+ ANSI73              +"      UNKNOWN        "+clr+"\n");
    dk_echo("74   ANSI74       "+ ANSI74              +"      UNKNOWN        "+clr+"\n");
    dk_echo("75   ANSI75       "+ ANSI75              +"      UNKNOWN        "+clr+"\n");
    dk_echo("76   ANSI76       "+ ANSI76              +"      UNKNOWN        "+clr+"\n");
    dk_echo("77   ANSI77       "+ ANSI77              +"      UNKNOWN        "+clr+"\n");
    dk_echo("78   ANSI78       "+ ANSI78              +"      UNKNOWN        "+clr+"\n");
    dk_echo("79   ANSI79       "+ ANSI79              +"      UNKNOWN        "+clr+"\n");
    dk_echo("80   ANSI80       "+ ANSI80              +"      UNKNOWN        "+clr+"\n");
    dk_echo("81   ANSI81       "+ ANSI81              +"      UNKNOWN        "+clr+"\n");
    dk_echo("82   ANSI82       "+ ANSI82              +"      UNKNOWN        "+clr+"\n");
    dk_echo("83   ANSI83       "+ ANSI83              +"      UNKNOWN        "+clr+"\n");
    dk_echo("84   ANSI84       "+ ANSI84              +"      UNKNOWN        "+clr+"\n");
    dk_echo("85   ANSI85       "+ ANSI85              +"      UNKNOWN        "+clr+"\n");
    dk_echo("86   ANSI86       "+ ANSI86              +"      UNKNOWN        "+clr+"\n");
    dk_echo("87   ANSI87       "+ ANSI87              +"      UNKNOWN        "+clr+"\n");
    dk_echo("88   ANSI88       "+ ANSI88              +"      UNKNOWN        "+clr+"\n");
    dk_echo("89   ANSI89       "+ ANSI89              +"      UNKNOWN        "+clr+"\n");
    dk_echo("90   lblack       "+ lblack              +"      lblack         "+clr+"\n");
    dk_echo("91   lred         "+ lred                +"      lred           "+clr+"\n");
    dk_echo("92   lgreen       "+ lgreen              +"      lgreen         "+clr+"\n");
    dk_echo("93   lyellow      "+ lyellow             +"      lyellow        "+clr+"\n");
    dk_echo("94   lblue        "+ lblue               +"      lblue          "+clr+"\n");
    dk_echo("95   lmagenta     "+ lmagenta            +"      lmagenta       "+clr+"\n");
    dk_echo("96   lcyan        "+ lcyan               +"      lcyan          "+clr+"\n");
    dk_echo("97   lwhite       "+ lwhite              +"      lwhite         "+clr+"\n");
    dk_echo("98   ANSI98       "+ ANSI98              +"      UNKNOWN        "+clr+"\n");
    dk_echo("99   ANSI99       "+ ANSI99              +"      UNKNOWN        "+clr+"\n");
    dk_echo("100  bg_lblack    "+ bg_lblack   + black +"      bg_lblack      "+clr+"\n");
    dk_echo("101  bg_lred      "+ bg_lred     + black +"      bg_lred        "+clr+"\n");
    dk_echo("102  bg_lgreen    "+ bg_lgreen   + black +"      bg_lgreen      "+clr+"\n");
    dk_echo("103  bg_lyellow   "+ bg_lyellow  + black +"      bg_lyellow     "+clr+"\n");
    dk_echo("104  bg_lblue     "+ bg_lblue    + black +"      bg_lblue       "+clr+"\n");
    dk_echo("105  bg_lmagenta  "+ bg_lmagenta + black +"      bg_lmagenta    "+clr+"\n");
    dk_echo("106  bg_lcyan     "+ bg_lcyan    + black +"      bg_lcyan       "+clr+"\n");
    dk_echo("107  bg_lwhite    "+ bg_lwhite   + black +"      bg_lwhite      "+clr+"\n");
    dk_echo("108  ANSI108      "+ ANSI108             +"      UNKNOWN        "+clr+"\n");
    dk_echo("109  ANSI109      "+ ANSI109             +"      UNKNOWN        "+clr+"\n");
    dk_echo("110  ANSI110      "+ ANSI110             +"      UNKNOWN        "+clr+"\n");
    dk_echo("111  ANSI111      "+ ANSI111             +"      UNKNOWN        "+clr+"\n");
    dk_echo("112  ANSI112      "+ ANSI112             +"      UNKNOWN        "+clr+"\n");
    dk_echo("113  ANSI113      "+ ANSI113             +"      UNKNOWN        "+clr+"\n");
    dk_echo("114  ANSI114      "+ ANSI114             +"      UNKNOWN        "+clr+"\n");
    dk_echo("115  ANSI115      "+ ANSI115             +"      UNKNOWN        "+clr+"\n");
    dk_echo("116  ANSI116      "+ ANSI116             +"      UNKNOWN        "+clr+"\n");
    dk_echo("117  ANSI117      "+ ANSI117             +"      UNKNOWN        "+clr+"\n");
    dk_echo("118  ANSI118      "+ ANSI118             +"      UNKNOWN        "+clr+"\n");
    dk_echo("119  ANSI119      "+ ANSI119             +"      UNKNOWN        "+clr+"\n");
    dk_echo("120  ANSI120      "+ ANSI120             +"      UNKNOWN        "+clr+"\n");
    dk_echo("121  ANSI121      "+ ANSI121             +"      UNKNOWN        "+clr+"\n");
    dk_echo("122  ANSI122      "+ ANSI122             +"      UNKNOWN        "+clr+"\n");
    dk_echo("123  ANSI123      "+ ANSI123             +"      UNKNOWN        "+clr+"\n");
    dk_echo("124  ANSI124      "+ ANSI124             +"      UNKNOWN        "+clr+"\n");

    dk_echo(RGB+"255;10;10m    RGB test (255;0;10)    "+clr+"\n");
    dk_echo(RGB+"10;255;10m    RGB test (0;255;10)    "+clr+"\n");
    dk_echo(RGB+"0;0;255m    RGB test (0;0;255)     "+clr+"\n");
    dk_echo(RGB+"0;0;250m    RGB test (0;0;250)     "+clr+"\n");
    dk_echo(RGB+"0;0;245m    RGB test (0;0;245)     "+clr+"\n");
    dk_echo(RGB+"0;0;240m    RGB test (0;0;240)     "+clr+"\n");
    dk_echo(RGB+"0;0;235m    RGB test (0;0;235)     "+clr+"\n");
    dk_echo(RGB+"0;0;230m    RGB test (0;0;230)     "+clr+"\n");
    dk_echo(RGB+"0;0;225m    RGB test (0;0;225)     "+clr+"\n");
    dk_echo(RGB+"0;0;220m    RGB test (0;0;220)     "+clr+"\n");
    dk_echo(RGB+"0;0;215m    RGB test (0;0;215)     "+clr+"\n");
    dk_echo(RGB+"0;0;210m    RGB test (0;0;210)     "+clr+"\n");
    dk_echo(RGB+"0;0;205m    RGB test (0;0;205)     "+clr+"\n");
    dk_echo(RGB+"0;0;200m    RGB test (0;0;200)     "+clr+"\n");
    dk_echo(RGB+"0;0;195m    RGB test (0;0;195)     "+clr+"\n");
    dk_echo(RGB+"0;0;190m    RGB test (0;0;190)     "+clr+"\n");
    dk_echo(RGB+"0;0;185m    RGB test (0;0;185)     "+clr+"\n");
    dk_echo(RGB+"0;0;180m    RGB test (0;0;180)     "+clr+"\n");
    dk_echo(RGB+"0;0;175m    RGB test (0;0;175)     "+clr+"\n");
    dk_echo(RGB+"0;0;170m    RGB test (0;0;170)     "+clr+"\n");
    dk_echo(RGB+"0;0;165m    RGB test (0;0;165)     "+clr+"\n");
    dk_echo(RGB+"0;0;160m    RGB test (0;0;160)     "+clr+"\n");
    dk_echo(RGB+"0;0;155m    RGB test (0;0;155)     "+clr+"\n");
    dk_echo(RGB+"0;0;150m    RGB test (0;0;150)     "+clr+"\n");
    dk_echo(RGB+"0;0;145m    RGB test (0;0;145)     "+clr+"\n");
    dk_echo(RGB+"0;0;140m    RGB test (0;0;140)     "+clr+"\n");
    dk_echo(RGB+"0;0;135m    RGB test (0;0;135)     "+clr+"\n");
    dk_echo(RGB+"0;0;130m    RGB test (0;0;130)     "+clr+"\n");
    dk_echo(RGB+"0;0;125m    RGB test (0;0;125)     "+clr+"\n");
    dk_echo(RGB+"0;0;120m    RGB test (0;0;120)     "+clr+"\n");
    dk_echo(RGB+"0;0;115m    RGB test (0;0;115)     "+clr+"\n");
    dk_echo(RGB+"0;0;110m    RGB test (0;0;110)     "+clr+"\n");
    dk_echo(RGB+"0;0;105m    RGB test (0;0;105)     "+clr+"\n");
    dk_echo(RGB+"0;0;100m    RGB test (0;0;100)     "+clr+"\n");
    dk_echo(RGB+"0;0;95m    RGB test (0;0;95)      "+clr+"\n");
    dk_echo(RGB+"0;0;90m    RGB test (0;0;90)      "+clr+"\n");
    dk_echo(RGB+"0;0;85m    RGB test (0;0;85)      "+clr+"\n");
    dk_echo(RGB+"0;0;80m    RGB test (0;0;80)      "+clr+"\n");
    dk_echo(RGB+"0;0;75m    RGB test (0;0;75)      "+clr+"\n");
    dk_echo(RGB+"0;0;70m    RGB test (0;0;70)      "+clr+"\n");
    dk_echo(RGB+"0;0;65m    RGB test (0;0;65)      "+clr+"\n");
    dk_echo(RGB+"0;0;60m    RGB test (0;0;60)      "+clr+"\n");
    dk_echo(RGB+"0;0;55m    RGB test (0;0;55)      "+clr+"\n");
    dk_echo(RGB+"0;0;50m    RGB test (0;0;50)      "+clr+"\n");
    dk_echo(RGB+"0;0;45m    RGB test (0;0;45)      "+clr+"\n");
    dk_echo(RGB+"0;0;40m    RGB test (0;0;40)      "+clr+"\n");
    dk_echo(RGB+"0;0;35m    RGB test (0;0;35)      "+clr+"\n");
    dk_echo(RGB+"0;0;30m    RGB test (0;0;30)      "+clr+"\n");
    dk_echo(RGB+"0;0;25m    RGB test (0;0;25)      "+clr+"\n");
    dk_echo(RGB+"0;0;20m    RGB test (0;0;20)      "+clr+"\n");
    dk_echo(RGB+"0;0;15m    RGB test (0;0;15)      "+clr+"\n");
    dk_echo(RGB+"0;0;10m    RGB test (0;0;10)      "+clr+"\n");
    dk_echo(RGB+"0;0;5m    RGB test (0;0;5)       "+clr+"\n");
    dk_echo(RGB+"0;0;0m    RGB test (0;0;0)       "+clr+"\n");
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"     RGB Background Colors     "+clr+"\n");
    dk_echo(bg_RGB+"255;10;10m    bg_RGB test (255;0;10)    "+clr+"\n");
    dk_echo(bg_RGB+"10;255;10m    bg_RGB test (0;255;10)    "+clr+"\n");
    dk_echo(bg_RGB+"0;0;255m    bg_RGB test (0;0;255)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;250m    bg_RGB test (0;0;250)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;245m    bg_RGB test (0;0;245)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;240m    bg_RGB test (0;0;240)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;235m    bg_RGB test (0;0;235)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;230m    bg_RGB test (0;0;230)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;225m    bg_RGB test (0;0;225)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;220m    bg_RGB test (0;0;220)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;215m    bg_RGB test (0;0;215)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;210m    bg_RGB test (0;0;210)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;205m    bg_RGB test (0;0;205)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;200m    bg_RGB test (0;0;200)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;195m    bg_RGB test (0;0;195)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;190m    bg_RGB test (0;0;190)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;185m    bg_RGB test (0;0;185)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;180m    bg_RGB test (0;0;180)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;175m    bg_RGB test (0;0;175)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;170m    bg_RGB test (0;0;170)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;165m    bg_RGB test (0;0;165)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;160m    bg_RGB test (0;0;160)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;155m    bg_RGB test (0;0;155)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;150m    bg_RGB test (0;0;150)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;145m    bg_RGB test (0;0;145)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;140m    bg_RGB test (0;0;140)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;135m    bg_RGB test (0;0;135)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;130m    bg_RGB test (0;0;130)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;125m    bg_RGB test (0;0;125)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;120m    bg_RGB test (0;0;120)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;115m    bg_RGB test (0;0;115)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;110m    bg_RGB test (0;0;110)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;105m    bg_RGB test (0;0;105)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;100m    bg_RGB test (0;0;100)     "+clr+"\n");
    dk_echo(bg_RGB+"0;0;95m    bg_RGB test (0;0;95)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;90m    bg_RGB test (0;0;90)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;85m    bg_RGB test (0;0;85)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;80m    bg_RGB test (0;0;80)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;75m    bg_RGB test (0;0;75)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;70m    bg_RGB test (0;0;70)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;65m    bg_RGB test (0;0;65)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;60m    bg_RGB test (0;0;60)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;55m    bg_RGB test (0;0;55)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;50m    bg_RGB test (0;0;50)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;45m    bg_RGB test (0;0;45)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;40m    bg_RGB test (0;0;40)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;35m    bg_RGB test (0;0;35)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;30m    bg_RGB test (0;0;30)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;25m    bg_RGB test (0;0;25)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;20m    bg_RGB test (0;0;20)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;15m    bg_RGB test (0;0;15)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;10m    bg_RGB test (0;0;10)      "+clr+"\n");
    dk_echo(bg_RGB+"0;0;5m    bg_RGB test (0;0;5)       "+clr+"\n");
    dk_echo(bg_RGB+"0;0;0m    bg_RGB test (0;0;0)       "+clr+"\n");
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"          Combinations         "+clr+"\n");
    dk_echo("negative                         "+negative+"    inverse foreground <-> background   "+clr+"\n");
    dk_echo("bg_yellow red                    "+bg_yellow+red+"    yellow backgroud / red foreground   "+clr+"\n");
    dk_echo("bg_yellow red negative           "+bg_yellow+red+negative+"         yellow / red inversed          "+clr+"\n");
    dk_echo("bg_red ..bg_green ..bg_blue      "+bg_red+"    nested   "+bg_green+"    colors    "+bg_blue+"     text    "+clr+"\n");
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"         ASCII Color Art       "+clr+"\n");
    dk_echo("\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   "+clr+"\n");
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   "+clr+"\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   "+clr+"\n");
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   "+clr+"\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   "+clr+"\n");
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   "+clr+"\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   "+clr+"\n");
    dk_echo(bg_white+"                                                       "+clr+"\n");
    dk_echo(bg_red+"                                                       "+clr+"\n");
    dk_echo(bg_white+"                                                       "+clr+"\n");
    dk_echo(bg_red+"                                                       "+clr+"\n");
    dk_echo(bg_white+"                                                       "+clr+"\n");
    dk_echo(bg_red+"                                                       "+clr+"\n");
    dk_echo("\n");
    dk_echo("\n");
}
#endif
