if(ANDROID)
	dk_depend(android)
	dk_depend(dl)
	dk_depend(log)
	dk_depend(m)
	dk_depend(sdl)
endif()
if(IOS OR IOSSIM)
	dk_depend(uikit)
	#LIST(APPEND DK_SRC DK/DKiOS.mm)
endif()
if(LINUX)
	dk_depend(dl)
	dk_depend(libasound2-dev) ##TODO: Move to DKAudio
	dk_depend(libgl1-mesa-dev)
	dk_depend(libstdc++fs)	
	dk_depend(libx11-dev)
	dk_depend(libxrandr-dev)
	dk_depend(libxtst-dev)
	dk_depend(mesa-common-dev)
	dk_depend(pthread)
	dk_depend(simple-getch)
endif()
if(MAC)
	dk_depend(core_foundation)
	dk_depend(core_services)
	dk_depend(core_graphics)
	dk_depend(carbon)		#for DKOSinfo.cpp Gestalt()
	dk_depend(iokit)		#for DKMac.cpp IO*() and kIO*()
endif()
if(RASPBERRY)
	dk_depend(bcm_host)
	dk_depend(dl)
	dk_depend(libasound2-dev) ##TODO: Move to DKAudio
	dk_depend(libgl1-mesa-dev)
	dk_depend(libstdc++fs)
	dk_depend(libx11-dev)
	dk_depend(libxrandr-dev)
	dk_depend(libxtst-dev)
	dk_depend(mesa-common-dev)
	dk_depend(pthread)
	dk_depend(simple-getch)
	dk_linkDir(/opt/vc/lib) ##TODO: move this into the appropriate 3rdParty/lib
endif()
if(WIN)
	dk_depend(psapi.lib)	# GetProcessMemoryInfo()
	dk_depend(pdh.lib)		# PdhOpenQueryA()
	dk_depend(dxva2.dll)	# GetNumberOfPhysicalMonitorsFromHMONITOR()
endif()

dk_depend(backward-cpp)
dk_depend(boxer)
dk_depend(fmt)

dk_generateCmake(DK)
dk_assets(DK)
