IF(WIN)
	LIST(APPEND WIN_LIBS shell32.lib)
	LIST(APPEND WIN_LIBS user32.lib)
	LIST(APPEND WIN_LIBS gdi32.lib)
	LIST(APPEND WIN_LIBS ole32.lib)
	LIST(APPEND WIN_LIBS Psapi.lib)
	LIST(APPEND WIN_LIBS pdh.lib)
	LIST(APPEND WIN_LIBS Comctl32.lib)
	LIST(APPEND WIN_LIBS Dxva2.dll)
	DKDEPEND(boost Boost_System)
	DKDEPEND(boost Boost_Filesystem)
ELSEIF(MAC)
	DKDEPEND(boost_1_66_0 Boost_System)
	DKDEPEND(boost_1_66_0 Boost_Filesystem)
ELSEIF(LINUX)
	DKDEPEND(libx11-dev)
	DKDEPEND(mesa-common-dev)
	DKDEPEND(libgl1-mesa-dev)
	DKDEPEND(libxrandr-dev)
	DKDEPEND(libasound2-dev) ##TODO: Move to DKAudio
	DKDEPEND(libxtst-dev)
	## DKDEPEND(libboost-tools-dev)
	DKDEPEND(boost Boost_System)
	DKDEPEND(boost Boost_Filesystem)
ELSEIF(RASPBERRY)
	DKDEPEND(libx11-dev)
	DKDEPEND(mesa-common-dev)
	DKDEPEND(libgl1-mesa-dev)
	DKDEPEND(libxrandr-dev)
	DKDEPEND(libasound2-dev) ##TODO: Move to DKAudio
	DKDEPEND(libxtst-dev)
	## DKDEPEND(libboost-tools-dev)
	DKDEPEND(boost Boost_System)
	DKDEPEND(boost Boost_Filesystem)
ELSEIF(ANDROID)
	DKDEPEND(boost Boost_System)
	DKDEPEND(boost Boost_Filesystem)
ELSEIF(IOS OR IOSSIM)
	LIST(APPEND DK_SRC DK/DKiPhone.mm)
	DKDEPEND(Boost.1.60.0-libstdcpp)
ENDIF()


DKDEPEND(DKDuktape)

DKPLUGIN(DK)
DKASSETS(DK)
