if(WIN)
	DKDEPEND(psapi.lib)	# GetProcessMemoryInfo()
	DKDEPEND(pdh.lib)	# PdhOpenQueryA()
	DKDEPEND(dxva2.dll)	# GetNumberOfPhysicalMonitorsFromHMONITOR()
endif()
if(MAC)
	DKDEPEND(core_foundation)
	DKDEPEND(core_services)
	DKDEPEND(core_graphics)
	DKDEPEND(carbon)	#for DKOSinfo.cpp Gestalt()
	DKDEPEND(iokit)		#for DKMac.cpp IO*() and kIO*()
endif()
if(IOS OR IOSSIM)
	DKDEPEND(uikit)
	#LIST(APPEND DK_SRC DK/DKiOS.mm)
endif()
if(LINUX)
	DKDEPEND(mesa-common-dev)
	DKDEPEND(libgl1-mesa-dev)
	DKDEPEND(libxrandr-dev)
	DKDEPEND(libasound2-dev) ##TODO: Move to DKAudio
	DKDEPEND(libxtst-dev)
	DKDEPEND(simple-getch)
endif()
if(RASPBERRY)
	DKDEPEND(mesa-common-dev)
	DKDEPEND(libgl1-mesa-dev)
	DKDEPEND(libx11-dev)
	DKDEPEND(libxrandr-dev)
	DKDEPEND(libasound2-dev) ##TODO: Move to DKAudio
	DKDEPEND(libxtst-dev)
	DKDEPEND(simple-getch)
endif()
if(ANDROID)
	DKDEPEND(sdl)
endif()
DKDEPEND(boxer)
DKDEPEND(fmt)

generateCmake(DK)
DKASSETS(DK)
