::TASKKILL /im cmd.exe /f
TASKKILL /im cscript.exe /f
TASKKILL /im ctfmon.exe /f
TASKKILL /im Lightshot.exe /f
TASKKILL /im MicrosoftEdgeUpdate.exe /f
TASKKILL /im mshta.exe /f
TASKKILL /im RuntimeBroker.exe /f
TASKKILL /im smartscreen.exe /f
TASKKILL /im wscript.exe /f
TASKKILL /im ShellExperienceHost.exe /f
TASKKILL /im RuntimeBroker.exe /f