dk_info("DK/DKINSTALL.cmake")

if(Android)
	dk_depend(log)
	#dk_depend(sdl)		# SDL_AndroidGetExternalStorageState()
	set(CMAKE_POSITION_INDEPENDENT_CODE ON)		# https://stackoverflow.com/a/38297422
endif()
if(Ios OR Iossim)
	dk_depend(uikit)
	#LIST(APPEND DK_SRC DK/DKiOS.mm)
endif()
if(Linux)
	#dk_depend(mesa)
	#dk_depend(libgl1-mesa-dev)
	dk_depend(libx11-dev)
	#dk_depend(libxrandr-dev)
	dk_depend(libasound2-dev) # TODO: Move to DKAudio
	dk_depend(libxtst-dev)
	#dk_depend(simple-getch)
	dk_depend(libstdc++fs)
endif()
if(Mac)
	dk_depend(core_foundation)
	dk_depend(core_services)
	dk_depend(core_graphics)
	dk_depend(carbon)		# for DKOSinfo.cpp Gestalt()
	dk_depend(iokit)		# for DKMac.cpp IO*() and kIO*()
endif()
if(Raspberry)
	#dk_depend(mesa)
	#dk_depend(libgl1-mesa-dev)
	dk_depend(libx11-dev)
	#dk_depend(libxrandr-dev)
	dk_depend(libasound2-dev) # TODO: Move to DKAudio
	dk_depend(libxtst-dev)
	#dk_depend(simple-getch)
endif()
if(Windows)
	dk_depend(psapi)		# GetProcessMemoryInfo()
	dk_depend(pdh)			# PdhOpenQueryA()
	dk_depend(dxva2)		# GetNumberOfPhysicalMonitorsFromHMONITOR()
endif()

dk_depend(backward-cpp)
dk_depend(boxer)
dk_depend(fmt)


dk_generateCmake(DK)
dk_assets(DK)
