#!/usr/bin/cmake -P
### DK.cmake ############################################################
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
	cmake_policy(SET CMP0009 NEW)
	file(GLOB_RECURSE DK.cmake "/DK.cmake")
	list(GET DK.cmake 0 DK.cmake)
	get_filename_component(DKCMAKE_FUNCTIONS_DIR "${DK.cmake}" DIRECTORY)
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} "${DKCMAKE_FUNCTIONS_DIR}/")
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")
include_guard()
#########################################################################

dk_validate(Config_Path  "dk_Config_Path()")

#DKAPP
dk_depend(DK)
dk_depend(DKArchive)
dk_depend(DKAssets)
dk_depend(DKBuild)
dk_depend(DKCodeRunner)
dk_depend(DKColorPicker)
dk_depend(DKDebug)
dk_depend(DKDevTools)
dk_depend(DKDuktapeDom)
dk_depend(DKDom)
dk_depend(DKDuktape)
dk_depend(DKEditor)
dk_depend(DKFile)
dk_depend(DKGit)
dk_depend(DKGui)
dk_depend(DKHandles)
dk_depend(DKInputTest)
dk_depend(DKLogin)
dk_depend(DKMySql)
dk_depend(DKNotepad)
dk_depend(DKOS)
dk_depend(DKPaint)
dk_depend(DKPhp)
dk_depend(DKRmlIframe)
dk_depend(DKRmlVideo)
dk_depend(sdl2_gif)
dk_depend(DKSDLRml)
dk_depend(DKSDLText)
dk_depend(DKSDLWindow)
dk_depend(DKStats)
dk_depend(DKThread)
dk_depend(DKWebTest)
dk_depend(DKWebSockets)
dk_depend(DKWebTest)
dk_depend(DKWindow)
dk_depend(DKTooltip)