@echo off 
set "STACK_0=main" 
set "globalVarA=GLOBALA" 
set "globalVarB=GLOBALB" 
set "STACK_1=funcA" 
set "STACK_2=funcB" 
set "globalVarA=GLOBAL A CHANGED" 
set "STACK_3=funcC" 
set "STACK_4=funcC2" 
set "STACK_4=" 
set "STACK_4=funcD" 
set "globalVarA=STILL A GLOBAL" 
set "STACK_4=" 
set "STACK_3=" 
set "STACK_2=" 
set "STACK_1=" 
