dk_depend(DKOSGWindow)
#dk_depend(openscenegraph osgdb_3dc)
#if(NOT ANDROID)
#	dk_depend(openscenegraph osgdb_3ds)
#	dk_depend(openscenegraph osgdb_ive)
#	dk_depend(openscenegraph osgdb_lwo)
#	dk_depend(openscenegraph osgdb_openflight)
#	dk_depend(openscenegraph osgdb_shp)
#endif()
#dk_depend(openscenegraph osgdb_ac)
#dk_depend(openscenegraph osgdb_bsp)
#dk_depend(openscenegraph osgdb_dw)
#dk_depend(openscenegraph osgdb_dxf)
#dk_depend(openscenegraph osgdb_logo)
#dk_depend(openscenegraph osgdb_lws)
#dk_depend(openscenegraph osgdb_md2)
#dk_depend(openscenegraph osgdb_obj)
#dk_depend(openscenegraph osgdb_osg)
#dk_depend(openscenegraph osgdb_rgb)
#dk_depend(openscenegraph osgdb_stl)
#dk_depend(openscenegraph osgdb_x)
#dk_depend(openscenegraph osgdb_rot)
#dk_depend(openscenegraph osgdb_scale)
#dk_depend(openscenegraph osgdb_normals)
#dk_depend(openscenegraph osgdb_trans)
#dk_depend(openscenegraph osgTerrain)
#dk_depend(openscenegraph osgVolume)
#dk_depend(openscenegraph osgSim)
#dk_depend(openscenegraph osgFX)
#dk_depend(openscenegraph osgdb_serializers_osg)
#dk_depend(openscenegraph osgParticle)
#dk_depend(openscenegraph osgdb_serializers_osgparticle)
#dk_depend(openscenegraph osgdb_deprecated_osg)


dk_generateCmake(DKOSGModel)
