.TH "libwget-parse_atom" 3 "Sun Nov 29 2020" "Version 1.99.2" "wget2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libwget-parse_atom \- Atom URL extraction routines
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwget_atom_get_urls_inline\fP (const char *atom, \fBwget_vector\fP **urls)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Routines for URL extraction from Atom feeds\&. 
.SH "Function Documentation"
.PP 
.SS "void wget_atom_get_urls_inline (const char * atom, \fBwget_vector\fP ** urls)"

.PP
\fBParameters\fP
.RS 4
\fIatom\fP Atom XML data 
.br
\fIurls\fP Pointer to return vector of URLs
.RE
.PP
Finds all URLs within the Atom XML data \fCatom\fP and returns them as vector in \fCurls\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for wget2 from the source code\&.
