DKDEPEND(libxml2)
DKDEPEND(pugixml)
IF(HAVE_DKDuktape)
	DKDEPEND(DKDuktape)
ENDIF()
IF(HAVE_DKCef)
	DKDEPEND(DKCef)
ENDIF()


#DKCOPY(${PUGIXML}/src/pugixml.hpp ${DKPLUGINS}/DKXml/pugixml.hpp FALSE)
DKCOPY(${PUGIXML}/src/pugixml.cpp ${DKPLUGINS}/DKXml/pugixml.cpp FALSE)
DKINCLUDE(${PUGIXML}/src)
DKINCLUDE(${XML2}/include)
generateCmake(DKXml)
