#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"

##################################################################################
# dk_appendFile(string, file)
#
#
dk_appendFile() {
	dk_debugFunc
	[ -z "$2" ] && dk_error "append_file <string> <file.ext> requires 2 parameters"
	
	echo "$1" >> $2
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}