#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"

##################################################################################
# dk_appendFile(string, file)
#
#
dk_appendFile() {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"
	
	[ -e "$2" ] && echo "$1" >> "$2" || echo "$1" > "$2" 
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_appendFile "appended string" "${DKSCRIPT_DIR}/appendFile_TEST.txt"
}