#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_clearCmakeCache()
#
#
dk_clearCmakeCache () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	dk_info "Clearing CMake cache . . ."
	cd "${DIGITALKNOB_DIR}" #|| dk_error "cd ${DIGITALKNOB_DIR} failed!"
	find . -name "CMakeCache.*" -delete
	rm -rf $(find . -type d -name CMakeFiles)
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}