#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"

##################################################################################
# dk_clearScreen()
#
#
dk_clearScreen () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	clear
}