#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"

##################################################################################
# dk_commandExists(<command>)
#
#
dk_commandExists () {
	dk_debugFunc
	[ $# -ne 1 ] && dk_error "Incorrect number of parameters"

	[ -n "$(command -v "$1")" ]
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}