#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_createCache()
#
#
dk_createCache () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	dk_echo "creating cache..."
	
	# write variable values line by line
	echo "$APP">"${DKBRANCH_DIR}/cache"
	echo "$TARGET_OS">>"${DKBRANCH_DIR}/cache"
	echo "$TYPE">>"${DKBRANCH_DIR}/cache"
	#echo "$DKENV">>"${DKBRANCH_DIR}/cache"
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}