#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_crlf()
#
#
#
dk_crlf() {
	dk_debugFunc
	
	dk_todo 
	return $true
}
