#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_deleteTempFiles()
#
#
dk_deleteTempFiles () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"

	dk_info "Deleting .TMP files . . ."
	cd "${DIGITALKNOB_DIR}" #|| dk_error "cd ${DIGITALKNOB_DIR} failed!"
	rm -rf $(find . -type d -name *.tmp)
	rm -rf $(find . -type d -name *.TMP)
	find . -name "*.tmp" -delete
	find . -name "*.TMP" -delete
}