#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_exit()
#
#
dk_exit () {
	dk_debugFunc
	
	echo "dk_exit $*"
	
	# TODO: when open with icon, we can use exec to keep the window open
	#exec $SHELL #$*
	
	# a pure exit is the default
	exit $*
}