#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_extract(<file_path> <destination>)
#
#
dk_extract () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"
	
	src="$1"
	dest="$2"
	
	if ! dk_fileExists "${dest}"; then
		dk_makeDirectory "${dest}"
	fi
	
	tar -xf "${src}" -C "${dest}"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	echo "dk_extract DKTEST() not implemented"
	#dk_extract "file.zip" "/path/extracted"
}