#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_extract(<file_path> <destination>)
#
#
dk_extract () {
	dk_debug "dk_extract($*)"
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "dk_extract(): Incorrect number of parameters"

	src="$1"
	dest="$2"
	
	if ! dk_fileExists "${dest}"; then
		dk_makeDirectory "${dest}"
	fi
	
	tar -xf "${src}" -C "${dest}"
	return
}