#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getFuncName(<output>)
#
#
dk_getFuncName() {
	dk_debugFunc
	[ $# -ne 1 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"
	
	eval "$1=${FUNCNAME[1]}"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_getFuncName funcName
	echo "funcName = ${funcName}"
}