#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getUsername()
#
#
dk_getUsername () {
	dk_debugFunc
	
	if [ -n "${USER-}" ]; then
		dk_printVar USER
		DKUSERNAME=$USER
	elif [ -n "${USERNAME-}" ]; then
		dk_printVar USERNAME
		DKUSERNAME=$USERNAME
	fi
	dk_printVar DKUSERNAME
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}