#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getDirectory(<path> <output>)
#
#
dk_getDirectory () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"
	
	eval "$2=$(dirname "$1")"
}