#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getFuncName()
#
#
dk_getFuncName() {
	dk_debugFunc
	[ -z "$1" ] && dk_error "get_func_name <variable> requires 1 parameter"
	
	eval "$1=${FUNCNAME[1]}"
	#echo "parameter name = $1"
	#echo "function name = ${FUNCNAME[1]}"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}