#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getExtension(<path> <output>)
#
#
dk_getExtension () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"
	
	filename="$(basename "$1")"
	eval "$2=${filename##*.}"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	filename="TestFile.extension"
	dk_getExtension "${filename}" output
	dk_printVar output
}