#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"

################################################################################
# dk_getFileSize(<path> <output>)
#
#
dk_getFileSize () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"
	
	dk_todo
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_getFileSize
}