#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_getDirectory(<path> <output>)
#
#
dk_getDirectory () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"
	
	eval "$2=$(dirname "$1")"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_getDirectory /usr/bin directory
	echo "directory = ${directory}"
	
}