#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


####################################################################
# dk_hexToDecimal(<hex> <output>)
#
#    reference: https://www.ascii-code.com
#               https://stackoverflow.com/a/13280173
#
dk_hexToDecimal () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"
	
	eval "$2=$(printf "%d\n" $1)"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_hexToDecimal 0x1b decimal
	echo "decimal = ${decimal}"

}