#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


################################################################################
# dk_hexToVariable(<name> <hex>)
#
#    reference: https://www.ascii-code.com
#               https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html#ANSI_002dC-Quoting
#               https://unix.stackexchange.com/a/347410
#
dk_hexToVariable () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"
	
	# 0x1b  prints as  '\x1b'
	# ${2//0x/x}  removes any starting 0 and changes any 0x to x
	export $1=$(printf '\%s' ${2//0x/x})
}






DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_hexToVariable HEX_0x8C 0x8C
	echo "HEX_0x8C = ${HEX_0x8C}"
	
	printf ${HEX_0x8C}
}