#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


#####################################################################
# dk_makeDirectory(<path>)
#
#
dk_makeDirectory () {
	dk_debug "dk_makeDirectory($*)"
	dk_debugFunc
	
	mkdir -p "$1"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}