#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_pushAssets()
#
#
dk_pushAssets () {
	dk_debugFunc
	[ $# -ne 0 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"
	
	dk_confirm || return 0
	
	dk_error "not implemented,  TODO"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}