#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_pushAssets()
#
#
dk_pushAssets () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	dk_confirm || return 0
	
	dk_error "not implemented,  TODO"
}