#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_pause()
#
#	Pause execution and wait for keypress to continue
#
dk_pause() {
	dk_debugFunc
	echo "dk_debugFunc()"
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	read -rp 'Press enter to continue...' key
	echo ""
	# echo $key
}