#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_pause()
#
#	Pause execution and wait for keypress to continue
#
dk_pause() {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	read -rp 'Press enter to continue...' key
	decho ""
	# echo ${key}
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}