#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_require()
#
#
dk_require() {
	dk_debugFunc
	[ -z "$1" ] && dk_error "dk_require(<func_name> <$n>) requires 2 parameters. Example dk_require my_func \$1"
	[ -z "$2" ] && dk_error "$1() requires at least 1 parameter"
}