#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_removeFromFile()
#
#
dk_removeFromFile() {
	dk_debugFunc
	[ -z "$2" ] && dk_error "remove_from_file <string> <file.ext> requires 2 parameters"

	sed -i -e "/$1/d" $2
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}