#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_require()
#
#
dk_require() {
	dk_debugFunc
	#[ $# -ne 0 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_require
}