#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_removeExtension(<filepath>)
#
#
dk_removeExtension () {
	dk_debugFunc
	[ $# -ne 1 ] && dk_error "Incorrect number of parameters"
	
	filepath="$1"
	filepath="${filepath%.*}"									    # remove everything past last dot
	[ "${filepath##*.}" = "tar" ] &&	filepath="${filepath%.*}"	# if .tar remove everything past last dot
}