#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


#####################################################################
# dk_remove(<path>)
#
#
dk_remove () {
	dk_debugFunc
	
	_path=$1
	if ! dk_fileExists "${_path}"; then
		dk_warning "dk_remove(): ${_path} does not exist"
	fi
	
	rm -r -f "${_path}"
	dk_sleep 1 # give the path a second to delete
	
	if dk_fileExists "${_path}"; then
		dk_error "dk_remove(): failed to remove ${_path}"
		return $false
	fi
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}