#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_removeCarrageReturns(<input>)
#
#
dk_removeCarrageReturns () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"

	in=$1
	out=$(echo "$in" | tr -d '\r')
	# carrage returns are removed from <out>
}