#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_remove" ] && exit || export readonly include_dk_remove=1
[ -z "$DKINIT" ] && . ./DK


#####################################################################
# dk_remove(<path>)
#
#
dk_remove () {
	dk_debugFunc
	
	_path=$1
	if ! dk_fileExists "${_path}"; then
		dk_warning "dk_remove(): ${_path} does not exist"
	fi
	
	rm -r -f "${_path}"
	dk_sleep 1 # give the path a second to delete
	
	if dk_fileExists "${_path}"; then
		dk_error "dk_remove(): failed to remove ${_path}"
		return $false
	fi
}