#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_reload()
#
#
dk_reload () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	dk_debug "reloading $DKSCRIPT_PATH"
	dk_clearScreen
	
	#FIXME: need to unset any and all include guards here.
	#       Or better yet, we need to clear the entire environment
	unset DKINIT
	
	if [ -n "$(command -v bash)" ]; then
		echo "exec /bin/bash $DKSCRIPT_PATH"
		exec /bin/bash "$DKSCRIPT_PATH"
	else
		echo "exec $DKSCRIPT_PATH"
		exec "$DKSCRIPT_PATH"
	fi
}