#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_reload()
#
#
dk_reload () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"
	
	dk_debug "reloading $DKSCRIPT_PATH"
	clear
	
	if [ -n "$(command -v bash)" ]; then
		exec /bin/bash "$DKSCRIPT_PATH"
	else
		exec "$DKSCRIPT_PATH"
	fi
}