#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_sleep" ] && exit || export readonly include_dk_sleep=1
[ -z "$DKINIT" ] && . ./DK


#####################################################################
# dk_sleep(<seconds>)
#
#
dk_sleep () {
	dk_debugFunc
	
	sleep $1
}