#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_set(<variable> <value>)
#
#
dk_set() {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"

	#eval "$1=$2"
	export $1="$2"
}





DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_set myVar "value assigned with dk_set"	
	echo "myVar = ${myVar}"
}