#!/bin/sh
echo "$0 $*"
#[ -n "$include_dk_stringContains" ] && exit || export readonly include_dk_stringContains=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_stringContains(<string> <substring>)
#
#
dk_stringContains () {
	dk_debug "dk_stringContains($*)"
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"
	
	# https://stackoverflow.com/a/8811800/688352
	_string="$1"
	dk_printVar _string
	_substring="$2"
	dk_printVar _substring
	[ "${_string#*"$_substring"}" != "$_string" ]	
}





DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###


	if dk_stringContains "1one1" "one"; then
		echo "1one1 contains one"
	else
		echo "1one1 does not contains one"
	fi

	if dk_stringContains "2two2" "tow"; then
		echo "2two2 contains tow"
	else
		echo "2two2 does not contain tow"
	fi
	
}