#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_set()
#
#
dk_set() {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"

	#eval "$1=$2"
	export $1="$2"
}





DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_set myVar "value assigned with dk_set"	
	echo "myVar = ${myVar}"
}