#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_toLower(<string> <output>)
#
#
dk_toLower () {
	dk_debugFunc
	[ $# -ne 2 ] && dk_error "${FUNCNAME}(): incorrect number of arguments"
	
	#[ dk_defined $1 ] || dk_error "dk_toLower($*): $1 is not defined"
	#eval value='$'{$1}
	
	eval "$2='$(echo "$1" | tr '[:upper:]' '[:lower:]')'"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	var="CoOnVeRtEd ThIs StRiNg To LoWeRcAsE"
	dk_toLower "${var}" var
	echo "var = ${var}"
}
