#!/bin/sh
[ -z "$DKINIT" ] && . ./DK.sh
#dk_includeGuard


##################################################################################
# dk_test(<args>)
#
#
dk_test () {
	dk_debugFunc
	
	echo "$1"
}


################################ DKTEST #########################################
#[ -n "$DKTEST" ] && ( (
DKTEST_START

	dk_test "called from TEST portion of the script"	
	
DKTEST_END
#echo "############################### END DKTEST ###############################"
#) & exec $SHELL )