#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_test(<args>)
#
#
dk_test () {
	dk_debugFunc
	
	echo "1 = $1"
	echo "{1} = ${1}"
	echo "FUNCNAME[0] = ${FUNCNAME[0]}"
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_test "called from TEST portion of the script"	
	
}