#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_validateEmscripten()
#
#
dk_validateEmscripten () {
	dk_debugFunc
	[ $# -ne 0 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"

	dk_cmakeEval "include('$DKIMPORTS_DIR/emsdk/DKMAKE.cmake')" "EMSDK;EMSDK_ENV;EMSDK_GENERATOR;EMSDK_TOOLCHAIN_FILE;EMSDK_C_COMPILER;EMSDK_CXX_COMPILER"
	dk_printVar EMSDK
	dk_printVar EMSDK_ENV
	dk_printVar EMSDK_GENERATOR
	dk_printVar EMSDK_TOOLCHAIN_FILE
	dk_printVar EMSDK_C_COMPILER
	dk_printVar EMSDK_CXX_COMPILER
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}