#!/bin/sh
#echo "$0 $*"
#[ -n "$include_dk_test" ] && exit || export readonly include_dk_test=1
[ -z "$DKINIT" ] && . ./DK


##################################################################################
# dk_validateEmscripten()
#
#
dk_validateEmscripten () {
	dk_debugFunc
	[ $# -gt 0 ] && dk_error "too many arguments"

	dk_cmakeEval "include('$DKIMPORTS_DIR/emsdk/DKMAKE.cmake')" "EMSDK;EMSDK_ENV;EMSDK_GENERATOR;EMSDK_TOOLCHAIN_FILE;EMSDK_C_COMPILER;EMSDK_CXX_COMPILER"
	dk_printVar EMSDK
	dk_printVar EMSDK_ENV
	dk_printVar EMSDK_GENERATOR
	dk_printVar EMSDK_TOOLCHAIN_FILE
	dk_printVar EMSDK_C_COMPILER
	dk_printVar EMSDK_CXX_COMPILER
}