#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


##################################################################################
# dk_validateSudo()
#
#
dk_validateSudo () {
	dk_debugFunc
	[ $# -ne 0 ] && dk_error "${FUNCNAME[0]}(): incorrect number of arguments"
	
	if command -v "sudo" >/dev/null 2>&1; then
		SUDO="sudo"
	fi
	${SUDO-} echo
}


DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_debug "DKTEST(${DKSCRIPT_NAME})"
}