#!/bin/sh
[ -z "${DKINIT}" ] && . "$(dirname $0)/DK"


###############################################################################
# dk_validate(variable func)
#
#	@variable  - The name of a variable to test
#	@func	   - The function to run if the variable is invalid.
#
dk_validate () {
	dk_debugFunc
	dk_debug "dk_validate($*)"
	[ $# -ne 2 ] && dk_error "Incorrect number of parameters"

	_var=$1
	_code=$2
	[ -n "${!_var+x}" ] && return
	
	echo "_code = ${_code}"
	dk_load ${_code}
	${_code}
	
	[ -z "${!_var+x}" ] && dk_error "dk_validate(): ${_var} is invalid"
}



DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###

	dk_validate
}