#!/bin/sh
[ -z "$DKINIT" ] && . ./DK.sh
#dk_includeGuard


##################################################################################
# dk_function()
#
#
dk_fnction() {
	dk_debugFunc
	
}




################################ DKTEST #########################################
DKTEST_START



DKTEST_END