#!/bin/sh
[ -z "$DKINIT" ] && . ./DK
#dk_includeGuard


##################################################################################
# dk_function()
#
#
dk_fnction() {
	dk_debugFunc
	
}




DKTEST() { ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ####### DKTEST ###


}