#!/usr/bin/cmake -P
if(NOT EXISTS "$ENV{DKCMAKE_FUNCTIONS_DIR_}")
	set(ENV{DKCMAKE_FUNCTIONS_DIR_} ${CMAKE_SOURCE_DIR}/../../DKCMake/functions/)
endif()
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")


############ DKCefChild ############
#NOTE: Use ${CMAKE_PROJECT_NAME} to reference the root parent project if needed

if(Android OR IOS OR Iossim)
	dk_undepend(DKCef)
	dk_return()
endif()
if(NOT HAVE_DKCef)
	dk_undepend(DKCefChild)
	dk_disable(DKCefChild)
	dk_return()
endif()

dk_depend(DKCef)
dk_assets(DKCefChild)

#dk_set(QUEUE_BUILD ON)
dk_addToPluginList(DKCefChild)
#dk_executable(DKCefChild)


if(Windows)
	# Copy the DKCefChild into the app bundle
	if(Debug)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${DEBUG_DIR}/DKCefChild.exe ${DK_Project_Dir}/assets/DKCef/${Target_Tuple}Debug OVERWRITE)
	endif()
	if(Release)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${RELEASE_DIR}/DKCefChild.exe ${DK_Project_Dir}/assets/DKCef/${Target_Tuple}Release OVERWRITE)
	endif()
endif()

if(Mac_X86_64)
#	if(Debug)
#		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${DEBUG_DIR}/DKCefChild.app "${DK_Project_Dir}/assets/DKCef/${Target_Tuple}Debug/${AppName} Helper.app" OVERWRITE)
#		dk_rename(${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/DKCefChild "${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/${AppName} Helper")
#		dk_rename(${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app "${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app")
#	endif()
#	if(Release)
#		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${RELEASE_DIR}/DKCefChild.app "${DK_Project_Dir}/assets/DKCef/${Target_Tuple}Release/${AppName} Helper.app" OVERWRITE)
#		dk_rename(${DK_Project_Dir}/${Target_Tuple}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/DKCefChild "${DK_Project_Dir}/${Target_Tuple}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app/Contents/MacOS/${AppName} Helper")
#		dk_rename(${DK_Project_Dir}/${Target_Tuple}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/DKCefChild.app "${DK_Project_Dir}/${Target_Tuple}/${RELEASE_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app")
#	endif()
#	MAC_dk_queueCommand(install_name_tool -change "@executable_path/Chromium Embedded Framework" "@executable_path/../../../../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework" "${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/Frameworks/${AppName} Helper.app/Contents/MacOS/${AppName} Helper")
#	
#	FIXME - command does not work because app does not exist yet
#	MAC_dk_queueCommand(install_name_tool -change "@executable_path/Chromium Embedded Framework" "@executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework" "${DK_Project_Dir}/${Target_Tuple}/${DEBUG_DIR}/${AppName}.app/Contents/MacOS/${AppName}")
endif()

if(Linux)
	dk_delete(${DK_Project_Dir}/assets/DKCef/DKCefChild)
	if(Debug)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${DEBUG_DIR}/DKCefChild ${DK_Project_Dir}/assets/DKCef OVERWRITE)
	endif()
	if(Release)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${RELEASE_DIR}/DKCefChild ${DK_Project_Dir}/assets/DKCef OVERWRITE)
	endif()
endif()

if(Raspberry)
	dk_delete(${DK_Project_Dir}/assets/DKCef/DKCefChild)
	if(Debug)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${DEBUG_DIR}/DKCefChild ${DK_Project_Dir}/assets/DKCef OVERWRITE)
	endif()
	if(Release)
		dk_copy(${DKCPP_PLUGINS_DIR}/DKCefChild/${Target_Tuple}/${RELEASE_DIR}/DKCefChild ${DK_Project_Dir}/assets/DKCef OVERWRITE)
	endif()
endif()




## DKCefChild win
if(Windows)
	dk_fileWrite(${Plugin_Path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	dk_appendCmake("###### ${name} ######\n")
	dk_appendCmake("cmake_minimum_required(VERSION 3.10)\n")
	#dk_appendCmake("cmake_policy(SET CMP0054 NEW)\n")
	dk_appendCmake("#!/usr/bin/cmake -P
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")\n")
	dk_appendCmake("project(DKCefChild)\n")
	dk_appendCmake("include_directories(${CEF_BINARY})\n")
	dk_appendCmake("include_directories(${DKCPP_PLUGINS_DIR})\n")
	
	## Debug ##
	dk_appendCmake("find_library(libcefD libcef.lib ${CEF_BINARY}/${DEBUG_DIR})\n")
	dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcefD})\n")
	dk_appendCmake("find_library(libcef_dll_wrapperD libcef_dll_wrapper.lib ${CEF_BINARY}/${Target_Tuple}/libcef_dll_wrapper/${DEBUG_DIR})\n")
	dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
	#dk_appendCmake("find_library(libcef_sandboxD cef_sandbox.lib ${CEF_BINARY}/${DEBUG_DIR})\n")
	#dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcef_sandboxD})\n")

	## Release ##
	dk_appendCmake("find_library(libcefR libcef.lib ${CEF_BINARY}/${RELEASE_DIR})\n")
	dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcefR})\n")
	dk_appendCmake("find_library(libcef_dll_wrapperR libcef_dll_wrapper.lib ${CEF_BINARY}/${Target_Tuple}/libcef_dll_wrapper/${RELEASE_DIR})\n")
	dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
	##dk_appendCmake("find_library(libcef_sandboxR cef_sandbox.lib ${CEF_BINARY}/${RELEASE_DIR})\n")
	#dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcef_sandboxR})\n")

	dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp ${DKCPP_PLUGINS_DIR}/DKCefChild/*.manifest)\n")	
	if(Windows_X86)
		dk_appendCmake("add_executable(DKCefChild WIN32 \${DKCefChild_SRC})\n")
	endif()
	if(Windows_X86_64)
		dk_appendCmake("add_executable(DKCefChild WIN64 \${DKCefChild_SRC})\n")
	endif()
	dk_appendCmake("target_link_libraries(DKCefChild \${CEF_BINARY_DEBUG_DKLIBS} \${CEF_BINARY_RELEASE_DKLIBS} dbghelp.lib version.lib winmm.lib ws2_32.lib psapi.lib)\n")
	dk_appendCmake("set_target_properties(DKCefChild PROPERTIES LINK_FLAGS_DEBUG \"/MANIFESTUAC:NO /SUBSYSTEM:CONSOLE /SAFESEH:NO\" LINK_FLAGS_RELEASE \"/INCREMENTAL:NO /OPT:NOREF /MANIFESTUAC:NO /SUBSYSTEM:CONSOLE /FORCE /SAFESEH:NO\")\n")
endif()


## DKCefChild mac
if(Mac)
	dk_fileWrite(${Plugin_Path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	dk_appendCmake("###### ${name} ######\n")
	dk_appendCmake("cmake_minimum_required(VERSION 3.10)\n")
	#dk_appendCmake("cmake_policy(SET CMP0002 OLD)\n")
	dk_appendCmake("#!/usr/bin/cmake -P
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")\n")
	dk_appendCmake("project(DKCefChild)\n")
	dk_appendCmake("include_directories(${CEF_BINARY})\n")
	dk_appendCmake("include_directories(${DKCPP_PLUGINS_DIR})\n")
	
	#if(Debug)
		#dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \"${CEF_BINARY}/${DEBUG_DIR}/Chromium Embedded Framework.framework\")\n")
		dk_appendCmake("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/libcef_dll_wrapper/${DEBUG_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		#dk_appendCmake("find_library(AK AppKit)\n")
		#dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS ${AK})\n")
	#endif()
	#if(Release)
		#dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \"${CEF_BINARY}/${RELEASE_DIR}/Chromium Embedded Framework.framework\")\n")
		dk_appendCmake("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/libcef_dll_wrapper/${RELEASE_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		#dk_appendCmake("find_library(AK AppKit)\n")
		#dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS ${AK})\n")
	#endif()
	
	dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp)\n")
	if(Mac_X86)
		dk_appendCmake("SET(CMAKE_OSX_ARCHITECTURES \"i386\")\n")
	endif()
	if(Mac_X86_64)
		dk_appendCmake("SET(CMAKE_OSX_ARCHITECTURES \"x86_64\")\n")
	endif()
	dk_appendCmake("add_executable(DKCefChild MACOSX_BUNDLE \${DKCefChild_SRC})\n")
	dk_appendCmake("target_link_libraries(DKCefChild \${CEF_BINARY_DEBUG_DKLIBS} \${CEF_BINARY_RELEASE_DKLIBS})\n")
endif()


## DKCefChild linux
if(Linux)
	dk_fileWrite(${Plugin_Path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	dk_appendCmake("###### ${name} ######\n")
	dk_appendCmake("cmake_minimum_required(VERSION 3.10)\n")
	#dk_appendCmake("cmake_policy(SET CMP0054 NEW)\n")
	#dk_appendCmake("CMAKE_POLICY(SET CMP0002 OLD)\n")
	dk_appendCmake("#!/usr/bin/cmake -P
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")\n")
	dk_appendCmake("project(DKCefChild)\n")
	dk_appendCmake("include_directories(${CEF_BINARY})\n")
	dk_appendCmake("include_directories(${DKCPP_PLUGINS_DIR})\n")
		
	if(Debug)
		dk_appendCmake("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/${DEBUG_DIR}/libcef_dll_wrapper)\n")
		dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		dk_appendCmake("find_library(libcefD libcef.so ${CEF_BINARY}/${DEBUG_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcefD})\n")
		
		dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp)\n")
		dk_appendCmake("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		dk_appendCmake("target_link_libraries(DKCefChild  \${CEF_BINARY_DEBUG_DKLIBS})\n")
	elseif(Release)
		dk_appendCmake("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/${RELEASE_DIR}/libcef_dll_wrapper)\n")
		dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		dk_appendCmake("find_library(libcefR libcef.so ${CEF_BINARY}/${RELEASE_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcefR})\n")
		
		dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp)\n")
		dk_appendCmake("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		dk_appendCmake("target_link_libraries(DKCefChild  \${CEF_BINARY_RELEASE_DKLIBS})\n")
	endif()
endif()

## DKCefChild raspberry
if(Raspberry)
	dk_fileWrite(${Plugin_Path}/CMakeLists.txt "### This file is generated by DKCMake. Any Changes here, will be overwritten. ###\n")
	dk_appendCmake("###### ${name} ######\n")
	dk_appendCmake("cmake_minimum_required(VERSION 3.10)\n")
	#dk_appendCmake("cmake_policy(SET CMP0054 NEW)\n")
	#dk_appendCmake("CMAKE_POLICY(SET CMP0002 OLD)\n")
	dk_appendCmake("#!/usr/bin/cmake -P
include("$ENV{DKCMAKE_FUNCTIONS_DIR_}DK.cmake")\n")
	dk_appendCmake("project(DKCefChild)\n")
	dk_appendCmake("include_directories(${CEF_BINARY})\n")
	dk_appendCmake("include_directories(${DKCPP_PLUGINS_DIR})\n")
		
	if(Debug)
		dk_appendCmake("find_library(libcef_dll_wrapperD libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/${DEBUG_DIR}/libcef_dll_wrapper)\n")
		dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcef_dll_wrapperD})\n")
		
		dk_appendCmake("find_library(libcefD libcef.so ${CEF_BINARY}/${DEBUG_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_DEBUG_DKLIBS debug \${libcefD})\n")
		
		dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp)\n")
		dk_appendCmake("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		dk_appendCmake("target_link_libraries(DKCefChild  \${CEF_BINARY_DEBUG_DKLIBS})\n")
	elseif(Release)
		dk_appendCmake("find_library(libcef_dll_wrapperR libcef_dll_wrapper.a ${CEF_BINARY}/${Target_Tuple}/${RELEASE_DIR}/libcef_dll_wrapper)\n")
		dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcef_dll_wrapperR})\n")
		
		dk_appendCmake("find_library(libcefR libcef.so ${CEF_BINARY}/${RELEASE_DIR})\n")
		dk_appendCmake("list(APPEND CEF_BINARY_RELEASE_DKLIBS optimized \${libcefR})\n")
		
		dk_appendCmake("file(GLOB DKCefChild_SRC ${DKCPP_PLUGINS_DIR}/DKCefChild/*.cpp)\n")
		dk_appendCmake("add_executable(DKCefChild \${DKCefChild_SRC})\n")
		dk_appendCmake("target_link_libraries(DKCefChild  \${CEF_BINARY_RELEASE_DKLIBS})\n")
	endif()
endif()
