DKDEPEND(codemirror)
dk_copy(${CODEMIRROR}/lib/ ${DKPLUGINS}/DKCodeMirror/lib/ TRUE)
dk_copy(${CODEMIRROR}/theme/ ${DKPLUGINS}/DKCodeMirror/theme/ TRUE)
dk_copy(${CODEMIRROR}/mode/ ${DKPLUGINS}/DKCodeMirror/mode/ TRUE)
DKASSETS(DKCodeMirror)