if(DKBUILDTOOLS_INCLUDED)
  return()
endif(DKBUILDTOOLS_INCLUDED)
set(DKBUILDTOOLS_INCLUDED true)

# https://clang.llvm.org/docs/ClangCommandLineReference.html
# https://clang.llvm.org/docs/CrossCompilation.html
# https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html
# https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html
# https://llvm.org/docs/GettingStarted.html
# https://llvm.org/docs/HowToCrossCompileLLVM.html
# https://forums.raspberrypi.com/viewtopic.php?t=244095
# https://bibouh123.wordpress.com/2014/10/13/compile-llvm-with-enabling-rtti/
# https://chromium.googlesource.com/external/github.com/google/crc32c/+/refs/tags/1.0.5/CMakeLists.txt
# https://docs.microsoft.com/en-us/cpp/build/reference/eh-exception-handling-model?view=msvc-170
# https://stackoverflow.com/a/24836566/688352

# Get the definition of any shell command                                             https://explainshell.com          
# helpful terminal commands
# lscpu                                     see details about the cpu                 https://explainshell.com/explain?cmd=lscpu
# uname -a                                  system identifier                         https://explainshell.com/explain?cmd=uname+-a
# gcc -c -Q -march=native --help=target     target specific compiler gcc flags        https://explainshell.com/explain?cmd=gcc+-c+-Q+-march%3Dnative+--help%3Dtarget
# gcc --version                             the version of gcc on the host machine    https://explainshell.com/explain?cmd=gcc+--version
# gcc --help                                general gcc help                          https://explainshell.com/explain?cmd=gcc+--help
# clang --version                           the version of clang on the host machine  https://explainshell.com/explain?cmd=clang+--version 
# clang--help                               general clang help                        https://explainshell.com/explain?cmd=clang+--help
# gcc-fpu                                   ARM processor floating point math         https://explainshell.com/explain?cmd=gcc+-fpu

# common flags for compilers
#                                         GCC                 CLANG/LLVM          MSVC                                                               NOTES
# Enable runtime type information         -frtti              -frtti              /GR                                                         
# Disable runtime type information        -fno-rtti           -fno-rtti           /GR-                                                         
# Standard C++ exception handling         -fexceptions        -fexceptions        /EHsc                                                    #https://stackoverflow.com/a/4574319/688352
# No Exceptions                           -fno-exceptions     -fno-exceptions     /D_HAS_EXCEPTIONS=0                                      #https://stackoverflow.com/a/65513682/688352
# Use address sanatizer                   -fsanitize=address  -fsanitize=address  /fsanitize=address                                       incompatable with /RTC1 
# Suppress Startup Banner                                                         /nologo     
# Enable updated __cplusplus macro                                                /Zc:__cplusplus       
# Precompiled Header Memory Limit                                                 /Zm<factor>                                              <factor> = memory size  EXAMPLE: /Zm500  
# No Experimental filesystem warning                                              /D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING
# Enable CRT Secure functions extension                                           /D__STDC_WANT_LIB_EXT1__
# supress CRT Secure function warnings                                            /D_CRT_SECURE_NO_WARNINGS
# precompiled headers                                                             /Yu<file>                                                <file> = file name  EXAMPLE: /Yustdafx.h


### User Friendly Options ###
DKSET(WARNINGS_AS_ERRORS OFF)
DKSET(WARNING_LEVEL 3)
DKSET(WARNING_4244 ON)
#DKSET(STATIC ON)
#DKSET(SHARED OFF)                                          

# xcode Variables
DKSET(XCODE_DEVROOT  /Applications/Xcode.app/Contents/Developer)
DKSET(XCODE_CLANG    ${XCODE_DEVROOT}/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang)
DKSET(XCODE_CLANGXX  ${XCODE_DEVROOT}/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++)
DKSET(XCODE_LIBTOOL  ${XCODE_DEVROOT}/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool)

# iOS variables
DKSET(IOS_DARWIN      darwin20.6.0)
DKSET(IOS_MIN_SDK     13.0)
DKSET(IOS_SYSROOT     ${XCODE_DEVROOT}/Platforms/iPhone.platform/Developer/SDKs/iPhone15.0.sdk)
DKSET(IOSSIM_SYSROOT  ${XCODE_DEVROOT}/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.0.sdk)

# linux variables
DKSET(LINUX_GCC   /usr/bin/gcc)
DKSET(LINUX_GXX   /usr/bin/g++)

# Visual C++ variables 
DKSET(MSVC_CL      C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.30.30705/bin/Hostx64/x86/cl.exe)
DKSET(MINGW32_GCC  C:/Users/Administrator/digitalknob/DK/3rdParty/mingw32-8.1.0/bin/gcc.exe)
DKSET(MINGW32_GXX  C:/Users/Administrator/digitalknob/DK/3rdParty/mingw32-8.1.0/bin/g++.exe)
DKSET(MINGW64_GCC  C:/Users/Administrator/digitalknob/DK/3rdParty/mingw64-8.1.0/bin/gcc.exe)
DKSET(MINGW64_GXX  C:/Users/Administrator/digitalknob/DK/3rdParty/mingw64-8.1.0/bin/g++.exe)
 

# Windows 32
WIN32_DKSET(DKCMAKE_FLAGS                -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON)
WIN32_DKSET(DKCMAKE_C_COMPILER           "${MSVC_CL}")
WIN32_DKSET(DKCMAKE_C_FLAGS              "/DWIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_WIN32_WINNT=0x0600 /D_USING_V110_SDK71_ /std:c17 /nologo /GR /EHsc /Zm500 /Zc:__cplusplus")
WIN32_DKSET(DKCMAKE_C_FLAGS_DEBUG        "/MTd /Od /Ob0 /Zi /RTC1 /DDEBUG /D_DEBUG")
WIN32_DKSET(DKCMAKE_C_FLAGS_RELEASE      "/MT /O2 /Ob2 /DNDEBUG")
WIN32_DKSET(DKCMAKE_CXX_COMPILER         "${MSVC_CL}")
WIN32_DKSET(DKCMAKE_CXX_FLAGS            "/DWIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_WIN32_WINNT=0x0600 /D_USING_V110_SDK71_ /std:c++17 /nologo /GR /EHsc /Zm500 /Zc:__cplusplus")
WIN32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG      "/MTd /Od /Ob0 /Zi /RTC1 /DDEBUG /D_DEBUG")
WIN32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE    "/MT /O2 /Ob2 /DNDEBUG")
WIN32_DKSET(DKCONFIGURE_FLAGS            --build=i686-w64-mingw32 --disable-shared --enable-static)
WIN32_DKSET(DKCONFIGURE_CC               ${MINGW32_GCC})
WIN32_DKSET(DKCONFIGURE_CFLAGS           "-march=i686 -DWIN32 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -D_USING_V110_SDK71_ -std=gnu17 -frtti -fexceptions")
WIN32_DKSET(DKCONFIGURE_CFLAGS_DEBUG     "-MTd -Od -Ob0 -Zi -RTC1 -DDEBUG -D_DEBUG")
WIN32_DKSET(DKCONFIGURE_CFLAGS_RELEASE   "-MT -O2 -Ob2 -DNDEBUG")
WIN32_DKSET(DKCONFIGURE_CXX	             ${MINGW32_GXX})
WIN32_DKSET(DKCONFIGURE_CXXFLAGS         "-march=i686 -DWIN32 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -D_USING_V110_SDK71_ -std:gnu++17 -frtti -fexceptions")
WIN32_DKSET(DKCONFIGURE_CXXFLAGS_DEBUG   "-MTd -Od -Ob0 -Zi -RTC1 -DDEBUG -D_DEBUG")
WIN32_DKSET(DKCONFIGURE_CXXFLAGS_RELEASE "-MT -O2 -Ob2 -DNDEBUG")
		
# Windows 64
WIN64_DKSET(DKCMAKE_FLAGS                 -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON)
WIN64_DKSET(DKCMAKE_C_COMPILER            "${MSVC_CL}")
WIN64_DKSET(DKCMAKE_C_FLAGS               "/DWIN64 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_WIN32_WINNT=0x0600 /D_USING_V110_SDK71_ /std:c17 /nologo /GR /EHsc /Zm500 /Zc:__cplusplus")
WIN64_DKSET(DKCMAKE_C_FLAGS_DEBUG         "/MTd /Od /Ob0 /Zi /RTC1 /DDEBUG /D_DEBUG")
WIN64_DKSET(DKCMAKE_C_FLAGS_RELEASE       "/MT /O2 /Ob2 /DNDEBUG")
WIN64_DKSET(DKCMAKE_CXX_COMPILER          "${MSVC_CL}")
WIN64_DKSET(DKCMAKE_CXX_FLAGS             "/DWIN63 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_WIN32_WINNT=0x0600 /D_USING_V110_SDK71_ /std:c++17 /nologo /GR /EHsc /Zm500 /Zc:__cplusplus /MACHINE:X64")
WIN64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG       "/MTd /Od /Ob0 /Zi /RTC1 /DDEBUG /D_DEBUG")
WIN64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE     "/MT /O2 /Ob2 /DNDEBUG")
WIN64_DKSET(DKCONFIGURE_FLAGS             --build=x86_64-w64-mingw32 --disable-shared --enable-static)
WIN64_DKSET(DKCONFIGURE_CC                ${MINGW64_GCC})
WIN64_DKSET(DKCONFIGURE_CFLAGS            "-march=x86-64 -DWIN64 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -D_USING_V110_SDK71_ -std=gnu17 -frtti -fexceptions")
WIN64_DKSET(DKCONFIGURE_CFLAGS_DEBUG      "-MTd -Od -Ob0 -Zi -RTC1 -DDEBUG -D_DEBUG")
WIN64_DKSET(DKCONFIGURE_CFLAGS_RELEASE    "-MT -O2 -Ob2 -DNDEBUG")
WIN64_DKSET(DKCONFIGURE_CXX	              ${MINGW64_GXX})
WIN64_DKSET(DKCONFIGURE_CXXFLAGS          "-march=x86-64 -DWIN64 -D_WINDOWS -D_CRT_SECURE_NO_WARNINGS -D_WIN32_WINNT=0x0600 -D_USING_V110_SDK71_ -std:gnu++17 -frtti -fexceptions")
WIN64_DKSET(DKCONFIGURE_CXXFLAGS_DEBUG    "-MTd -Od -Ob0 -Zi -RTC1 -DDEBUG -D_DEBUG")
WIN64_DKSET(DKCONFIGURE_CXXFLAGS_RELEASE  "-MT -O2 -Ob2 -DNDEBUG")

# Moc 32
MAC32_DKSET(DKCMAKE_FLAGS                 -DCMAKE_OSX_ARCHITECTURES=x86 -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON)
MAC32_DKSET(DKCMAKE_C_COMPILER            ${XCODE_CLANG})
MAC32_DKSET(DKCMAKE_C_FLAGS               "-arch i686 -DMAC -DMAC32 -std=c17 -x objective-c")
MAC32_DKSET(DKCMAKE_C_FLAGS_DEBUG         "-DDEBUG -D_DEBUG")
MAC32_DKSET(DKCMAKE_C_FLAGS_RELEASE       "-DNDEBUG")
MAC32_DKSET(DKCMAKE_CXX_COMPILER          ${XCODE_CLANGXX})
MAC32_DKSET(DKCMAKE_CXX_FLAGS             "-arch i686 -DMAC -DMAC32 -std=c++17 -x objective-c++")
MAC32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG       "-DDEBUG -D_DEBUG")
MAC32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE     "-DNDEBUG")
MAC32_DKSET(DKCONFIGURE_FLAGS             --disable-shared --enable-static)
MAC32_DKSET(DKCONFIGURE_CC                ${XCODE_CLANG})
MAC32_DKSET(DKCONFIGURE_CFLAGS            "-arch i686 -DMAC -DMAC32 -std=c17 -x objective-c")
MAC32_DKSET(DKCONFIGURE_CFLAGS_DEBUG      "-DDEBUG -D_DEBUG")
MAC32_DKSET(DKCONFIGURE_CFLAGS_RELEASE    "-DNDEBUG")
MAC32_DKSET(DKCONFIGURE_CXX               ${XCODE_CLANGXX})
MAC32_DKSET(DKCONFIGURE_CXXFLAGS          "-arch i686 -DMAC -DMAC32 -std=c++17 -x objective-c++")
MAC32_DKSET(DKCONFIGURE_CXXFLAGS_DEBUG    "-DDEBUG -D_DEBUG")
MAC32_DKSET(DKCONFIGURE_CXXFLAGS_RELEASE  "-DNDEBUG")

# Moc 64
MAC64_DKSET(DKCMAKE_FLAGS                 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON)
MAC64_DKSET(DKCMAKE_C_COMPILER            ${XCODE_CLANG})
MAC64_DKSET(DKCMAKE_C_FLAGS               "-DMAC -DMAC64 -std=c17 -x objective-c")
MAC64_DKSET(DKCMAKE_C_FLAGS_DEBUG         "-DDEBUG -D_DEBUG")
MAC64_DKSET(DKCMAKE_C_FLAGS_RELEASE       "-DNDEBUG")
WIN64_DKSET(DKCMAKE_CXX_COMPILER          ${XCODE_CLANGXX})
MAC64_DKSET(DKCMAKE_CXX_FLAGS             "-DMAC -DMAC64 -std=c++17 -x objective-c++")
MAC64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG       "-DDEBUG -D_DEBUG")
MAC64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE     "-DNDEBUG")
MAC64_DKSET(DKCONFIGURE_FLAGS             --disable-shared --enable-static)
MAC64_DKSET(DKCONFIGURE_CXX               ${XCODE_CLANGXX})
MAC64_DKSET(DKCONFIGURE_CFLAGS            "-arch x86-64 -DMAC -DMAC64 -std=c17 -x objective-c")
MAC64_DKSET(DKCONFIGURE_CFLAGS_DEBUG      "-DDEBUG -D_DEBUG")
MAC64_DKSET(DKCONFIGURE_CFLAGS_RELEASE    "-DNDEBUG")
MAC64_DKSET(DKCONFIGURE_CC                ${XCODE_CLANG})
MAC64_DKSET(DKCONFIGURE_CXXFLAGS          "-arch x86-64 -DMAC -DMAC64 -std=c++17 -x objective-c++")
MAC32_DKSET(DKCONFIGURE_CXXFLAGS_DEBUG    "-DDEBUG -D_DEBUG")
MAC32_DKSET(DKCONFIGURE_CXXFLAGS_RELEASE  "-DNDEBUG")

# iOS 32
IOS32_DKSET(DKCMAKE_FLAGS              -DCMAKE_TOOLCHAIN_FILE=${DKCMAKE}/ios.toolchain.cmake -DPLATFORM=OS -DSDK_VERSION=15.0 -DDEPLOYMENT_TARGET=${IOS_MIN_SDK} -DBUILD_SHARED_LIBS=OFF)
#IOS32_DKSET(DKCMAKE_C_COMPILER         "")
IOS32_DKSET(DKCMAKE_C_FLAGS            "-DIOS -DIOS32 -std=c17 -x objective-c")
IOS32_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
IOS32_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#IOS32_DKSET(DKCMAKE_CXX_COMPILER      "")
IOS32_DKSET(DKCMAKE_CXX_FLAGS          "-DIOS -DIOS32 -std=c++17 -x objective-c++")
IOS32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
IOS32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
IOS32_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static --host i686-apple-${IOS_DARWIN})
IOS32_DKSET(DKCONFIGURE_CC             ${XCODE_CLANG})
IOS32_DKSET(DKCONFIGURE_CFLAGS         "-arch i686 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOS_SYSROOT}")
IOS32_DKSET(DKCONFIGURE_CXX	           ${XCODE_CLANGXX})
IOS32_DKSET(DKCONFIGURE_CXXFLAGS       "-arch i686 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOS_SYSROOT}")

# iOS 64
IOS64_DKSET(DKCMAKE_FLAGS              -DCMAKE_TOOLCHAIN_FILE=${DKCMAKE}/ios.toolchain.cmake -DPLATFORM=OS64 -DSDK_VERSION=15.0 -DDEPLOYMENT_TARGET=${IOS_MIN_SDK} -DBUILD_SHARED_LIBS=OFF)
#IOS64_DKSET(DKCMAKE_C_COMPILER         "")
IOS64_DKSET(DKCMAKE_C_FLAGS            "-DIOS -DIOS64 -std=c17 -x objective-c")
IOS64_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
IOS64_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#IOS64_DKSET(DKCMAKE_CXX_COMPILER      "")
IOS64_DKSET(DKCMAKE_CXX_FLAGS          "-DIOS -DIOS64 -std=c++17 -x objective-c++")
IOS64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
IOS64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
IOS64_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static --host x86_64-apple-${IOS_DARWIN})
IOS64_DKSET(DKCONFIGURE_CC             ${XCODE_CLANG})
IOS64_DKSET(DKCONFIGURE_CFLAGS         "-arch x86_64 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOS_SYSROOT}")
IOS64_DKSET(DKCONFIGURE_CXX	           ${XCODE_CLANGXX})
IOS64_DKSET(DKCONFIGURE_CXXFLAGS       "-arch x86_64 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOS_SYSROOT}")

# iOS Simulator 32
IOSSIM32_DKSET(DKCMAKE_FLAGS              -DCMAKE_TOOLCHAIN_FILE=${DKCMAKE}/ios.toolchain.cmake -DPLATFORM=SIMULATOR -DSDK_VERSION=15.0 -DDEPLOYMENT_TARGET=13.0 -DBUILD_SHARED_LIBS=OFF)
#IOSSIM32_DKSET(DKCMAKE_C_COMPILER         "")
IOSSIM32_DKSET(DKCMAKE_C_FLAGS            "-DIOS -DIOS32 -DIOSSIM -DIOSSIM32 -std=c17 -x objective-c")
IOSSIM32_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
IOSSIM32_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#IOSSIM32_DKSET(DKCMAKE_CXX_COMPILER      "")
IOSSIM32_DKSET(DKCMAKE_CXX_FLAGS          "-DIOS -DIOS32 -DIOSSIM -DIOSSIM32 -std=c++17 -x objective-c++")
IOSSIM32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
IOSSIM32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
IOSSIM32_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static --host i686-apple-${IOS_DARWIN})
IOSSIM32_DKSET(DKCONFIGURE_CC             ${XCODE_CLANG})
IOSSIM32_DKSET(DKCONFIGURE_CFLAGS         "-arch i686 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOSSIM_SYSROOT}")
IOSSIM32_DKSET(DKCONFIGURE_CXX	          ${XCODE_CLANGXX})
IOSSIM32_DKSET(DKCONFIGURE_CXXFLAGS       "-arch i686 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOSSIM_SYSROOT}")

# iOS Simulator 64
IOSSIM64_DKSET(DKCMAKE_FLAGS              -DCMAKE_TOOLCHAIN_FILE=${DKCMAKE}/ios.toolchain.cmake -DPLATFORM=SIMULATOR64 -DSDK_VERSION=15.0 -DDEPLOYMENT_TARGET=13.0 -DBUILD_SHARED_LIBS=OFF)
#IOSSIM64_DKSET(DKCMAKE_C_COMPILER         "")
IOSSIM64_DKSET(DKCMAKE_C_FLAGS            "-DIOS -DIOS64 -DIOSSIM -DIOSSIM64 -std=c17 -x objective-c")
IOSSIM64_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
IOSSIM64_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#IOSSIM64_DKSET(DKCMAKE_CXX_COMPILER      "")
IOSSIM64_DKSET(DKCMAKE_CXX_FLAGS          "-DIOS -DIOS64 -DIOSSIM -DIOSSIM64 -std=c++17 -x objective-c++")
IOSSIM64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
IOSSIM64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
IOSSIM64_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static --host x86_64-apple-${IOS_DARWIN})
IOSSIM64_DKSET(DKCONFIGURE_CC             ${XCODE_CLANG})
IOSSIM64_DKSET(DKCONFIGURE_CFLAGS         "-arch x86_64 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOSSIM_SYSROOT}")
IOSSIM64_DKSET(DKCONFIGURE_CXX	          ${XCODE_CLANGXX})
IOSSIM64_DKSET(DKCONFIGURE_CXXFLAGS       "-arch x86_64 -mios-version-min=${IOS_MIN_SDK} -isysroot ${IOSSIM_SYSROOT}")

# Linux 32
LINUX32_DKSET(DKCMAKE_FLAGS              -DBUILD_SHARED_LIBS=OFF)
#LINUX32_DKSET(DKCMAKE_C_COMPILER         "")
LINUX32_DKSET(DKCMAKE_C_FLAGS            "-DLINUX -DLINUX32 -std=gnu11 -no-pie -fPIC")
LINUX32_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
LINUX32_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#LINUX32_DKSET(DKCMAKE_CXX_COMPILER      "")
LINUX32_DKSET(DKCMAKE_CXX_FLAGS          "-DLINUX -DLINUX32 -std=gnu++17 -lstdc++fs -no-pie -fPIC")
LINUX32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
LINUX32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
LINUX32_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
LINUX32_DKSET(DKCONFIGURE_CC             ${LINUX_GCC})
LINUX32_DKSET(DKCONFIGURE_CFLAGS         "-march=i686 -DLINUX -DLINUX32 -std=gnu11 -no-pie -fPIC")
LINUX32_DKSET(DKCONFIGURE_CXX            ${LINUX_GXX})
LINUX32_DKSET(DKCONFIGURE_CXXFLAGS       "-march=i686 -DLINUX -DLINUX32 -std=gnu++17 -lstdc++fs -no-pie -fPIC")

# Linux 64
LINUX64_DKSET(DKCMAKE_FLAGS              -DBUILD_SHARED_LIBS=OFF)
#LINUX64_DKSET(DKCMAKE_C_COMPILER         "")
LINUX64_DKSET(DKCMAKE_C_FLAGS            "-march=x86-64 -DLINUX -DLINUX64 -std=gnu11 -no-pie -fPIC")
LINUX64_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
LINUX64_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#LINUX64_DKSET(DKCMAKE_CXX_COMPILER      "")
LINUX64_DKSET(DKCMAKE_CXX_FLAGS          "-march=x86-64 -DLINUX -DLINUX64 -std=gnu++17 -lstdc++fs -no-pie -fPIC")
LINUX64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
LINUX64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
LINUX64_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
LINUX64_DKSET(DKCONFIGURE_CC             ${LINUX_GCC})
LINUX64_DKSET(DKCONFIGURE_CFLAGS         "-march=x86-64 -DLINUX -DLINUX64 -std=gnu11 -no-pie -fPIC")
LINUX64_DKSET(DKCONFIGURE_CXX            ${LINUX_GXX})
LINUX64_DKSET(DKCONFIGURE_CXXFLAGS       "-march=x86-64 -DLINUX -DLINUX64 -std=gnu++17 -lstdc++fs -no-pie -fPIC")

# Raspbery 32
RASPBERRY32_DKSET(DKCMAKE_FLAGS              -DBUILD_SHARED_LIBS=OFF)
#RASPBERRY32_DKSET(DKCMAKE_C_COMPILER         "")
RASPBERRY32_DKSET(DKCMAKE_C_FLAGS            "-DLINUX -DLINUX32 -DRASPBERRY -DRASPBERRY32 -std=gnu11 -no-pie -fPIC")
RASPBERRY32_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
RASPBERRY32_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#RASPBERRY32_DKSET(DKCMAKE_CXX_COMPILER      "")
RASPBERRY32_DKSET(DKCMAKE_CXX_FLAGS          "-DLINUX -DLINUX32 -DRASPBERRY -DRASPBERRY32 -std=gnu++17 -lstdc++fs -no-pie -fPIC")
RASPBERRY32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
RASPBERRY32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
RASPBERRY32_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
RASPBERRY32_DKSET(DKCONFIGURE_CC             ${LINUX_GCC})
RASPBERRY32_DKSET(DKCONFIGURE_CFLAGS         "-march=armv7l")
RASPBERRY32_DKSET(DKCONFIGURE_CXX            ${LINUX_GXX})
RASPBERRY32_DKSET(DKCONFIGURE_CXXFLAGS       "-march=armv7l")

# Raspbery 64
RASPBERRY64_DKSET(DKCMAKE_FLAGS              -DBUILD_SHARED_LIBS=OFF)
#RASPBERRY64_DKSET(DKCMAKE_C_COMPILER         "")
RASPBERRY64_DKSET(DKCMAKE_C_FLAGS            "-DLINUX -DLINUX64 -DRASPBERRY -DRASPBERRY64 -std=gnu11 -no-pie -fPIC")
RASPBERRY64_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
RASPBERRY64_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#RASPBERRY64_DKSET(DKCMAKE_CXX_COMPILER      "")
RASPBERRY64_DKSET(DKCMAKE_CXX_FLAGS          "-DLINUX -DLINUX64 -DRASPBERRY -DRASPBERRY64 -std=gnu++17 -lstdc++fs -no-pie -fPIC")
RASPBERRY64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
RASPBERRY64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
RASPBERRY64_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
RASPBERRY64_DKSET(DKCONFIGURE_CC             ${LINUX_GCC})
#RASPBERRY64_DKSET(DKCONFIGURE_CFLAGS         "-march=armv7l")
RASPBERRY64_DKSET(DKCONFIGURE_CXX            ${LINUX_GXX})
#RASPBERRY64_DKSET(DKCONFIGURE_CXXFLAGS       "-march=armv7l")

# Android 32
ANDROID32_DKSET(DKCMAKE_FLAGS
	-DANDROID_PLATFORM=26
	-DBUILD_SHARED_LIBS=OFF 
	-DANDROID_NDK=${ANDROIDNDK}
	-DCMAKE_TOOLCHAIN_FILE=${ANDROIDNDK}/build/cmake/android.toolchain.cmake
	-DANDROID_TOOLCHAIN=clang
	-DANDROID_ABI=armeabi-v7a
	-DANDROID_STL=c++_static
	-DANDROID_CPP_FEATURES="rtti exceptions")
#ANDROID32_DKSET(DKCMAKE_C_COMPILER         "")
ANDROID32_DKSET(DKCMAKE_C_FLAGS            "-DANDROID -DANDROID32 -std=c17")
ANDROID32_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
ANDROID32_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#ANDROID32_DKSET(DKCMAKE_CXX_COMPILER      "")
ANDROID32_DKSET(DKCMAKE_CXX_FLAGS          "-DANDROID -DANDROID32 -std=c++1z")
ANDROID32_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
ANDROID32_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
ANDROID32_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
#ANDROID32_DKSET(DKCONFIGURE_CC             ${CLANG})
ANDROID32_DKSET(DKCONFIGURE_CFLAGS         "-DANDROID -DANDROID32 -std=c17")
#ANDROID32_DKSET(DKCONFIGURE_CXX            ${CLANGXX})
ANDROID32_DKSET(DKCONFIGURE_CXXFLAGS       "-DANDROID -DANDROID32 -std=c++1z")

# Android 64
ANDROID64_DKSET(DKCMAKE_FLAGS
	-DANDROID_PLATFORM=26
	-DBUILD_SHARED_LIBS=OFF 
	-DANDROID_NDK=${ANDROIDNDK}
	-DCMAKE_TOOLCHAIN_FILE=${ANDROIDNDK}/build/cmake/android.toolchain.cmake
	-DANDROID_TOOLCHAIN=clang
	-DANDROID_ABI=arm64-v8a
	-DANDROID_STL=c++_static
	-DANDROID_CPP_FEATURES="rtti exceptions")
#ANDROID64_DKSET(DKCMAKE_C_COMPILER         "")
ANDROID64_DKSET(DKCMAKE_C_FLAGS            "-DANDROID -DANDROID64 -std=c17")
ANDROID64_DKSET(DKCMAKE_C_FLAGS_DEBUG      "-DDEBUG -D_DEBUG")
ANDROID64_DKSET(DKCMAKE_C_FLAGS_RELEASE    "-DNDEBUG")
#ANDROID64_DKSET(DKCMAKE_CXX_COMPILER      "")
ANDROID64_DKSET(DKCMAKE_CXX_FLAGS          "-DANDROID -DANDROID64 -std=c++1z")
ANDROID64_DKSET(DKCMAKE_CXX_FLAGS_DEBUG    "-DDEBUG -D_DEBUG")
ANDROID64_DKSET(DKCMAKE_CXX_FLAGS_RELEASE  "-DNDEBUG")
ANDROID64_DKSET(DKCONFIGURE_FLAGS          --disable-shared --enable-static)
#ANDROID64_DKSET(DKCONFIGURE_CC             ${CLANG})
ANDROID64_DKSET(DKCONFIGURE_CFLAGS         "-DANDROID -DANDROID64 -std=c17")
#ANDROID64_DKSET(DKCONFIGURE_CXX            ${CLANGXX})
ANDROID64_DKSET(DKCONFIGURE_CXXFLAGS       "-DANDROID -DANDROID64 -std=c++1z")








# Setup done by cmake from here
if(WARNINGS_AS_ERRORS)
	WIN_DKSET(DKCMAKE_C_FLAGS "${DKCMAKE_C_FLAGS} /WX")
	WIN_DKSET(DKCMAKE_CXX_FLAGS "${DKCMAKE_CXX_FLAGS} /WX")
endif()
if(WARNING_LEVEL)
	WIN_DKSET(DKCMAKE_C_FLAGS "${DKCMAKE_C_FLAGS} /W${WARNING_LEVEL}")
	WIN_DKSET(DKCMAKE_CXX_FLAGS "${DKCMAKE_CXX_FLAGS} /W${WARNING_LEVEL}")
endif()
if(WARNING_4244) # /wd4244 - Warning: possible loss of data 
	WIN_DKSET(DKCMAKE_C_FLAGS "${DKCMAKE_C_FLAGS} /wd4244")
	WIN_DKSET(DKCMAKE_CXX_FLAGS "${DKCMAKE_CXX_FLAGS} /wd4244")
endif()
message(STATUS "DKCMAKE_C_FLAGS:           ${DKCMAKE_C_FLAGS}")
message(STATUS "DKCMAKE_C_FLAGS_DEBUG:     ${DKCMAKE_C_FLAGS_DEBUG}")
message(STATUS "DKCMAKE_C_FLAGS_RELEASE:   ${DKCMAKE_C_FLAGS_RELEASE}")
message(STATUS "DKCMAKE_CXX_FLAGS:         ${DKCMAKE_CXX_FLAGS}")
message(STATUS "DKCMAKE_CXX_FLAGS_DEBUG:   ${DKCMAKE_CXX_FLAGS_DEBUG}")
message(STATUS "DKCMAKE_CXX_FLAGS_RELEASE: ${DKCMAKE_CXX_FLAGS_RELEASE}")


DKSET(CMAKE_C_FLAGS           "${CMAKE_C_FLAGS} ${DKCMAKE_C_FLAGS}")
DKSET(CMAKE_C_FLAGS_DEBUG     "${CMAKE_C_FLAGS_DEBUG} ${DKCMAKE_C_FLAGS_DEBUG}")
DKSET(CMAKE_C_FLAGS_RELEASE   "${CMAKE_C_FLAGS_RELEASE} ${DKCMAKE_C_FLAGS_RELEASE}")
DKSET(CMAKE_CXX_FLAGS         "${CMAKE_CXX_FLAGS} ${DKCMAKE_CXX_FLAGS}")
DKSET(CMAKE_CXX_FLAGS_DEBUG   "${CMAKE_CXX_FLAGS_DEBUG} ${DKCMAKE_CXX_FLAGS_DEBUG}")
DKSET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${DKCMAKE_CXX_FLAGS_RELEASE}")
message(STATUS "CMAKE_C_FLAGS:            ${CMAKE_C_FLAGS}")
message(STATUS "CMAKE_C_FLAGS_DEBUG:      ${CMAKE_C_FLAGS_DEBUG}")
message(STATUS "CMAKE_C_FLAGS_RELEASE:    ${CMAKE_C_FLAGS_RELEASE}")
message(STATUS "CMAKE_CXX_FLAGS:          ${CMAKE_CXX_FLAGS}")
message(STATUS "CMAKE_CXX_FLAGS_DEBUG:    ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS "CMAKE_CXX_FLAGS_RELEASE:  ${CMAKE_CXX_FLAGS_RELEASE}")

#DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} 
#-DCMAKE_C_FLAGS=${DKCMAKE_C_FLAGS}
#-DCMAKE_C_FLAGS_DEBUG=${DKCMAKE_C_FLAGS_DEBUG}
#-DCMAKE_C_FLAGS_RELEASE=${DKCMAKE_C_FLAGS_RELEASE}
#-DCMAKE_CXX_FLAGS=${DKCMAKE_CXX_FLAGS}
#-DCMAKE_CXX_FLAGS_DEBUG=${DKCMAKE_CXX_FLAGS_DEBUG}
#-DCMAKE_CXX_FLAGS_RELEASE=${DKCMAKE_CXX_FLAGS_RELEASE})
if(DKCMAKE_C_FLAGS)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_C_FLAGS=${DKCMAKE_C_FLAGS})
endif()
if(DKCMAKE_C_FLAGS_DEBUG)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_C_FLAGS_DEBUG=${DKCMAKE_C_FLAGS_DEBUG})
endif()
if(DKCMAKE_C_FLAGS_RELEASE)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_C_FLAGS_RELEASE=${DKCMAKE_C_FLAGS_RELEASE})
endif()
if(DKCMAKE_CXX_FLAGS)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_CXX_FLAGS=${DKCMAKE_CXX_FLAGS})
endif()
if(DKCMAKE_CXX_FLAGS_DEBUG)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_CXX_FLAGS_DEBUG=${DKCMAKE_CXX_FLAGS_DEBUG})
endif()
if(DKCMAKE_CXX_FLAGS_RELEASE)
	DKSET(DKCMAKE_FLAGS ${DKCMAKE_FLAGS} -DCMAKE_CXX_FLAGS_RELEASE=${DKCMAKE_CXX_FLAGS_RELEASE})
endif()

#DKSET(DKCONFIGURE_FLAGS ${DKCONFIGURE_FLAGS}
#"CC=${DKCONFIGURE_CC}"
#"CXX=${DKCONFIGURE_CXX}"
#"CFLAGS=${DKCONFIGURE_CFLAGS}"
#"CXXFLAGS=${DKCONFIGURE_CXXFLAGS}")
if(DKCONFIGURE_CC)
	DKSET(DKCONFIGURE_FLAGS ${DKCONFIGURE_FLAGS} CC=${DKCONFIGURE_CC})
endif()
if(DKCONFIGURE_CXX)
	DKSET(DKCONFIGURE_FLAGS ${DKCONFIGURE_FLAGS} CXX=${DKCONFIGURE_CXX})
endif()
if(DKCONFIGURE_CFLAGS)
	DKSET(DKCONFIGURE_FLAGS ${DKCONFIGURE_FLAGS} CFLAGS="${DKCONFIGURE_CFLAGS}")
endif()
if(DKCONFIGURE_CXXFLAGS)
	DKSET(DKCONFIGURE_FLAGS ${DKCONFIGURE_FLAGS} CXXFLAGS="${DKCONFIGURE_CXXFLAGS}")
endif()



#Wait()


### DEPENDS ###
DKDEPEND(git)
DKDEPEND(cmake)

### WINDOWS ###	
if(CMAKE_HOST_WIN32 AND WIN)
	DKDEPEND(visualstudio)
	DKDEPEND(imagemagick)
	
	DKSET(DKCMAKE_WIN32 ${CMAKE_EXE} -G ${VS_GENERATOR} -A Win32 ${DKCMAKE_FLAGS})  # Windows 32
	DKSET(DKCONFIGURE_WIN32 ../../configure ${DKCONFIGURE_FLAGS})                   # Windows 32
	DKSET(DKCMAKE_WIN64 ${CMAKE_EXE} -G ${VS_GENERATOR} -A x64 ${DKCMAKE_FLAGS})    # Windows 64
	DKSET(DKCONFIGURE_WIN64 ../../configure ${DKCONFIGURE_FLAGS})                   # Windows 64
endif()

if(CMAKE_HOST_APPLE)
	DKDEPEND(xcode)
	
	DKSET(DKCMAKE_MAC32 ${CMAKE_EXE} -G "Xcode" ${DKCMAKE_FLAGS})     # Mac 32
	DKSET(DKCONFIGURE_MAC32 ../../configure ${DKCONFIGURE_FLAGS})     # Mac 32
	DKSET(DKCMAKE_MAC64 ${CMAKE_EXE} -G "Xcode" ${DKCMAKE_FLAGS})     # Mac 64
	DKSET(DKCONFIGURE_MAC64 ../../configure ${DKCONFIGURE_FLAGS})     # Mac 64
	DKSET(DKCMAKE_IOS32 ${CMAKE_EXE} -G "Xcode" ${DKCMAKE_FLAGS})     # iOS 32
	DKSET(DKCONFIGURE_IOS32 ../../configure ${DKCONFIGURE_FLAGS})     # iOS 32
	DKSET(DKCMAKE_IOS64 ${CMAKE_EXE} -G "Xcode"	${DKCMAKE_FLAGS})     # iOS 64
	DKSET(DKCONFIGURE_IOS64 ../../configure ${DKCONFIGURE_FLAGS})     # iOS 64
	DKSET(DKCMAKE_IOSSIM32 ${CMAKE_EXE} -G "Xcode" ${DKCMAKE_FLAGS})  # iOS Simulator 32
	DKSET(DKCONFIGURE_IOSSIM32 ../../configure ${DKCONFIGURE_FLAGS})  # iOS Simulator 32
	DKSET(DKCMAKE_IOSSIM64 ${CMAKE_EXE} -G "Xcode" ${DKCMAKE_FLAGS})  # iOS Simulator 64
	DKSET(DKCONFIGURE_IOSSIM64 ../../configure ${DKCONFIGURE_FLAGS})  # iOS Simulator 64
endif()

if(LINUX)
	##DKDEPEND(kdevelop)
	DKDEPEND(libx11-dev)
	LINUX_LIB(pthread)
	LINUX_LIB(dl)
	LINUX_LIB(libstdc++fs.a)
	
	DKSET(DKCMAKE_LINUX_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)        # Linux Debug
	DKSET(DKCMAKE_LINUX_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)    #Linux Release
	DKSET(DKCMAKE_LINUX32_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)      # Linux 32 Debug
	DKSET(DKCMAKE_LINUX32_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)  # Linux 32 Release
	DKSET(DKCMAKE_LINUX64_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)      # Linux 64 Debug
	DKSET(DKCMAKE_LINUX64_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)  # Linux 64 Release
	DKSET(DKCONFIGURE_LINUX ../../configure ${DKCONFIGURE_FLAGS})                                                # Linux
endif()

if(CMAKE_HOST_LINUX AND RASPBERRY)
	DKDEPEND(libx11-dev)
	RASPBERRY_LIB(pthread)
	RASPBERRY_LIB(dl)
	RASPBERRY_LIB(libstdc++fs.a)
	link_directories(/opt/vc/lib)
	RASPBERRY_LIB(bcm_host)
	
	DKSET(DKCMAKE_RASPBERRY_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)        # RaspBerry Debug
	DKSET(DKCMAKE_RASPBERRY_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)    # RaspBerry Release
	DKSET(DKCMAKE_RASPBERRY32_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)      # RaspBerry 32 Debug
	DKSET(DKCMAKE_RASPBERRY32_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)  # RaspBerry 32 Release
	DKSET(DKCMAKE_RASPBERRY64_DEBUG ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Debug)      # RaspBerry 64 Debug
	DKSET(DKCMAKE_RASPBERRY64_RELEASE ${CMAKE_EXE} -G "Unix Makefiles" ${DKCMAKE_FLAGS} -DCMAKE_BUILD_TYPE=Release)  # RaspBerry 64 Release
	DKSET(DKCONFIGURE_RASPBERRY ../../configure ${DKCONFIGURE_FLAGS})                                                # RaspBerry
endif()

if(CMAKE_HOST_WIN32 AND ANDROID)
	ANDROID_LIB(dl)
	ANDROID_LIB(log)
	ANDROID_LIB(android)
	ANDROID_LIB(m)
	DKDEPEND(jdk)
	DKDEPEND(apache-ant)
	DKDEPEND(android-sdk)
	#DKDEPEND(android-studio)
	DKDEPEND(android-ndk) 
	DKDEPEND(visualstudio)
	DKDEPEND(mingw32)
	DKDEPEND(msys)
	DKDEPEND(openssl)
	#DKINCLUDE(${ANDROIDNDK}/sources/android/cpufeatures)
	
	DKSET(DKCMAKE_ANDROID32 ${CMAKE_EXE} -G ${VS_GENERATOR} -A ARM ${DKCMAKE_FLAGS})    # Android 32
	DKSET(DKCMAKE_ANDROID64 ${CMAKE_EXE} -G ${VS_GENERATOR} -A ARM64 ${DKCMAKE_FLAGS})  # Android 64
	DKSET(DKCONFIGURE_ANDROID ../../configure ${DKCONFIGURE_FLAGS})                     # Android
endif()
