# https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

string(ASCII 27 ESC)
set(ColourReset "${ESC}[0m")
set(ColourBold  "${ESC}[1m")

# Regular Colors
set(black        "${ESC}[30;100m")
set(red          "${ESC}[31m")
set(green        "${ESC}[32m")
set(yellow       "${ESC}[33m")
set(blue         "${ESC}[34m")
set(magenta      "${ESC}[35m")
set(cyan         "${ESC}[36m")
set(white        "${ESC}[37m")

# Bold
set(B_black      "${ESC}[1;30m")
set(B_red        "${ESC}[1;31m")
set(B_green      "${ESC}[1;32m")
set(B_yellow     "${ESC}[1;33m")
set(B_blue       "${ESC}[1;34m")
set(B_magenta    "${ESC}[1;35m")
set(B_cyan       "${ESC}[1;36m")
set(B_white      "${ESC}[1;37m")

# High Intensity
set(H_black      "${ESC}[0;90m")
set(H_red        "${ESC}[0;91m")
set(H_green      "${ESC}[0;92m")
set(H_yellow     "${ESC}[0;93m")
set(H_blue       "${ESC}[0;94m")
set(H_magenta    "${ESC}[0;95m")
set(H_cyan       "${ESC}[0;96m")
set(H_white      "${ESC}[0;97m")

# High Intensity Bold
set(HB_black     "${ESC}[1;90m")
set(HB_red       "${ESC}[1;91m")
set(HB_green     "${ESC}[1;92m")
set(HB_yellow    "${ESC}[1;93m")
set(HB_blue      "${ESC}[1;94m")
set(HB_magenta   "${ESC}[1;95m")
set(HB_cyan      "${ESC}[1;96m")
set(HB_white     "${ESC}[1;97m")

# Underline
set(U_black      "${ESC}[4;30;100m")
set(U_red        "${ESC}[4;31m")
set(U_green      "${ESC}[4;32m")
set(U_yellow     "${ESC}[4;33m")
set(U_blue       "${ESC}[4;34m")
set(U_magenta    "${ESC}[4;35m")
set(U_cyan       "${ESC}[4;36m")
set(U_white      "${ESC}[4;37m")

# Background
set(BG_black     "${ESC}[40m")
set(BG_red       "${ESC}[41m")
set(BG_green     "${ESC}[30;42m")
set(BG_yellow    "${ESC}[30;43m")
set(BG_blue      "${ESC}[44m")
set(BG_magenta   "${ESC}[45m")
set(BG_cyan      "${ESC}[30;46m")
set(BG_white     "${ESC}[30;47m")

 # High Intensity background
set(HBG_black    "${ESC}[0;30;100m")
set(HBG_red      "${ESC}[0;30;101m")
set(HBG_green    "${ESC}[0;30;102m")
set(HBG_yellow   "${ESC}[0;30;103m")
set(HBG_blue     "${ESC}[0;30;104m")
set(HBG_magenta  "${ESC}[0;30;105m")
set(HBG_cyan     "${ESC}[0;30;106m")
set(HBG_white    "${ESC}[0;30;107m")


set(ESC_0    "${ESC}[0;37m")
set(ESC_1    "${ESC}[1;37m")
set(ESC_2    "${ESC}[2;37m")
set(ESC_3    "${ESC}[3;37m")
set(ESC_4    "${ESC}[4;37m")
set(ESC_5    "${ESC}[5;37m")
set(ESC_6    "${ESC}[6;37m")
set(ESC_7    "${ESC}[7;37m")
set(ESC_8    "${ESC}[8;37m")
set(ESC_9    "${ESC}[9;37m")
set(ESC_10   "${ESC}[10;37m")
set(ESC_11   "${ESC}[11;37m")
set(ESC_12   "${ESC}[12;37m")
set(ESC_13   "${ESC}[13;37m")
set(ESC_14   "${ESC}[14;37m")
set(ESC_15   "${ESC}[15;37m")
set(ESC_16   "${ESC}[16;37m")
set(ESC_17   "${ESC}[17;37m")
set(ESC_18   "${ESC}[18;37m")
set(ESC_19   "${ESC}[19;37m")
set(ESC_20   "${ESC}[20;37m")

macro(printStyleChart)
	message(" ")
	message(       "Style Chart")
	message(       "${ESC_0}     ESC_0         ${ColourReset}")
	message(       "${ESC_1}     ESC_1         ${ColourReset}")
	message(       "${ESC_2}     ESC_2         ${ColourReset}")
	message(       "${ESC_3}     ESC_3         ${ColourReset}")
	message(       "${ESC_4}     ESC_4         ${ColourReset}")
	message(       "${ESC_5}     ESC_5         ${ColourReset}")
	message(       "${ESC_6}     ESC_6         ${ColourReset}")
	message(       "${ESC_7}     ESC_7         ${ColourReset}")
	message(       "${ESC_8}     ESC_8         ${ColourReset}")
	message(       "${ESC_9}     ESC_9         ${ColourReset}")
	message(      "${ESC_10}     ESC_10        ${ColourReset}")
	message(      "${ESC_11}     ESC_11        ${ColourReset}")
	message(      "${ESC_12}     ESC_12        ${ColourReset}")
	message(      "${ESC_13}     ESC_13        ${ColourReset}")
	message(      "${ESC_14}     ESC_14        ${ColourReset}")
	message(      "${ESC_15}     ESC_15        ${ColourReset}")
	message(      "${ESC_16}     ESC_16        ${ColourReset}")
	message(      "${ESC_17}     ESC_17        ${ColourReset}")
	message(      "${ESC_18}     ESC_18        ${ColourReset}")
	message(      "${ESC_19}     ESC_19        ${ColourReset}")
	message(      "${ESC_20}     ESC_20        ${ColourReset}")
endmacro()

macro(printColorChart)
	message(" ")
	message(      "Regualar")
	message(      "${black}     black          ${ColourReset}")
	message(        "${red}     red            ${ColourReset}")
	message(      "${green}     green          ${ColourReset}")
	message(     "${yellow}     yellow         ${ColourReset}")
	message(       "${blue}     blue           ${ColourReset}")
	message(    "${magenta}     magenta        ${ColourReset}")
	message(       "${cyan}     cyan           ${ColourReset}")
	message(      "${white}     white          ${ColourReset}")
	message(" ")
	message(    "Bold")
	message(    "${B_black}     B_black        ${ColourReset}")
	message(      "${B_red}     B_red          ${ColourReset}")
	message(    "${B_green}     B_green        ${ColourReset}")
	message(   "${B_yellow}     B_yellow       ${ColourReset}")
	message(     "${B_blue}     B_blue         ${ColourReset}")
	message(  "${B_magenta}     B_magenta      ${ColourReset}")
	message(     "${B_cyan}     B_cyan         ${ColourReset}")
	message(    "${B_white}     B_white        ${ColourReset}")
	message(" ")
	message(    "High Intensity")
	message(    "${H_black}     H_black        ${ColourReset}")
	message(      "${H_red}     H_red          ${ColourReset}")
	message(    "${H_green}     H_green        ${ColourReset}")
	message(   "${H_yellow}     H_yellow       ${ColourReset}")
	message(     "${H_blue}     H_blue         ${ColourReset}")
	message(  "${H_magenta}     H_magenta      ${ColourReset}")
	message(     "${H_cyan}     H_cyan         ${ColourReset}")
	message(    "${H_white}     H_white        ${ColourReset}")
	message(" ")
	message(   "High Intensity Bold")
	message(   "${HB_black}     HB_black       ${ColourReset}")
	message(     "${HB_red}     HB_red         ${ColourReset}")
	message(   "${HB_green}     HB_green       ${ColourReset}")
	message(  "${HB_yellow}     HB_yellow      ${ColourReset}")
	message(    "${HB_blue}     HB_blue        ${ColourReset}")
	message( "${HB_magenta}     HB_magenta     ${ColourReset}")
	message(    "${HB_cyan}     HB_cyan        ${ColourReset}")
	message(   "${HB_white}     HB_white       ${ColourReset}")
	message(" ")
	message(    "Underline")
	message(    "${U_black}     U_black        ${ColourReset}")
	message(      "${U_red}     U_red          ${ColourReset}")
	message(    "${U_green}     U_green        ${ColourReset}")
	message(   "${U_yellow}     U_yellow       ${ColourReset}")
	message(     "${U_blue}     U_blue         ${ColourReset}")
	message(  "${U_magenta}     U_magenta      ${ColourReset}")
	message(     "${U_cyan}     U_cyan         ${ColourReset}")
	message(    "${U_white}     U_white        ${ColourReset}")
	message(" ")
	message(   "Background")
	message(   "${BG_black}     BG_black       ${ColourReset}")
	message(     "${BG_red}     BG_red         ${ColourReset}")
	message(   "${BG_green}     BG_green       ${ColourReset}")
	message(  "${BG_yellow}     BG_yellow      ${ColourReset}")
	message(    "${BG_blue}     BG_blue        ${ColourReset}")
	message( "${BG_magenta}     BG_magenta     ${ColourReset}")
	message(    "${BG_cyan}     BG_cyan        ${ColourReset}")
	message(   "${BG_white}     BG_white       ${ColourReset}")
	message(" ")
	message(  "High Intensity Background")
	message(  "${HBG_black}     HBG_black      ${ColourReset}")
	message(    "${HBG_red}     HBG_red        ${ColourReset}")
	message(  "${HBG_green}     HBG_green      ${ColourReset}")
	message( "${HBG_yellow}     HBG_yellow     ${ColourReset}")
	message(   "${HBG_blue}     HBG_blue       ${ColourReset}")
	message("${HBG_magenta}     HBG_magenta    ${ColourReset}")
	message(   "${HBG_cyan}     HBG_cyan       ${ColourReset}")
	message(  "${HBG_white}     HBG_white      ${ColourReset}")
	message(" ")
endmacro()

printColorChart()
printStyleChart()