string(ASCII 27 ESC)
set(ColourReset "${ESC}[m")
set(ColourBold  "${ESC}[1m")
set(Red         "${ESC}[31m")
set(Green       "${ESC}[32m")
set(Yellow      "${ESC}[33m")
set(Blue        "${ESC}[34m")
set(Magenta     "${ESC}[35m")
set(Cyan        "${ESC}[36m")
set(White       "${ESC}[37m")
set(BoldRed     "${ESC}[1;31m")
set(BoldGreen   "${ESC}[1;32m")
set(BoldYellow  "${ESC}[1;33m")
set(BoldBlue    "${ESC}[1;34m")
set(BoldMagenta "${ESC}[1;35m")
set(BoldCyan    "${ESC}[1;36m")
set(BoldWhite   "${ESC}[1;37m")
  
  
message("This is normal")
message("${Red}This is Red${ColourReset}")
message("${Green}This is Green${ColourReset}")
message("${Yellow}This is Yellow${ColourReset}")
message("${Blue}This is Blue${ColourReset}")
message("${Magenta}This is Magenta${ColourReset}")
message("${Cyan}This is Cyan${ColourReset}")
message("${White}This is White${ColourReset}")
message("${BoldRed}This is BoldRed${ColourReset}")
message("${BoldGreen}This is BoldGreen${ColourReset}")
message("${BoldYellow}This is BoldYellow${ColourReset}")
message("${BoldBlue}This is BoldBlue${ColourReset}")
message("${BoldMagenta}This is BoldMagenta${ColourReset}")
message("${BoldCyan}This is BoldCyan${ColourReset}")
message("${BoldWhite}This is BoldWhite\n\n${ColourReset}")