include_guard()

DKDISABLE(tiff)

# DISABLED FOR ALL
DKDISABLE(_TEMPLATE-APP_)
DKDISABLE(_TEMPLATE-LIB_)
DKDISABLE(android-java-tools)
DKDISABLE(astyle)
DKDISABLE(conio.h)
DKDISABLE(DKJerryscript)
DKDISABLE(DKOFWindow)
DKDISABLE(DKOSGAudio)               # Openscenegraph
DKDISABLE(DKOSGCef)                 # Openscenegraph
DKDISABLE(DKOSGLights)              # Openscenegraph
DKDISABLE(DKOSGManipulator)         # Openscenegraph
DKDISABLE(DKOSGModel)               # Openscenegraph
DKDISABLE(DKOSGNotify)              # Openscenegraph
DKDISABLE(DKOSGPhysics)             # Openscenegraph
DKDISABLE(DKOSGPicker)              # Openscenegraph
DKDISABLE(DKOSGRml)                 # Openscenegraph
DKDISABLE(DKOSGStats)               # Openscenegraph
DKDISABLE(DKOSGTerrain)             # Openscenegraph
DKDISABLE(DKOSGVideo)               # Openscenegraph
DKDISABLE(DKOSGViewer)              # Openscenegraph 
DKDISABLE(DKOSGWidget)
DKDISABLE(DKOSGWindow)
DKDISABLE(DKPlugin1)
DKDISABLE(DKPlugin2)
DKDISABLE(DKRestart)
DKDISABLE(DKScreenRecorder)
DKDISABLE(DKSDLAudio)
DKDISABLE(DKSDLWav)
DKDISABLE(DKSDLVideo)
DKDISABLE(DKSFMLRml)               # incomplete
DKDISABLE(DKThread)
DKDISABLE(DKTorrent)
DKDISABLE(DKUpdate)
DKDISABLE(DKVncClient)
DKDISABLE(DKVncServer)
DKDISABLE(emsdk)
DKDISABLE(emsdk-portable)
DKDISABLE(ffmpeg-dev)
DKDISABLE(ffmpeg-shared)
DKDISABLE(ffmpeg-static)
DKDISABLE(gradle)
DKDISABLE(jpeg)                     # using libjpeg_turbo instead
DKDISABLE(libcaca)
DKDISABLE(librocket)                # replaced with RmlUi
DKDISABLE(libvncserver)
DKDISABLE(libvncserver-master-win)
DKDISABLE(libx11)
DKDISABLE(miniweb)
DKDISABLE(notepadpp)
DKDISABLE(openframeworks)
DKDISABLE(openscenegraph)          # Openscenegraph
DKDISABLE(osgaudio)                # Openscenegraph
DKDISABLE(osgbullet)               # Openscenegraph
DKDISABLE(osgworks)                # Openscenegraph
DKDISABLE(sdl2_gif)                # my use SDL_Image animation
DKDISABLE(sdl2_giflib_sa)          # updated version of sdl2_gif
DKDISABLE(simple-getch)            # kept for reference


# Temporarily disabled
DKDISABLE(opencv)  #WORKING, just disabled because it takes so long to compile


if(NOT WIN_HOST) # Disabled on Non-Windows host machines
	DKDISABLE(android-studio)
	DKDISABLE(glintercept)
	DKDISABLE(python)
	DKDISABLE(php-win32-vs16-x64)
	DKDISABLE(vs16-redistributable)
endif()
if(WIN) # Disabled for Windows targets
	DKDISABLE(build-essential)
	#DKDISABLE(bzip2)
	DKDISABLE(DKOcr)
	DKDISABLE(DKWebSockets)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(java)
	DKDISABLE(jerryscript)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(opensles)
	DKDISABLE(podofo)
	DKDISABLE(tesseract)
	DKDISABLE(tiff)
	DKDISABLE(uwebsockets)
	DKDISABLE(waave)
endif()
if(WIN_32) # Disabled for Windows 32bit targets
	#
endif()
if(WIN_64) # Disabled for Windows 64bit targets
	DKDISABLE(java)
	DKDISABLE(smpeg2)
endif()


if(MAC)  # Disabled on Mac host machines
    #DKDISABLE(android-build-tools)
	#DKDISABLE(android-ndk)
	#DKDISABLE(android-platform-tools)
	DKDISABLE(boxer)
	DKDISABLE(build-essential)
	DKDISABLE(bzip2)
	DKDISABLE(DKMySql)
	DKDISABLE(DKOcr)
	DKDISABLE(DKWebSockets)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(java)
	DKDISABLE(JDK8)
	DKDISABLE(JDK11)
	DKDISABLE(jerryscript)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(libuv)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(mlocate)
	DKDISABLE(mobile_core_services)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(smpeg2)
	DKDISABLE(tesseract)
	DKDISABLE(tidy-html5)
	DKDISABLE(tiff)
	DKDISABLE(uwebsockets)
	DKDISABLE(waave)
endif()

if(IOS OR IOSSIM)
	DKDISABLE(agl)
	DKDISABLE(boost)
	DKDISABLE(boxer)
	DKDISABLE(bzip2)
	DKDISABLE(cef_binary)
	#DKDISABLE(DKArchive)
	DKDISABLE(DKCef)
	DKDISABLE(DKCefChild)
	DKDISABLE(DKMidi)
	DKDISABLE(DKMySql)
	DKDISABLE(DKOcr)
	DKDISABLE(DKRmlIframe)
	DKDISABLE(DKSDLCef)
	DKDISABLE(DKWebSockets)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(glew)
	DKDISABLE(imagemagick)
	DKDISABLE(java)
	DKDISABLE(jerryscript)
	#DKDISABLE(libarchive)
	DKDISABLE(libiconv)
	DKDISABLE(libmd)
	DKDISABLE(libpng)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(linusb)
	DKDISABLE(libuv)	
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(mlocate)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(rtmidi)
	DKDISABLE(sdl-gpu)
	#DKDISABLE(sdl2_mixer)
	DKDISABLE(smpeg2)
	DKDISABLE(tesseract)
	DKDISABLE(tidy-html5)
	DKDISABLE(tiff)
	DKDISABLE(uwebsockets)
	DKDISABLE(waave)
endif()


if(NOT LINUX AND NOT RASPBERRY) # Disabled NON Linux targets
	DKDISABLE(build-essential)
	DKDISABLE(kdevelop)
	DKDISABLE(libasound2-dev)
	DKDISABLE(libgl1-mesa-dev)
	DKDISABLE(libglib2.0-dev)
	DKDISABLE(libglu1-mesa-dev)
	DKDISABLE(libgtk2.0-dev)
	DKDISABLE(libsndfile1-dev)
	DKDISABLE(libsystemd-dev)
	DKDISABLE(libudev-dev)
	DKDISABLE(libx11-dev)
	DKDISABLE(libxcursor-dev)
	DKDISABLE(libxrandr-dev)
	DKDISABLE(libxtst-dev)
	DKDISABLE(mesa-common-dev)
endif()
if(LINUX) # Disabled for Linux targets
	DKDISABLE(android-build-tools)
	DKDISABLE(boxer)
	DKDISABLE(DKHook)         # NOTE: this has linux functions too
	DKDISABLE(DKOcr)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKSFMLRml)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKTorrent)
	DKDISABLE(DKWebSockets)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(java)
	DKDISABLE(jdk)
	DKDISABLE(jerryscript)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(sdl-gpu)
	#DKDISABLE(sdl2_mixer)
	DKDISABLE(sfml)           # sfml_sfml-network)  #TODO: disabling individual sublibraries
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(uwebsockets)
	DKDISABLE(upx)
	DKDISABLE(waave)
endif()


if(RASPBERRY) # Disabled for Raspberry Pi targets
	DKDISABLE(android-build-tools)
	DKDISABLE(boxer)
	DKDISABLE(DKHook)           # NOTE: this has linux functions too
	DKDISABLE(DKMidi)
	DKDISABLE(DKOcr)
	DKDISABLE(DKWebSockets)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(java)
	DKDISABLE(jdk)
	DKDISABLE(jerryscript)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(sdl-gpu)
	#DKDISABLE(sdl2_mixer)
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(waave)
endif()


if(ANDROID) # Disabled for Android targets
	DKDISABLE(boxer)
	DKDISABLE(bzip2)
	DKDISABLE(cef_binary)
	DKDISABLE(curl)
	DKDISABLE(cryptopp)
	DKDISABLE(DKCef)
	DKDISABLE(DKCefChild)
	DKDISABLE(DKCurl)
	DKDISABLE(DKWebSockets)
	#DKDISABLE(DKDom)
	DKDISABLE(DKHandles)
	DKDISABLE(DKHook)        # NOTE: this has linux functions too
	DKDISABLE(DKMidi)
	DKDISABLE(DKMySql)
	DKDISABLE(DKOcr)
	#DKDISABLE(DKRml)
	DKDISABLE(DKRmlIframe)
	DKDISABLE(DKSDLCef)
	#DKDISABLE(DKSDLRml)
	#DKDISABLE(DKSDLText)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKWebSockets)
	DKDISABLE(DKWebview)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(glew)
	DKDISABLE(imagemagick)
	DKDISABLE(java)
	DKDISABLE(jdk8)
	DKDISABLE(jdk9)
	DKDISABLE(jerryscript)
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libtorrent)
	DKDISABLE(libiconv)
	DKDISABLE(libogg)
	DKDISABLE(libuv)
	DKDISABLE(libvorbis)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(lua)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(rlottie)
	DKDISABLE(rtmidi)
	DKDISABLE(sdl-gpu)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sfml)
	DKDISABLE(smpeg2)
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(tidy-html5)
	DKDISABLE(tiff)
	DKDISABLE(uwebsockets)
	DKDISABLE(xz)
	DKDISABLE(waave)
endif()
if(ANDROID_64) # Disabled for Android 64bit targets
	DKDISABLE(boost)
endif()
