# DISABLED FOR ALL
DKDISABLE(_TEMPLATE_)
DKDISABLE(DKOSGAudio)
DKDISABLE(DKOSGCef)
DKDISABLE(DKOSGLights)
DKDISABLE(DKOSGManipulator)
DKDISABLE(DKOSGModel)
DKDISABLE(DKOSGNotify)
DKDISABLE(DKOSGPhysics)
DKDISABLE(DKOSGPicker)
DKDISABLE(DKOSGRml)
DKDISABLE(DKOSGStats)
DKDISABLE(DKOSGTerrain)
DKDISABLE(DKOSGVideo)
DKDISABLE(DKOSGViewer)
DKDISABLE(DKOSGWidget)
DKDISABLE(DKOSGWindow)
DKDISABLE(DKSDLText)
DKDISABLE(DKUpdate)
DKDISABLE(sdl2_ttf)


if(NOT CMAKE_HOST_WIN32) # Disabled on Non-Windows host machines
	DKDISABLE(mingw32)
	DKDISABLE(mingw64)
	DKDISABLE(msys)
endif()
if(WIN) # Disabled for Windows targets
	DKDISABLE(android-studio)
	DKDISABLE(DKOcr)
	DKDISABLE(DKOFWindow)
	DKDISABLE(DKPlugin1)
	DKDISABLE(DKPlugin2)
	DKDISABLE(DKScreenRecorder)
	DKDISABLE(DKSDLAudio)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKThread)
	DKDISABLE(DKTorrent)  
	DKDISABLE(DKVncClient)
	DKDISABLE(DKVncServer)
	DKDISABLE(emsdk)
	DKDISABLE(emsdk-portable)
	DKDISABLE(ffmpeg-dev)
	DKDISABLE(ffmpeg-shared)
	DKDISABLE(ffmpeg-static)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(imagemagick)
	DKDISABLE(jpeg) 
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libasound2-dev)
	DKDISABLE(libgl1-mesa-dev)
	DKDISABLE(libgtk2.0-dev)
	DKDISABLE(librocket)
	DKDISABLE(libsystemd-dev)
	DKDISABLE(libtorrent)      
	DKDISABLE(libvncserver-master)
	DKDISABLE(libvncserver-master-win)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libx11-dev)
	DKDISABLE(libxrandr-dev)
	DKDISABLE(libxtst-dev)
	DKDISABLE(lighttpd)
	DKDISABLE(mesa-common-dev)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openframeworks)
	DKDISABLE(openscenegraph)
	DKDISABLE(osgaudio)
	DKDISABLE(osgbullet)
	DKDISABLE(osgworks)
	DKDISABLE(podofo)
	DKDISABLE(sdl2_giflib_sa)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(tesseract)
	DKDISABLE(waave)
	DKDISABLE(xcode)
endif()
if(WIN_32) # Disabled for Windows 32bit targets
	#
endif()
if(WIN_64) # Disabled for Windows 64bit targets
	DKDISABLE(bzip2)
	DKDISABLE(DKWebSockets)
	DKDISABLE(opencv)
	DKDISABLE(smpeg2)
	DKDISABLE(uwebsockets)
endif()



if(CMAKE_HOST_APPLE)  # Disabled on Apple host machines
	DKDISABLE(cmake)
	DKDISABLE(xcode)
endif()



if(CMAKE_HOST_LINUX) # Disabled on Linux host machines
	DKDISABLE(visualstudio)
endif()
if(LINUX) # Disabled for Linux targets
	DKDISABLE(android-build-tools)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKOcr)
	DKDISABLE(DKOFWindow)
	DKDISABLE(DKPlugin1)
	DKDISABLE(DKPlugin2)
	DKDISABLE(DKSDLAudio)
	DKDISABLE(DKSDLText)
	DKDISABLE(DKSDLVideo)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKTorrent)
	DKDISABLE(DKUpdate)
	DKDISABLE(DKVncClient)
	DKDISABLE(DKVncServer) 
	DKDISABLE(DKWebSockets)
	DKDISABLE(emsdk)
	DKDISABLE(emsdk-portable)
	DKDISABLE(ffmpeg-dev)
	DKDISABLE(ffmpeg-shared)
	DKDISABLE(ffmpeg-static)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(jdk)
	DKDISABLE(leptonica)
	DKDISABLE(libogg)
	DKDISABLE(librocket)
	DKDISABLE(libtorrent) 
	DKDISABLE(libvorbis)
	DKDISABLE(libvncserver-master)
	DKDISABLE(libvncserver-master-win)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openframeworks)
	DKDISABLE(openscenegraph)
	DKDISABLE(openssl)
	DKDISABLE(osgaudio)
	DKDISABLE(osgbullet)
	DKDISABLE(osgworks)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(sdl2_giflib_sa)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sdl2_ttf)
	DKDISABLE(sfml)
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(visualstudio)
	DKDISABLE(waave)
	DKDISABLE(xcode)
endif()
if(LINUX_32) # Disabled for Linux 32bit targets
	#
endif()
if(LINUX_64) # Disabled for Linux 64bit targets
	DKDISABLE(DKScreenRecorder)
endif()



if(RASPBERRY) # Disabled for Raspberry Pi targets
	DKDISABLE(android-build-tools)
	DKDISABLE(android-studio)
	DKDISABLE(cef_binary)
	DKDISABLE(DKCef)
	DKDISABLE(DKCefChild)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKOcr)
	DKDISABLE(DKOFWindow)
	DKDISABLE(DKPlugin1)
	DKDISABLE(DKPlugin2)
	DKDISABLE(DKScreenRecorder)
	DKDISABLE(DKSDLAudio)
	DKDISABLE(DKSDLCef)
	DKDISABLE(DKSDLText)
	DKDISABLE(DKSDLVideo)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKTorrent)
	DKDISABLE(DKUpdate)
	DKDISABLE(DKVncClient)
	DKDISABLE(DKVncServer) 
	DKDISABLE(DKWebSockets)
	DKDISABLE(emsdk)
	DKDISABLE(emsdk-portable)
	DKDISABLE(ffmpeg-dev)
	DKDISABLE(ffmpeg-shared)
	DKDISABLE(ffmpeg-static)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(jdk)
	DKDISABLE(leptonica)
	DKDISABLE(libogg)
	DKDISABLE(librocket)
	DKDISABLE(libtorrent) 
	DKDISABLE(libvorbis)
	DKDISABLE(libvncserver-master)
	DKDISABLE(libvncserver-master-win)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openframeworks)
	DKDISABLE(openscenegraph)
	DKDISABLE(openssl)
	DKDISABLE(osgaudio)
	DKDISABLE(osgbullet)
	DKDISABLE(osgworks)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(sdl2_giflib_sa)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sdl2_ttf)
	DKDISABLE(sfml)
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(visualstudio)
	DKDISABLE(waave)
	DKDISABLE(xcode)
endif()
if(RASPBERRY_32) # Disabled for Raspberry Pi 32bit targets
	#
endif()
if(RASPBERRY_64) # Disabled for Raspberry Pi 64bit targets
	#
endif()



if(ANDROID) # Disabled for Android targets
	DKDISABLE(bzip2)
	DKDISABLE(cef_binary)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKOcr)
	DKDISABLE(DKOFWindow)
	DKDISABLE(DKPlugin1)
	DKDISABLE(DKPlugin2)
	DKDISABLE(DKSDLAudio)
	DKDISABLE(DKSDLVideo)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKTorrent)
	DKDISABLE(DKUpdate)
	DKDISABLE(DKVncClient)
	DKDISABLE(DKVncServer) 
	DKDISABLE(DKWebSockets)
	DKDISABLE(emsdk)
	DKDISABLE(emsdk-portable)
	DKDISABLE(ffmpeg-dev)
	DKDISABLE(ffmpeg-shared)
	DKDISABLE(ffmpeg-static)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(giflib)
	DKDISABLE(imagemagick)
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libiconv)
	DKDISABLE(libpng)
	DKDISABLE(librocket)
	DKDISABLE(libtorrent) 
	DKDISABLE(libuv)
	DKDISABLE(libvncserver-master)
	DKDISABLE(libvncserver-master-win)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(opencv)
	DKDISABLE(openframeworks)
	DKDISABLE(openscenegraph)
	DKDISABLE(osgaudio)
	DKDISABLE(osgbullet)
	DKDISABLE(osgworks)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(rmlui)
	DKDISABLE(sdl2_giflib_sa)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sfml)
	DKDISABLE(smpeg2)
	DKDISABLE(stackwalker)
	DKDISABLE(tesseract)
	DKDISABLE(tidy-html5)
	DKDISABLE(uwebsockets)
	DKDISABLE(waave)
	DKDISABLE(xcode)
	DKDISABLE(xz)
endif()
if(ANDROID_32) # Disabled for Android 32bit targets
	#
endif()
if(ANDROID_64) # Disabled for Android 64bit targets
	#
endif()
