# DISABLED FOR ALL
DKDISABLE(_TEMPLATE_)
DKDISABLE(android-studio)
DKDISABLE(conio.h)
#DKDISABLE(DKCefChild)
DKDISABLE(DKJerryscript)
DKDISABLE(DKOFWindow)
DKDISABLE(DKOSGAudio)
DKDISABLE(DKOSGCef)
DKDISABLE(DKOSGLights)
DKDISABLE(DKOSGManipulator)
DKDISABLE(DKOSGModel)
DKDISABLE(DKOSGNotify)
DKDISABLE(DKOSGPhysics)
DKDISABLE(DKOSGPicker)
DKDISABLE(DKOSGRml)
DKDISABLE(DKOSGStats)
DKDISABLE(DKOSGTerrain)
DKDISABLE(DKOSGVideo)
DKDISABLE(DKOSGViewer)
DKDISABLE(DKOSGWidget)
DKDISABLE(DKOSGWindow)
DKDISABLE(DKPlugin1)
DKDISABLE(DKPlugin2)
DKDISABLE(DKRestart)
DKDISABLE(DKScreenRecorder)
DKDISABLE(DKSDLAudio)
DKDISABLE(DKSDLWav)
DKDISABLE(DKSDLVideo)
DKDISABLE(DKThread)
DKDISABLE(DKTorrent)
DKDISABLE(DKUpdate)
DKDISABLE(DKVncClient)
DKDISABLE(DKVncServer)
DKDISABLE(emsdk)
DKDISABLE(emsdk-portable)
DKDISABLE(ffmpeg-dev)
DKDISABLE(ffmpeg-shared)
DKDISABLE(ffmpeg-static)
DKDISABLE(jerryscript)
DKDISABLE(libcaca)
DKDISABLE(librocket)
DKDISABLE(libtorrent)
DKDISABLE(libvncserver-master)
DKDISABLE(libvncserver-master-win)
DKDISABLE(lua)
DKDISABLE(ncurses)
DKDISABLE(openframeworks)
DKDISABLE(openscenegraph)
DKDISABLE(osgaudio)
DKDISABLE(osgbullet)
DKDISABLE(osgworks)
DKDISABLE(sdl2_giflib_sa)
DKDISABLE(tesseract)
DKDISABLE(waave)



if(NOT CMAKE_HOST_WIN32) # Disabled on Non-Windows host machines
	DKDISABLE(glew)
	DKDISABLE(mingw32)
	DKDISABLE(mingw64)
	DKDISABLE(msys)
	DKDISABLE(python)
	DKDISABLE(php-win32-vs16-x64)
endif()
if(WIN) # Disabled for Windows targets
	#DKDISABLE(bzip2)
	DKDISABLE(DKOcr)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	#DKDISABLE(imagemagick)
	DKDISABLE(jpeg) 
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libasound2-dev)
	DKDISABLE(libgl1-mesa-dev)
	DKDISABLE(libgtk2.0-dev)
	DKDISABLE(libsystemd-dev)     
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libx11-dev)
	DKDISABLE(libxrandr-dev)
	DKDISABLE(libxtst-dev)
	DKDISABLE(lighttpd)
	DKDISABLE(mesa-common-dev)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(podofo)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(xcode)
endif()
if(WIN_32) # Disabled for Windows 32bit targets
	#
endif()
if(WIN_64) # Disabled for Windows 64bit targets
	#DKDISABLE(bzip2)
	DKDISABLE(DKWebSockets)
	DKDISABLE(opencv)
	DKDISABLE(smpeg2)
	DKDISABLE(uwebsockets)
endif()



if(CMAKE_HOST_APPLE)  # Disabled on Apple host machines
    DKDISABLE(android-build-tools)
	DKDISABLE(android-ndk)
	DKDISABLE(android-platform-tools)
	DKDISABLE(boxer)
	DKDISABLE(bzip2)
	#DKDISABLE(DKCefChild)
	DKDISABLE(DKMySql)
	DKDISABLE(DKOcr)
	DKDISABLE(DKWebSockets)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(jpeg) 
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libasound2-dev)
	DKDISABLE(libgl1-mesa-dev)
	DKDISABLE(libgtk2.0-dev)
	DKDISABLE(libsystemd-dev)
	DKDISABLE(libtorrent)
	DKDISABLE(libuv)	
	DKDISABLE(libvorbis)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libx11-dev)
	DKDISABLE(libxml2)
	DKDISABLE(libxrandr-dev)
	DKDISABLE(libxtst-dev)
	DKDISABLE(lighttpd)
	DKDISABLE(mesa-common-dev)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(opencv)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	#DKDISABLE(sdl2_gif)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(tidy-html5)
	DKDISABLE(tiff)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(visualstudio)
endif()



if(CMAKE_HOST_LINUX) # Disabled on Linux host machines
	DKDISABLE(visualstudio)
endif()
if(LINUX) # Disabled for Linux targets
	DKDISABLE(android-build-tools)
	DKDISABLE(boxer)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKOcr)
	DKDISABLE(DKSDLWav)
	DKDISABLE(DKSDLText)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKTorrent)
	DKDISABLE(DKWebSockets)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(jdk)
	DKDISABLE(leptonica)
	DKDISABLE(libogg)
	DKDISABLE(libvorbis)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sdl2_ttf)
	DKDISABLE(sfml)
	DKDISABLE(stackwalker)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(visualstudio)
	DKDISABLE(xcode)
endif()
if(LINUX_32) # Disabled for Linux 32bit targets
	#
endif()
if(LINUX_64) # Disabled for Linux 64bit targets
	#
endif()



if(RASPBERRY) # Disabled for Raspberry Pi targets
	DKDISABLE(android-build-tools)
	DKDISABLE(boxer)
	DKDISABLE(cef_binary)
	DKDISABLE(DKCef)
	DKDISABLE(DKCefChild)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKMidi)
	DKDISABLE(DKOcr)
	DKDISABLE(DKSDLCef)
	DKDISABLE(DKSDLText)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKWebSockets)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(ghostscript)
	DKDISABLE(imagemagick)
	DKDISABLE(jdk)
	DKDISABLE(leptonica)
	DKDISABLE(libogg)
	DKDISABLE(libvorbis)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libxml2)
	DKDISABLE(lighttpd)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sdl2_ttf)
	DKDISABLE(sfml)
	DKDISABLE(stackwalker)
	DKDISABLE(upx)
	DKDISABLE(uwebsockets)
	DKDISABLE(visualstudio)
	DKDISABLE(xcode)
endif()
if(RASPBERRY_32) # Disabled for Raspberry Pi 32bit targets
	#
endif()
if(RASPBERRY_64) # Disabled for Raspberry Pi 64bit targets
	#
endif()



if(ANDROID) # Disabled for Android targets
	DKDISABLE(boxer)
	DKDISABLE(bzip2)
	DKDISABLE(cef_binary)
	DKDISABLE(curl)
	DKDISABLE(DKCef)
	DKDISABLE(DKCefChild)
	DKDISABLE(DKCurl)
	DKDISABLE(DKDom)
	DKDISABLE(DKHook) #NOTE: this has linux functions too
	DKDISABLE(DKMySql)
	DKDISABLE(DKOcr)
	DKDISABLE(DKRml)
	DKDISABLE(DKRmlIframe)
	DKDISABLE(DKSDLRml)
	DKDISABLE(DKSFMLRml)
	DKDISABLE(DKSFMLWindow)
	DKDISABLE(DKWebSockets)
	DKDISABLE(DKWebview)
	DKDISABLE(flac)
	DKDISABLE(freealut)
	DKDISABLE(freealut-master)
	DKDISABLE(giflib)
	DKDISABLE(imagemagick)
	DKDISABLE(jpeg)
	DKDISABLE(kdevelop)
	DKDISABLE(leptonica)
	DKDISABLE(libasound2-dev)
	DKDISABLE(libgl1-mesa-dev)
	DKDISABLE(libgtk2.0-dev)
	DKDISABLE(libiconv)
	DKDISABLE(libogg)
	DKDISABLE(libpng)
	DKDISABLE(libsystemd-dev)
	DKDISABLE(libuv)
	DKDISABLE(libvorbis)
	DKDISABLE(libxrandr-dev)
	DKDISABLE(libwebp)
	DKDISABLE(libwebsockets)
	DKDISABLE(libx11-dev)
	DKDISABLE(libxml2)
	DKDISABLE(libxtst-dev)
	DKDISABLE(lighttpd)
	DKDISABLE(mesa-common-dev)
	DKDISABLE(openal)
	DKDISABLE(openal-android)
	DKDISABLE(opencv)
	DKDISABLE(openssl)
	DKDISABLE(podofo)
	DKDISABLE(python)
	DKDISABLE(rlottie)
	DKDISABLE(rmlui)
	DKDISABLE(sdl2_gif)
	DKDISABLE(sdl2_mixer)
	DKDISABLE(sfml)
	DKDISABLE(smpeg2)
	DKDISABLE(stackwalker)
	DKDISABLE(tidy-html5)
	DKDISABLE(uwebsockets)
	DKDISABLE(xcode)
	DKDISABLE(xz)
endif()
if(ANDROID_32) # Disabled for Android 32bit targets
	#
endif()
if(ANDROID_64) # Disabled for Android 64bit targets
	#
endif()
