if(ANDROID)
	RETURN()
endif()
if(LINUX)
	##RETURN()
endif()

##dk_depend(libwebsockets)
##dk_depend(uwebsockets)
dk_depend(uwebsockets)
if(HAVE_DKDuktape)
	dk_depend(DKDuktape)
endif()
if(HAVE_DKCef)
	dk_depend(DKCef)
endif()


dk_generateCmake(DKWebSockets)
dk_assets(DKWebSockets)