dk_enable(HAVE_DKCef) ##FIXME: Find a way to remove this requirement

dk_depend(DK)
dk_depend(DKAssets)
dk_depend(DKDebug)
dk_depend(DKDom)
dk_depend(DKDuktape)
dk_depend(DKDuktapeDom)
dk_depend(DKFile)
dk_depend(DKGui)
dk_depend(DKRml)
dk_depend(DKRmlIframe)
dk_depend(DKSdlCef)
dk_depend(DKSdlRml)
dk_depend(DKSdlText)
dk_depend(DKSdlWindow)
dk_depend(DKWebTest)
dk_depend(DKWidget)
dk_depend(DKWindow)
