dk_depend(openscenegraph)

# osgCore
#dk_depend(openscenegraph OpenThreads)
#dk_depend(openscenegraph osg)
#dk_depend(openscenegraph osgUtil)
#dk_depend(openscenegraph osgDB)
#dk_depend(openscenegraph osgGA)
#dk_depend(openscenegraph osgText)
#dk_depend(openscenegraph osgViewer)
#dk_depend(openscenegraph osgAnimation)
#dk_depend(openscenegraph osgFX)
#dk_depend(openscenegraph osgManipulator)
#dk_depend(openscenegraph osgParticle)
#dk_depend(openscenegraph osgShadow)
#dk_depend(openscenegraph osgSim)
#dk_depend(openscenegraph osgTerrain)
#dk_depend(openscenegraph osgVolume)
#dk_depend(openscenegraph osgWidget)

# osgWrappers
#dk_depend(openscenegraph osgdb_deprecated_osg)
#dk_depend(openscenegraph osgdb_deprecated_osganimation)
#dk_depend(openscenegraph osgdb_deprecated_osgfx)
#dk_depend(openscenegraph osgdb_deprecated_osgparticle)
#dk_depend(openscenegraph osgdb_deprecated_osgshadow)
#dk_depend(openscenegraph osgdb_deprecated_osgsim)
#dk_depend(openscenegraph osgdb_deprecated_osgterrain)
#dk_depend(openscenegraph osgdb_deprecated_osgtext)
#dk_depend(openscenegraph osgdb_deprecated_osgviewer)
#dk_depend(openscenegraph osgdb_deprecated_osgvolume)
#dk_depend(openscenegraph osgdb_deprecated_osgwidget)

# osgPlugins
#dk_depend(openscenegraph osgdb_freetype)
#dk_depend(openscenegraph osgdb_ive)
#dk_depend(openscenegraph osgdb_openflight)
#dk_depend(openscenegraph osgdb_osg)
#dk_depend(openscenegraph osgdb_rgb)

# osgSerializers
#dk_depend(openscenegraph osgdb_serializers_osg)
#dk_depend(openscenegraph osgdb_serializers_osganimation)
#dk_depend(openscenegraph osgdb_serializers_osgfx)
#dk_depend(openscenegraph osgdb_serializers_osgmanipulator)
#dk_depend(openscenegraph osgdb_serializers_osgparticle)
#dk_depend(openscenegraph osgdb_serializers_osgshadow)
#dk_depend(openscenegraph osgdb_serializers_osgsim)
#dk_depend(openscenegraph osgdb_serializers_osgterrain)
#dk_depend(openscenegraph osgdb_serializers_osgtext)
#dk_depend(openscenegraph osgdb_serializers_osgvolume)

# osgCore (continued)
#dk_depend(openscenegraph osgUl)
#dk_depend(openscenegraph osgPresentation)

# osgPlugins (continued)
#dk_depend(openscenegraph osgdb_3dc)
#dk_depend(openscenegraph osgdb_3ds)
#dk_depend(openscenegraph osgdb_ac)
#dk_depend(openscenegraph osgdb_bmp)
#dk_depend(openscenegraph osgdb_bsp)
#dk_depend(openscenegraph osgdb_bvh)
#dk_depend(openscenegraph osgdb_cfg)
#dk_depend(openscenegraph osgdb_curl)
#dk_depend(openscenegraph osgdb_dds)
#dk_depend(openscenegraph osgdb_dot)
#dk_depend(openscenegraph osgdb_dxf)
#dk_depend(openscenegraph osgdb_gles)
#dk_depend(openscenegraph osgdb_glsl)
#dk_depend(openscenegraph osgdb_gz)
#dk_depend(openscenegraph osgdb_hdr)
#dk_depend(openscenegraph osgdb_jpeg)
#dk_depend(openscenegraph osgdb_ktx)
#dk_depend(openscenegraph osgdb_logo)
#dk_depend(openscenegraph osgdb_lua)
#dk_depend(openscenegraph osgdb_lwo)
#dk_depend(openscenegraph osgdb_lws)
#dk_depend(openscenegraph osgdb_md2)
#dk_depend(openscenegraph osgdb_mdl)
#dk_depend(openscenegraph osgdb_normals)
#dk_depend(openscenegraph osgdb_obj)
#dk_depend(openscenegraph osgdb_osc)
#dk_depend(openscenegraph osgdb_osga)
#dk_depend(openscenegraph osgdb_osgjs)
#dk_depend(openscenegraph osgdb_osgshadow)
#dk_depend(openscenegraph osgdb_osgterrain)
#dk_depend(openscenegraph osgdb_osgtgz)
#dk_depend(openscenegraph osgdb_osgviewer)
#dk_depend(openscenegraph osgdb_p3d)
#dk_depend(openscenegraph osgdb_pic)
#dk_depend(openscenegraph osgdb_ply)
#dk_depend(openscenegraph osgdb_png)
#dk_depend(openscenegraph osgdb_pnm)
#dk_depend(openscenegraph osgdb_pov)
#dk_depend(openscenegraph osgdb_pvr)
#dk_depend(openscenegraph osgdb_revisions)
#dk_depend(openscenegraph osgdb_rot)
#dk_depend(openscenegraph osgdb_scale)

# osgSerializers (continued)
#dk_depend(openscenegraph osgdb_serializers_osgga)
#dk_depend(openscenegraph osgdb_serializers_osggui)
#dk_depend(openscenegraph osgdb_serializers_osgutil)
#dk_depend(openscenegraph osgdb_serializers_osgviewer)
	
# osgPlugins (continued)
#dk_depend(openscenegraph osgdb_shp)
#dk_depend(openscenegraph osgdb_stl)
#dk_depend(openscenegraph osgdb_tf)
#dk_depend(openscenegraph osgdb_tga)
#dk_depend(openscenegraph osgdb_tgz)
#dk_depend(openscenegraph osgdb_tiff)
#dk_depend(openscenegraph osgdb_trans)
#dk_depend(openscenegraph osgdb_trk)
#dk_depend(openscenegraph osgdb_txf)
#dk_depend(openscenegraph osgdb_txp)
#dk_depend(openscenegraph osgdb_vnc)
#dk_depend(openscenegraph osgdb_vtf)
#dk_depend(openscenegraph osgdb_x)
#dk_depend(openscenegraph osgdb_zip)


dk_generateCmake(DKOSGViewer)
