<<<<<<< HEAD
=======
///$(which true);FLAGS="-g -Wall -Wextra --std=c17 -O1 -fsanitize=address,undefined";THIS_FILE="$(cd "$(dirname "$0")"; pwd -P)/$(basename "$0")";OUT_FILE="tmp/build-cache/$THIS_FILE";mkdir -p "$(dirname "$OUT_FILE")";test "$THIS_FILE" -ot "$OUT_FILE" || $(which clang || which gcc) $FLAGS "$THIS_FILE" -o "$OUT_FILE" || exit $?;exec bash -c "exec -a \"$0\" \"$OUT_FILE\" $([ $# -eq 0 ] || printf ' "%s"' "$@")"

>>>>>>> Development
#include "dk_color.h"
#include "dk_echo.h"

//###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
<<<<<<< HEAD
#ifdef DKTEST
int main() {
    dk_echo("\n");

	printf("0    clr          %s      clr            \n%s", clr,  clr);
    printf("1    bold         %s      bold           \n%s", bold, clr);
/*  dk_echo("2    dim          "+ dim                 +"      dim            \n"+clr);
    dk_echo("3    italic       "+ italic              +"      italic         \n"+clr);
    dk_echo("4    underline    "+ underline           +"      underline      \n"+clr);
    dk_echo("5    blink        "+ blink               +"      blink          \n"+clr);
    dk_echo("6    fblink       "+ fblink              +"      fblink         \n"+clr);
    dk_echo("7    negative     "+ negative            +"      negative       \n"+clr);
    dk_echo("8    invisible    "+ invisible           +"      invisible      \n"+clr);
    dk_echo("9    strike       "+ strike              +"      strike         \n"+clr);
    dk_echo("10   ANSI10       "+ ANSI10              +"      UNKNOWN        \n"+clr);
    dk_echo("11   ANSI11       "+ ANSI11              +"      UNKNOWN        \n"+clr);
    dk_echo("12   ANSI12       "+ ANSI12              +"      UNKNOWN        \n"+clr);
    dk_echo("13   ANSI13       "+ ANSI13              +"      UNKNOWN        \n"+clr);
    dk_echo("14   ANSI14       "+ ANSI14              +"      UNKNOWN        \n"+clr);
    dk_echo("15   ANSI15       "+ ANSI15              +"      UNKNOWN        \n"+clr);
    dk_echo("16   ANSI16       "+ ANSI16              +"      UNKNOWN        \n"+clr);
    dk_echo("17   ANSI17       "+ ANSI17              +"      UNKNOWN        \n"+clr);
    dk_echo("18   ANSI18       "+ ANSI18              +"      UNKNOWN        \n"+clr);
    dk_echo("19   ANSI19       "+ ANSI19              +"      UNKNOWN        \n"+clr);
    dk_echo("20   ANSI20       "+ ANSI20              +"      UNKNOWN        \n"+clr);
    dk_echo("21   ANSI21       "+ ANSI21              +"      UNKNOWN        \n"+clr);
    dk_echo("22   nobold       "+ nobold              +"      nobold         \n"+clr);
    dk_echo("23   noitalic     "+ noitalic            +"      noitalic       \n"+clr);
    dk_echo("24   nounderline  "+ nounderline         +"      nounderline    \n"+clr);
    dk_echo("25   noblink      "+ noblink             +"      noblink        \n"+clr);
    dk_echo("26   ANSI26       "+ ANSI26              +"      UNKNOWN        \n"+clr);
    dk_echo("27   nonegative   "+ nonegative          +"      nonegative     \n"+clr);
    dk_echo("28   visible      "+ visible             +"      visible        \n"+clr);
    dk_echo("29   nostrike     "+ nostrike            +"      nostrike       \n"+clr);
    dk_echo("30   black        "+ black + bg_lblack   +"      black          \n"+clr);
    dk_echo("31   red          "+ red                 +"      red            \n"+clr);
    dk_echo("32   green        "+ green               +"      green          \n"+clr);
    dk_echo("33   yellow       "+ yellow              +"      yellow         \n"+clr);
    dk_echo("34   blue         "+ blue                +"      blue           \n"+clr);
    dk_echo("35   magenta      "+ magenta             +"      magenta        \n"+clr);
    dk_echo("36   cyan         "+ cyan                +"      cyan           \n"+clr);
    dk_echo("37   white        "+ white               +"      white          \n"+clr);
    dk_echo("38   RGB          "+ RGB                 +"      RGB            \n"+clr);
    dk_echo("39   default_     "+ default_            +"      default_       \n"+clr);
    dk_echo("40   bg_black     "+ bg_black   + white  +"      bg_black       \n"+clr);
    dk_echo("41   bg_red       "+ bg_red     + black  +"      bg_red         \n"+clr);
    dk_echo("42   bg_green     "+ bg_green   + black  +"      bg_green       \n"+clr);
    dk_echo("43   bg_yellow    "+ bg_yellow  + black  +"      bg_yellow      \n"+clr);
    dk_echo("44   bg_blue      "+ bg_blue    + black  +"      bg_blue        \n"+clr);
    dk_echo("45   bg_magenta   "+ bg_magenta + black  +"      bg_magenta     \n"+clr);
    dk_echo("46   bg_cyan      "+ bg_cyan    + black  +"      bg_cyan        \n"+clr);
    dk_echo("47   bg_white     "+ bg_white   + black  +"      bg_white       \n"+clr);
    dk_echo("48   bg_RGB       "+ bg_RGB     + black  +"      bg_RGB         \n"+clr);
    dk_echo("49   bg_default   "+ bg_default + white  +"      bg_default     \n"+clr);
    dk_echo("50   ANSI50       "+ ANSI50              +"      UNKNOWN        \n"+clr);
    dk_echo("51   ANSI51       "+ ANSI51              +"      UNKNOWN        \n"+clr);
    dk_echo("52   ANSI52       "+ ANSI52              +"      UNKNOWN        \n"+clr);
    dk_echo("53   ANSI53       "+ ANSI53              +"      UNKNOWN        \n"+clr);
    dk_echo("54   ANSI54       "+ ANSI54              +"      UNKNOWN        \n"+clr);
    dk_echo("55   ANSI55       "+ ANSI55              +"      UNKNOWN        \n"+clr);
    dk_echo("56   ANSI56       "+ ANSI56              +"      UNKNOWN        \n"+clr);
    dk_echo("57   ANSI57       "+ ANSI57              +"      UNKNOWN        \n"+clr);
    dk_echo("58   ANSI58       "+ ANSI58              +"      UNKNOWN        \n"+clr);
    dk_echo("59   ANSI59       "+ ANSI59              +"      UNKNOWN        \n"+clr);
    dk_echo("60   ANSI60       "+ ANSI60              +"      UNKNOWN        \n"+clr);
    dk_echo("61   ANSI61       "+ ANSI61              +"      UNKNOWN        \n"+clr);
    dk_echo("62   ANSI62       "+ ANSI62              +"      UNKNOWN        \n"+clr);
    dk_echo("63   ANSI63       "+ ANSI63              +"      UNKNOWN        \n"+clr);
    dk_echo("64   ANSI64       "+ ANSI64              +"      UNKNOWN        \n"+clr);
    dk_echo("65   ANSI65       "+ ANSI65              +"      UNKNOWN        \n"+clr);
    dk_echo("66   ANSI66       "+ ANSI66              +"      UNKNOWN        \n"+clr);
    dk_echo("67   ANSI67       "+ ANSI67              +"      UNKNOWN        \n"+clr);
    dk_echo("68   ANSI68       "+ ANSI68              +"      UNKNOWN        \n"+clr);
    dk_echo("69   ANSI69       "+ ANSI69              +"      UNKNOWN        \n"+clr);
    dk_echo("70   ANSI70       "+ ANSI70              +"      UNKNOWN        \n"+clr);
    dk_echo("71   ANSI71       "+ ANSI71              +"      UNKNOWN        \n"+clr);
    dk_echo("72   ANSI72       "+ ANSI72              +"      UNKNOWN        \n"+clr);
    dk_echo("73   ANSI73       "+ ANSI73              +"      UNKNOWN        \n"+clr);
    dk_echo("74   ANSI74       "+ ANSI74              +"      UNKNOWN        \n"+clr);
    dk_echo("75   ANSI75       "+ ANSI75              +"      UNKNOWN        \n"+clr);
    dk_echo("76   ANSI76       "+ ANSI76              +"      UNKNOWN        \n"+clr);
    dk_echo("77   ANSI77       "+ ANSI77              +"      UNKNOWN        \n"+clr);
    dk_echo("78   ANSI78       "+ ANSI78              +"      UNKNOWN        \n"+clr);
    dk_echo("79   ANSI79       "+ ANSI79              +"      UNKNOWN        \n"+clr);
    dk_echo("80   ANSI80       "+ ANSI80              +"      UNKNOWN        \n"+clr);
    dk_echo("81   ANSI81       "+ ANSI81              +"      UNKNOWN        \n"+clr);
    dk_echo("82   ANSI82       "+ ANSI82              +"      UNKNOWN        \n"+clr);
    dk_echo("83   ANSI83       "+ ANSI83              +"      UNKNOWN        \n"+clr);
    dk_echo("84   ANSI84       "+ ANSI84              +"      UNKNOWN        \n"+clr);
    dk_echo("85   ANSI85       "+ ANSI85              +"      UNKNOWN        \n"+clr);
    dk_echo("86   ANSI86       "+ ANSI86              +"      UNKNOWN        \n"+clr);
    dk_echo("87   ANSI87       "+ ANSI87              +"      UNKNOWN        \n"+clr);
    dk_echo("88   ANSI88       "+ ANSI88              +"      UNKNOWN        \n"+clr);
    dk_echo("89   ANSI89       "+ ANSI89              +"      UNKNOWN        \n"+clr);
    dk_echo("90   lblack       "+ lblack              +"      lblack         \n"+clr);
    dk_echo("91   lred         "+ lred                +"      lred           \n"+clr);
    dk_echo("92   lgreen       "+ lgreen              +"      lgreen         \n"+clr);
    dk_echo("93   lyellow      "+ lyellow             +"      lyellow        \n"+clr);
    dk_echo("94   lblue        "+ lblue               +"      lblue          \n"+clr);
    dk_echo("95   lmagenta     "+ lmagenta            +"      lmagenta       \n"+clr);
    dk_echo("96   lcyan        "+ lcyan               +"      lcyan          \n"+clr);
    dk_echo("97   lwhite       "+ lwhite              +"      lwhite         \n"+clr);
    dk_echo("98   ANSI98       "+ ANSI98              +"      UNKNOWN        \n"+clr);
    dk_echo("99   ANSI99       "+ ANSI99              +"      UNKNOWN        \n"+clr);
    dk_echo("100  bg_lblack    "+ bg_lblack   + black +"      bg_lblack      \n"+clr);
    dk_echo("101  bg_lred      "+ bg_lred     + black +"      bg_lred        \n"+clr);
    dk_echo("102  bg_lgreen    "+ bg_lgreen   + black +"      bg_lgreen      \n"+clr);
    dk_echo("103  bg_lyellow   "+ bg_lyellow  + black +"      bg_lyellow     \n"+clr);
    dk_echo("104  bg_lblue     "+ bg_lblue    + black +"      bg_lblue       \n"+clr);
    dk_echo("105  bg_lmagenta  "+ bg_lmagenta + black +"      bg_lmagenta    \n"+clr);
    dk_echo("106  bg_lcyan     "+ bg_lcyan    + black +"      bg_lcyan       \n"+clr);
    dk_echo("107  bg_lwhite    "+ bg_lwhite   + black +"      bg_lwhite      \n"+clr);
    dk_echo("108  ANSI108      "+ ANSI108             +"      UNKNOWN        \n"+clr);
    dk_echo("109  ANSI109      "+ ANSI109             +"      UNKNOWN        \n"+clr);
    dk_echo("110  ANSI110      "+ ANSI110             +"      UNKNOWN        \n"+clr);
    dk_echo("111  ANSI111      "+ ANSI111             +"      UNKNOWN        \n"+clr);
    dk_echo("112  ANSI112      "+ ANSI112             +"      UNKNOWN        \n"+clr);
    dk_echo("113  ANSI113      "+ ANSI113             +"      UNKNOWN        \n"+clr);
    dk_echo("114  ANSI114      "+ ANSI114             +"      UNKNOWN        \n"+clr);
    dk_echo("115  ANSI115      "+ ANSI115             +"      UNKNOWN        \n"+clr);
    dk_echo("116  ANSI116      "+ ANSI116             +"      UNKNOWN        \n"+clr);
    dk_echo("117  ANSI117      "+ ANSI117             +"      UNKNOWN        \n"+clr);
    dk_echo("118  ANSI118      "+ ANSI118             +"      UNKNOWN        \n"+clr);
    dk_echo("119  ANSI119      "+ ANSI119             +"      UNKNOWN        \n"+clr);
    dk_echo("120  ANSI120      "+ ANSI120             +"      UNKNOWN        \n"+clr);
    dk_echo("121  ANSI121      "+ ANSI121             +"      UNKNOWN        \n"+clr);
    dk_echo("122  ANSI122      "+ ANSI122             +"      UNKNOWN        \n"+clr);
    dk_echo("123  ANSI123      "+ ANSI123             +"      UNKNOWN        \n"+clr);
    dk_echo("124  ANSI124      "+ ANSI124             +"      UNKNOWN        \n"+clr);

    dk_echo(RGB+"255;10;10m    RGB test (255;0;10)    \n"+clr);
    dk_echo(RGB+"10;255;10m    RGB test (0;255;10)    \n"+clr);
    dk_echo(RGB+"0;0;255m    RGB test (0;0;255)     \n"+clr);
    dk_echo(RGB+"0;0;250m    RGB test (0;0;250)     \n"+clr);
    dk_echo(RGB+"0;0;245m    RGB test (0;0;245)     \n"+clr);
    dk_echo(RGB+"0;0;240m    RGB test (0;0;240)     \n"+clr);
    dk_echo(RGB+"0;0;235m    RGB test (0;0;235)     \n"+clr);
    dk_echo(RGB+"0;0;230m    RGB test (0;0;230)     \n"+clr);
    dk_echo(RGB+"0;0;225m    RGB test (0;0;225)     \n"+clr);
    dk_echo(RGB+"0;0;220m    RGB test (0;0;220)     \n"+clr);
    dk_echo(RGB+"0;0;215m    RGB test (0;0;215)     \n"+clr);
    dk_echo(RGB+"0;0;210m    RGB test (0;0;210)     \n"+clr);
    dk_echo(RGB+"0;0;205m    RGB test (0;0;205)     \n"+clr);
    dk_echo(RGB+"0;0;200m    RGB test (0;0;200)     \n"+clr);
    dk_echo(RGB+"0;0;195m    RGB test (0;0;195)     \n"+clr);
    dk_echo(RGB+"0;0;190m    RGB test (0;0;190)     \n"+clr);
    dk_echo(RGB+"0;0;185m    RGB test (0;0;185)     \n"+clr);
    dk_echo(RGB+"0;0;180m    RGB test (0;0;180)     \n"+clr);
    dk_echo(RGB+"0;0;175m    RGB test (0;0;175)     \n"+clr);
    dk_echo(RGB+"0;0;170m    RGB test (0;0;170)     \n"+clr);
    dk_echo(RGB+"0;0;165m    RGB test (0;0;165)     \n"+clr);
    dk_echo(RGB+"0;0;160m    RGB test (0;0;160)     \n"+clr);
    dk_echo(RGB+"0;0;155m    RGB test (0;0;155)     \n"+clr);
    dk_echo(RGB+"0;0;150m    RGB test (0;0;150)     \n"+clr);
    dk_echo(RGB+"0;0;145m    RGB test (0;0;145)     \n"+clr);
    dk_echo(RGB+"0;0;140m    RGB test (0;0;140)     \n"+clr);
    dk_echo(RGB+"0;0;135m    RGB test (0;0;135)     \n"+clr);
    dk_echo(RGB+"0;0;130m    RGB test (0;0;130)     \n"+clr);
    dk_echo(RGB+"0;0;125m    RGB test (0;0;125)     \n"+clr);
    dk_echo(RGB+"0;0;120m    RGB test (0;0;120)     \n"+clr);
    dk_echo(RGB+"0;0;115m    RGB test (0;0;115)     \n"+clr);
    dk_echo(RGB+"0;0;110m    RGB test (0;0;110)     \n"+clr);
    dk_echo(RGB+"0;0;105m    RGB test (0;0;105)     \n"+clr);
    dk_echo(RGB+"0;0;100m    RGB test (0;0;100)     \n"+clr);
    dk_echo(RGB+"0;0;95m    RGB test (0;0;95)      \n"+clr);
    dk_echo(RGB+"0;0;90m    RGB test (0;0;90)      \n"+clr);
    dk_echo(RGB+"0;0;85m    RGB test (0;0;85)      \n"+clr);
    dk_echo(RGB+"0;0;80m    RGB test (0;0;80)      \n"+clr);
    dk_echo(RGB+"0;0;75m    RGB test (0;0;75)      \n"+clr);
    dk_echo(RGB+"0;0;70m    RGB test (0;0;70)      \n"+clr);
    dk_echo(RGB+"0;0;65m    RGB test (0;0;65)      \n"+clr);
    dk_echo(RGB+"0;0;60m    RGB test (0;0;60)      \n"+clr);
    dk_echo(RGB+"0;0;55m    RGB test (0;0;55)      \n"+clr);
    dk_echo(RGB+"0;0;50m    RGB test (0;0;50)      \n"+clr);
    dk_echo(RGB+"0;0;45m    RGB test (0;0;45)      \n"+clr);
    dk_echo(RGB+"0;0;40m    RGB test (0;0;40)      \n"+clr);
    dk_echo(RGB+"0;0;35m    RGB test (0;0;35)      \n"+clr);
    dk_echo(RGB+"0;0;30m    RGB test (0;0;30)      \n"+clr);
    dk_echo(RGB+"0;0;25m    RGB test (0;0;25)      \n"+clr);
    dk_echo(RGB+"0;0;20m    RGB test (0;0;20)      \n"+clr);
    dk_echo(RGB+"0;0;15m    RGB test (0;0;15)      \n"+clr);
    dk_echo(RGB+"0;0;10m    RGB test (0;0;10)      \n"+clr);
    dk_echo(RGB+"0;0;5m    RGB test (0;0;5)       \n"+clr);
    dk_echo(RGB+"0;0;0m    RGB test (0;0;0)       \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo("black bg_lblack     RGB Background Colors     \n"+clr);
    dk_echo(bg_RGB+"255;10;10m    bg_RGB test (255;0;10)    \n"+clr);
    dk_echo(bg_RGB+"10;255;10m    bg_RGB test (0;255;10)    \n"+clr);
    dk_echo(bg_RGB+"0;0;255m    bg_RGB test (0;0;255)     \n"+clr);
    dk_echo(bg_RGB+"0;0;250m    bg_RGB test (0;0;250)     \n"+clr);
    dk_echo(bg_RGB+"0;0;245m    bg_RGB test (0;0;245)     \n"+clr);
    dk_echo(bg_RGB+"0;0;240m    bg_RGB test (0;0;240)     \n"+clr);
    dk_echo(bg_RGB+"0;0;235m    bg_RGB test (0;0;235)     \n"+clr);
    dk_echo(bg_RGB+"0;0;230m    bg_RGB test (0;0;230)     \n"+clr);
    dk_echo(bg_RGB+"0;0;225m    bg_RGB test (0;0;225)     \n"+clr);
    dk_echo(bg_RGB+"0;0;220m    bg_RGB test (0;0;220)     \n"+clr);
    dk_echo(bg_RGB+"0;0;215m    bg_RGB test (0;0;215)     \n"+clr);
    dk_echo(bg_RGB+"0;0;210m    bg_RGB test (0;0;210)     \n"+clr);
    dk_echo(bg_RGB+"0;0;205m    bg_RGB test (0;0;205)     \n"+clr);
    dk_echo(bg_RGB+"0;0;200m    bg_RGB test (0;0;200)     \n"+clr);
    dk_echo(bg_RGB+"0;0;195m    bg_RGB test (0;0;195)     \n"+clr);
    dk_echo(bg_RGB+"0;0;190m    bg_RGB test (0;0;190)     \n"+clr);
    dk_echo(bg_RGB+"0;0;185m    bg_RGB test (0;0;185)     \n"+clr);
    dk_echo(bg_RGB+"0;0;180m    bg_RGB test (0;0;180)     \n"+clr);
    dk_echo(bg_RGB+"0;0;175m    bg_RGB test (0;0;175)     \n"+clr);
    dk_echo(bg_RGB+"0;0;170m    bg_RGB test (0;0;170)     \n"+clr);
    dk_echo(bg_RGB+"0;0;165m    bg_RGB test (0;0;165)     \n"+clr);
    dk_echo(bg_RGB+"0;0;160m    bg_RGB test (0;0;160)     \n"+clr);
    dk_echo(bg_RGB+"0;0;155m    bg_RGB test (0;0;155)     \n"+clr);
    dk_echo(bg_RGB+"0;0;150m    bg_RGB test (0;0;150)     \n"+clr);
    dk_echo(bg_RGB+"0;0;145m    bg_RGB test (0;0;145)     \n"+clr);
    dk_echo(bg_RGB+"0;0;140m    bg_RGB test (0;0;140)     \n"+clr);
    dk_echo(bg_RGB+"0;0;135m    bg_RGB test (0;0;135)     \n"+clr);
    dk_echo(bg_RGB+"0;0;130m    bg_RGB test (0;0;130)     \n"+clr);
    dk_echo(bg_RGB+"0;0;125m    bg_RGB test (0;0;125)     \n"+clr);
    dk_echo(bg_RGB+"0;0;120m    bg_RGB test (0;0;120)     \n"+clr);
    dk_echo(bg_RGB+"0;0;115m    bg_RGB test (0;0;115)     \n"+clr);
    dk_echo(bg_RGB+"0;0;110m    bg_RGB test (0;0;110)     \n"+clr);
    dk_echo(bg_RGB+"0;0;105m    bg_RGB test (0;0;105)     \n"+clr);
    dk_echo(bg_RGB+"0;0;100m    bg_RGB test (0;0;100)     \n"+clr);
    dk_echo(bg_RGB+"0;0;95m    bg_RGB test (0;0;95)      \n"+clr);
    dk_echo(bg_RGB+"0;0;90m    bg_RGB test (0;0;90)      \n"+clr);
    dk_echo(bg_RGB+"0;0;85m    bg_RGB test (0;0;85)      \n"+clr);
    dk_echo(bg_RGB+"0;0;80m    bg_RGB test (0;0;80)      \n"+clr);
    dk_echo(bg_RGB+"0;0;75m    bg_RGB test (0;0;75)      \n"+clr);
    dk_echo(bg_RGB+"0;0;70m    bg_RGB test (0;0;70)      \n"+clr);
    dk_echo(bg_RGB+"0;0;65m    bg_RGB test (0;0;65)      \n"+clr);
    dk_echo(bg_RGB+"0;0;60m    bg_RGB test (0;0;60)      \n"+clr);
    dk_echo(bg_RGB+"0;0;55m    bg_RGB test (0;0;55)      \n"+clr);
    dk_echo(bg_RGB+"0;0;50m    bg_RGB test (0;0;50)      \n"+clr);
    dk_echo(bg_RGB+"0;0;45m    bg_RGB test (0;0;45)      \n"+clr);
    dk_echo(bg_RGB+"0;0;40m    bg_RGB test (0;0;40)      \n"+clr);
    dk_echo(bg_RGB+"0;0;35m    bg_RGB test (0;0;35)      \n"+clr);
    dk_echo(bg_RGB+"0;0;30m    bg_RGB test (0;0;30)      \n"+clr);
    dk_echo(bg_RGB+"0;0;25m    bg_RGB test (0;0;25)      \n"+clr);
    dk_echo(bg_RGB+"0;0;20m    bg_RGB test (0;0;20)      \n"+clr);
    dk_echo(bg_RGB+"0;0;15m    bg_RGB test (0;0;15)      \n"+clr);
    dk_echo(bg_RGB+"0;0;10m    bg_RGB test (0;0;10)      \n"+clr);
    dk_echo(bg_RGB+"0;0;5m    bg_RGB test (0;0;5)       \n"+clr);
    dk_echo(bg_RGB+"0;0;0m    bg_RGB test (0;0;0)       \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"          Combinations         \n"+clr);
    dk_echo("negative                             negative    inverse foreground <-> background   \n"+clr);
    dk_echo("bg_yellow red                      bg_yellow red    yellow backgroud / red foreground   \n"+clr);
    dk_echo("bg_yellow red negative           bg_yellow red negative         yellow / red inversed          \n"+clr);
    dk_echo("bg_red ..bg_green ..bg_blue      bg_red     nested   bg_green     colors    bg_blue     text    \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"         ASCII Color Art       \n"+clr);
    dk_echo("\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
*/
=======
#ifndef DKMAIN
#define DKMAIN 1
int main(int argc, char** argv){
    dk_echo("\n");
 
	dk_echo("%s%s          CSI Codes         %s\n", black, bg_lblack, clr);
	dk_echo("0    clr           %s      clr             %s\n", clr,  clr);
    dk_echo("1    bold          %s      bold            %s\n", bold, clr);
	dk_echo("2    dim           %s      dim             %s\n", dim, clr);
    dk_echo("3    italic        %s      italic          %s\n", italic, clr);
    dk_echo("4    underline     %s      underline       %s\n", underline, clr);
    dk_echo("5    blink         %s      blink           %s\n", blink, clr);
    dk_echo("6    fblink        %s      fblink          %s\n", fblink, clr);
    dk_echo("7    negative      %s      negative        %s\n", negative, clr);
    dk_echo("8    invisible     %s      invisible       %s\n", invisible, clr);
    dk_echo("9    strike        %s      strike          %s\n", strike, clr);
    dk_echo("10   ANSI10        %s      ANSI10          %s\n", ANSI10, clr);
    dk_echo("11   ANSI11        %s      ANSI11          %s\n", ANSI11, clr);
    dk_echo("12   ANSI12        %s      ANSI12          %s\n", ANSI12, clr);
    dk_echo("13   ANSI13        %s      ANSI13          %s\n", ANSI13, clr);
    dk_echo("14   ANSI14        %s      ANSI14          %s\n", ANSI14, clr);
    dk_echo("15   ANSI15        %s      ANSI15          %s\n", ANSI15, clr);
    dk_echo("16   ANSI16        %s      ANSI16          %s\n", ANSI16, clr);
    dk_echo("17   ANSI17        %s      ANSI17          %s\n", ANSI17, clr);
    dk_echo("18   ANSI18        %s      ANSI18          %s\n", ANSI18, clr);
    dk_echo("19   ANSI19        %s      ANSI19          %s\n", ANSI19, clr);
    dk_echo("20   ANSI20        %s      ANSI20          %s\n", ANSI20, clr);
    dk_echo("21   ANSI21        %s      ANSI21          %s\n", ANSI21, clr);
    dk_echo("22   nobold        %s      nobold          %s\n", nobold, clr);
    dk_echo("23   noitalic      %s      noitalic        %s\n", noitalic, clr);
    dk_echo("24   nounderline   %s      nounderline     %s\n", nounderline, clr);
    dk_echo("25   noblink       %s      noblink         %s\n", noblink, clr);
    dk_echo("26   ANSI26        %s      ANSI26          %s\n", ANSI26, clr);
    dk_echo("27   nonegative    %s      nonegative      %s\n", nonegative , clr);
    dk_echo("28   visible       %s      visible         %s\n", visible, clr);
    dk_echo("29   nostrike      %s      nostrike        %s\n", nostrike, clr);
    dk_echo("30   black         %s%s      black           %s\n", black, bg_lblack, clr);
    dk_echo("31   red           %s      red             %s\n", red, clr);
    dk_echo("32   green         %s      green           %s\n", green, clr);
    dk_echo("33   yellow        %s      yellow          %s\n", yellow, clr);
    dk_echo("34   blue          %s      blue            %s\n", blue, clr);
    dk_echo("35   magenta       %s      magenta         %s\n", magenta, clr);
    dk_echo("36   cyan          %s      cyan            %s\n", cyan, clr);
    dk_echo("37   white         %s      white           %s\n", white, clr);
	dk_echo("38   RGB                  %s255;0;0mR%s0;255;0mG%s0;0;255mB       %s\n", RGB, RGB, RGB, clr);
    dk_echo("39   default_      %s      default_        %s\n", default_, clr);
    dk_echo("40   bg_black      %s%s      bg_black        %s\n", bg_black, white, clr);
    dk_echo("41   bg_red        %s%s      bg_red          %s\n", bg_red, black, clr);
    dk_echo("42   bg_green      %s%s      bg_green        %s\n", bg_green, black, clr);
    dk_echo("43   bg_yellow     %s%s      bg_yellow       %s\n", bg_yellow, black, clr);
    dk_echo("44   bg_blue       %s%s      bg_blue         %s\n", bg_blue, black, clr);
    dk_echo("45   bg_magenta    %s%s      bg_magenta      %s\n", bg_magenta, black, clr);
    dk_echo("46   bg_cyan       %s%s      bg_cyan         %s\n", bg_cyan, black, clr);
    dk_echo("47   bg_white      %s%s      bg_white        %s\n", bg_white, black, clr);
    dk_echo("38   bg_RGB               %s255;0;0mR%s0;255;0mG%s0;0;255mB%s       \n", bg_RGB, bg_RGB, bg_RGB, clr);
    dk_echo("49   bg_default    %s%s      bg_default      %s\n", bg_default, white, clr);
    dk_echo("50   ANSI50        %s      ANSI50          %s\n", ANSI50, clr);
    dk_echo("51   ANSI51        %s      ANSI51          %s\n", ANSI51, clr);
    dk_echo("52   ANSI52        %s      ANSI52          %s\n", ANSI52, clr);
    dk_echo("53   ANSI53        %s      ANSI53          %s\n", ANSI53, clr);
    dk_echo("54   ANSI54        %s      ANSI54          %s\n", ANSI54, clr);
    dk_echo("55   ANSI55        %s      ANSI55          %s\n", ANSI55, clr);
    dk_echo("56   ANSI56        %s      ANSI56          %s\n", ANSI56, clr);
    dk_echo("57   ANSI57        %s      ANSI57          %s\n", ANSI57, clr);
    dk_echo("58   ANSI58        %s      ANSI58          %s\n", ANSI58, clr);
    dk_echo("59   ANSI59        %s      ANSI59          %s\n", ANSI59, clr);
    dk_echo("60   ANSI60        %s      ANSI60          %s\n", ANSI60, clr);
    dk_echo("61   ANSI61        %s      ANSI61          %s\n", ANSI61, clr);
    dk_echo("62   ANSI62        %s      ANSI62          %s\n", ANSI62, clr);
    dk_echo("63   ANSI63        %s      ANSI63          %s\n", ANSI63, clr);
    dk_echo("64   ANSI64        %s      ANSI64          %s\n", ANSI64, clr);
    dk_echo("65   ANSI65        %s      ANSI65          %s\n", ANSI65, clr);
    dk_echo("66   ANSI66        %s      ANSI66          %s\n", ANSI66, clr);
    dk_echo("67   ANSI67        %s      ANSI67          %s\n", ANSI67, clr);
    dk_echo("68   ANSI68        %s      ANSI68          %s\n", ANSI68, clr);
    dk_echo("69   ANSI69        %s      ANSI69          %s\n", ANSI69, clr);
    dk_echo("70   ANSI70        %s      ANSI70          %s\n", ANSI70, clr);
    dk_echo("71   ANSI71        %s      ANSI71          %s\n", ANSI71, clr);
    dk_echo("72   ANSI72        %s      ANSI72          %s\n", ANSI72, clr);
    dk_echo("73   ANSI73        %s      ANSI73          %s\n", ANSI73, clr);
    dk_echo("74   ANSI74        %s      ANSI74          %s\n", ANSI74, clr);
    dk_echo("75   ANSI75        %s      ANSI75          %s\n", ANSI75, clr);
    dk_echo("76   ANSI76        %s      ANSI76          %s\n", ANSI76, clr);
    dk_echo("77   ANSI77        %s      ANSI77          %s\n", ANSI77, clr);
    dk_echo("78   ANSI78        %s      ANSI78          %s\n", ANSI78, clr);
    dk_echo("79   ANSI79        %s      ANSI79          %s\n", ANSI79, clr);
    dk_echo("80   ANSI80        %s      ANSI80          %s\n", ANSI80, clr);
    dk_echo("81   ANSI81        %s      ANSI81          %s\n", ANSI81, clr);
    dk_echo("82   ANSI82        %s      ANSI82          %s\n", ANSI82, clr);
    dk_echo("83   ANSI83        %s      ANSI83          %s\n", ANSI83, clr);
    dk_echo("84   ANSI84        %s      ANSI84          %s\n", ANSI84, clr);
    dk_echo("85   ANSI85        %s      ANSI85          %s\n", ANSI85, clr);
    dk_echo("86   ANSI86        %s      ANSI86          %s\n", ANSI86, clr);
    dk_echo("87   ANSI87        %s      ANSI87          %s\n", ANSI87, clr);
    dk_echo("88   ANSI88        %s      ANSI88          %s\n", ANSI88, clr);
    dk_echo("89   ANSI89        %s      ANSI89          %s\n", ANSI89, clr);
    dk_echo("90   lblack        %s      lblack          %s\n", lblack, clr);
    dk_echo("91   lred          %s      lred            %s\n", lred, clr);
    dk_echo("92   lgreen        %s      lgreen          %s\n", lgreen, clr);
    dk_echo("93   lyellow       %s      lyellow         %s\n", lyellow, clr);
    dk_echo("94   lblue         %s      lblue           %s\n", lblue, clr);
    dk_echo("95   lmagenta      %s      lmagenta        %s\n", lmagenta, clr);
    dk_echo("96   lcyan         %s      lcyan           %s\n", lcyan, clr);
    dk_echo("97   lwhite        %s      lwhite          %s\n", lwhite, clr);
    dk_echo("98   ANSI98        %s      ANSI98          %s\n", ANSI98, clr);
    dk_echo("99   ANSI99        %s      ANSI99          %s\n", ANSI99, clr);
    dk_echo("100  bg_lblack     %s%s      bg_lblack       %s\n", bg_lblack, black, clr);
    dk_echo("101  bg_lred       %s%s      bg_lred         %s\n", bg_lred, black, clr);
    dk_echo("102  bg_lgreen     %s%s      bg_lgreen       %s\n", bg_lgreen, black, clr);
    dk_echo("103  bg_lyellow    %s%s      bg_lyellow      %s\n", bg_lyellow, black, clr);
    dk_echo("104  bg_lblue      %s%s      bg_lblue        %s\n", bg_lblue, black, clr);
    dk_echo("105  bg_lmagenta   %s%s      bg_lmagenta     %s\n", bg_lmagenta, black, clr);
    dk_echo("106  bg_lcyan      %s%s      bg_lcyan        %s\n", bg_lcyan, black, clr);
    dk_echo("107  bg_lwhite     %s%s      bg_lwhite       %s\n", bg_lwhite, black, clr);
    dk_echo("108  ANSI108       %s      ANSI108         %s\n", ANSI108, clr);
    dk_echo("109  ANSI109       %s      ANSI109         %s\n", ANSI109, clr);
    dk_echo("110  ANSI110       %s      ANSI110         %s\n", ANSI110, clr);
    dk_echo("111  ANSI111       %s      ANSI111         %s\n", ANSI111, clr);
    dk_echo("112  ANSI112       %s      ANSI112         %s\n", ANSI112, clr);
    dk_echo("113  ANSI113       %s      ANSI113         %s\n", ANSI113, clr);
    dk_echo("114  ANSI114       %s      ANSI114         %s\n", ANSI114, clr);
    dk_echo("115  ANSI115       %s      ANSI115         %s\n", ANSI115, clr);
    dk_echo("116  ANSI116       %s      ANSI116         %s\n", ANSI116, clr);
    dk_echo("117  ANSI117       %s      ANSI117         %s\n", ANSI117, clr);
    dk_echo("118  ANSI118       %s      ANSI118         %s\n", ANSI118, clr);
    dk_echo("119  ANSI119       %s      ANSI119         %s\n", ANSI119, clr);
    dk_echo("120  ANSI120       %s      ANSI120         %s\n", ANSI120, clr);
    dk_echo("121  ANSI121       %s      ANSI121         %s\n", ANSI121, clr);
    dk_echo("122  ANSI122       %s      ANSI122         %s\n", ANSI122, clr);
    dk_echo("123  ANSI123       %s      ANSI123         %s\n", ANSI123, clr);
    dk_echo("124  ANSI124       %s      ANSI124         %s\n", ANSI124, clr);
	
	dk_echo("%s%s                Styles                 %s\n", black, bg_lblack, clr);
	dk_echo("%s%s          Style Combinations           %s\n", black, bg_lblack, clr);
	dk_echo("%s%s          Color Combinations           %s\n", black, bg_lblack, clr);
	dk_echo("%s%s          Foreground Colors            %s\n", black, bg_lblack, clr);
	dk_echo("%s%s          Background Colors            %s\n", black, bg_lblack, clr);
	dk_echo("%s%s       Foreground Colors  bright       %s\n", black, bg_lblack, clr);
	dk_echo("%s%s       Background Colors  bright       %s\n", black, bg_lblack, clr);
	
	dk_echo("%s%s          RGB Foreground Colors        %s\n", black, bg_lblack, clr);
    dk_echo("%s255;10;10m  RGB test (255;0;10)    %s\n",RGB, clr);
    dk_echo("%s10;255;10m  RGB test (0;255;10)    %s\n",RGB, clr);
    dk_echo("%s0;0;255m    RGB test (0;0;255)     %s\n",RGB, clr);
    dk_echo("%s0;0;250m    RGB test (0;0;250)     %s\n",RGB, clr);
    dk_echo("%s0;0;245m    RGB test (0;0;245)     %s\n",RGB, clr);
    dk_echo("%s0;0;240m    RGB test (0;0;240)     %s\n",RGB, clr);
    dk_echo("%s0;0;235m    RGB test (0;0;235)     %s\n",RGB, clr);
    dk_echo("%s0;0;230m    RGB test (0;0;230)     %s\n",RGB, clr);
    dk_echo("%s0;0;225m    RGB test (0;0;225)     %s\n",RGB, clr);
    dk_echo("%s0;0;220m    RGB test (0;0;220)     %s\n",RGB, clr);
    dk_echo("%s0;0;215m    RGB test (0;0;215)     %s\n",RGB, clr);
    dk_echo("%s0;0;210m    RGB test (0;0;210)     %s\n",RGB, clr);
    dk_echo("%s0;0;205m    RGB test (0;0;205)     %s\n",RGB, clr);
    dk_echo("%s0;0;200m    RGB test (0;0;200)     %s\n",RGB, clr);
    dk_echo("%s0;0;195m    RGB test (0;0;195)     %s\n",RGB, clr);
    dk_echo("%s0;0;190m    RGB test (0;0;190)     %s\n",RGB, clr);
    dk_echo("%s0;0;185m    RGB test (0;0;185)     %s\n",RGB, clr);
    dk_echo("%s0;0;180m    RGB test (0;0;180)     %s\n",RGB, clr);
    dk_echo("%s0;0;175m    RGB test (0;0;175)     %s\n",RGB, clr);
    dk_echo("%s0;0;170m    RGB test (0;0;170)     %s\n",RGB, clr);
    dk_echo("%s0;0;165m    RGB test (0;0;165)     %s\n",RGB, clr);
    dk_echo("%s0;0;160m    RGB test (0;0;160)     %s\n",RGB, clr);
    dk_echo("%s0;0;155m    RGB test (0;0;155)     %s\n",RGB, clr);
    dk_echo("%s0;0;150m    RGB test (0;0;150)     %s\n",RGB, clr);
    dk_echo("%s0;0;145m    RGB test (0;0;145)     %s\n",RGB, clr);
    dk_echo("%s0;0;140m    RGB test (0;0;140)     %s\n",RGB, clr);
    dk_echo("%s0;0;135m    RGB test (0;0;135)     %s\n",RGB, clr);
    dk_echo("%s0;0;130m    RGB test (0;0;130)     %s\n",RGB, clr);
    dk_echo("%s0;0;125m    RGB test (0;0;125)     %s\n",RGB, clr);
    dk_echo("%s0;0;120m    RGB test (0;0;120)     %s\n",RGB, clr);
    dk_echo("%s0;0;115m    RGB test (0;0;115)     %s\n",RGB, clr);
    dk_echo("%s0;0;110m    RGB test (0;0;110)     %s\n",RGB, clr);
    dk_echo("%s0;0;105m    RGB test (0;0;105)     %s\n",RGB, clr);
    dk_echo("%s0;0;100m    RGB test (0;0;100)     %s\n",RGB, clr);
    dk_echo("%s0;0;95m    RGB test (0;0;95)      %s\n",RGB, clr);
    dk_echo("%s0;0;90m    RGB test (0;0;90)      %s\n",RGB, clr);
    dk_echo("%s0;0;85m    RGB test (0;0;85)      %s\n",RGB, clr);
    dk_echo("%s0;0;80m    RGB test (0;0;80)      %s\n",RGB, clr);
    dk_echo("%s0;0;75m    RGB test (0;0;75)      %s\n",RGB, clr);
    dk_echo("%s0;0;70m    RGB test (0;0;70)      %s\n",RGB, clr);
    dk_echo("%s0;0;65m    RGB test (0;0;65)      %s\n",RGB, clr);
    dk_echo("%s0;0;60m    RGB test (0;0;60)      %s\n",RGB, clr);
    dk_echo("%s0;0;55m    RGB test (0;0;55)      %s\n",RGB, clr);
    dk_echo("%s0;0;50m    RGB test (0;0;50)      %s\n",RGB, clr);
    dk_echo("%s0;0;45m    RGB test (0;0;45)      %s\n",RGB, clr);
    dk_echo("%s0;0;40m    RGB test (0;0;40)      %s\n",RGB, clr);
    dk_echo("%s0;0;35m    RGB test (0;0;35)      %s\n",RGB, clr);
    dk_echo("%s0;0;30m    RGB test (0;0;30)      %s\n",RGB, clr);
    dk_echo("%s0;0;25m    RGB test (0;0;25)      %s\n",RGB, clr);
    dk_echo("%s0;0;20m    RGB test (0;0;20)      %s\n",RGB, clr);
    dk_echo("%s0;0;15m    RGB test (0;0;15)      %s\n",RGB, clr);
    dk_echo("%s0;0;10m    RGB test (0;0;10)      %s\n",RGB, clr);
    dk_echo("%s0;0;5m    RGB test (0;0;5)       %s\n",RGB, clr);
    dk_echo("%s0;0;0m    RGB test (0;0;0)       %s\n",RGB, clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo("%s%s            RGB Background Colors     %s\n", black, bg_lblack, clr);
    dk_echo("%s255;10;10m    bg_RGB test (255;0;10)    %s\n", bg_RGB, clr);
    dk_echo("%s10;255;10m    bg_RGB test (0;255;10)    %s\n", bg_RGB, clr);
    dk_echo("%s0;0;255m    bg_RGB test (0;0;255)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;250m    bg_RGB test (0;0;250)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;245m    bg_RGB test (0;0;245)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;240m    bg_RGB test (0;0;240)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;235m    bg_RGB test (0;0;235)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;230m    bg_RGB test (0;0;230)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;225m    bg_RGB test (0;0;225)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;220m    bg_RGB test (0;0;220)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;215m    bg_RGB test (0;0;215)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;210m    bg_RGB test (0;0;210)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;205m    bg_RGB test (0;0;205)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;200m    bg_RGB test (0;0;200)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;195m    bg_RGB test (0;0;195)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;190m    bg_RGB test (0;0;190)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;185m    bg_RGB test (0;0;185)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;180m    bg_RGB test (0;0;180)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;175m    bg_RGB test (0;0;175)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;170m    bg_RGB test (0;0;170)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;165m    bg_RGB test (0;0;165)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;160m    bg_RGB test (0;0;160)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;155m    bg_RGB test (0;0;155)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;150m    bg_RGB test (0;0;150)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;145m    bg_RGB test (0;0;145)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;140m    bg_RGB test (0;0;140)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;135m    bg_RGB test (0;0;135)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;130m    bg_RGB test (0;0;130)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;125m    bg_RGB test (0;0;125)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;120m    bg_RGB test (0;0;120)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;115m    bg_RGB test (0;0;115)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;110m    bg_RGB test (0;0;110)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;105m    bg_RGB test (0;0;105)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;100m    bg_RGB test (0;0;100)     %s\n", bg_RGB, clr);
    dk_echo("%s0;0;95m    bg_RGB test (0;0;95)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;90m    bg_RGB test (0;0;90)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;85m    bg_RGB test (0;0;85)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;80m    bg_RGB test (0;0;80)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;75m    bg_RGB test (0;0;75)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;70m    bg_RGB test (0;0;70)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;65m    bg_RGB test (0;0;65)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;60m    bg_RGB test (0;0;60)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;55m    bg_RGB test (0;0;55)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;50m    bg_RGB test (0;0;50)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;45m    bg_RGB test (0;0;45)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;40m    bg_RGB test (0;0;40)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;35m    bg_RGB test (0;0;35)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;30m    bg_RGB test (0;0;30)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;25m    bg_RGB test (0;0;25)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;20m    bg_RGB test (0;0;20)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;15m    bg_RGB test (0;0;15)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;10m    bg_RGB test (0;0;10)      %s\n", bg_RGB, clr);
    dk_echo("%s0;0;5m    bg_RGB test (0;0;5)       %s\n", bg_RGB, clr);
    dk_echo("%s0;0;0m    bg_RGB test (0;0;0)       %s\n", bg_RGB, clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo("%s%s          Combinations         %s\n", black, bg_lblack, clr);
    dk_echo("negative                         %s      inverse foreground <-> background   %s\n", negative, clr);
    dk_echo("bg_yellow red                    %s%s      yellow backgroud / red foreground   %s\n", bg_yellow, red, clr);
    dk_echo("bg_yellow red negative           %s%s%s           yellow / red inversed          %s\n", bg_yellow, red, negative, clr);
    dk_echo("bg_red ..bg_green ..bg_blue      %s     nested   %s     colors    %s     text    %s\n", bg_red, bg_green, bg_blue, clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo("%s%s         ASCII Color Art       %s\n", black, bg_lblack, clr);
    dk_echo("\n");
    dk_echo("%s  * * * * * * * * * %s                                   %s\n", bg_blue, bg_red, clr);
    dk_echo("%s   * * * * * * * *  %s                                   %s\n", bg_blue, bg_white, clr);
    dk_echo("%s  * * * * * * * * * %s                                   %s\n", bg_blue, bg_red, clr);
    dk_echo("%s   * * * * * * * *  %s                                   %s\n", bg_blue, bg_white, clr);
    dk_echo("%s  * * * * * * * * * %s                                   %s\n", bg_blue, bg_red, clr);
    dk_echo("%s   * * * * * * * *  %s                                   %s\n", bg_blue, bg_white, clr);
    dk_echo("%s  * * * * * * * * * %s                                   %s\n", bg_blue, bg_red, clr);
    dk_echo("%s                                                       %s\n", bg_white, clr);
    dk_echo("%s                                                       %s\n", bg_red, clr);
    dk_echo("%s                                                       %s\n", bg_white, clr);
    dk_echo("%s                                                       %s\n", bg_red, clr);
    dk_echo("%s                                                       %s\n", bg_white, clr);
    dk_echo("%s                                                       %s\n", bg_red, clr);
    dk_echo("\n");
    dk_echo("\n");
	
	int exit_status = 0;
	return exit_status;
>>>>>>> Development
}
#endif
