#include "dk_color.h"
#include "dk_echo.h"

//###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ###### DKTEST ######
#ifndef DKMAIN
#define DKMAIN = 1
int main() {
    dk_echo("\n");

	printf("0    clr          %s      clr            \n%s", clr,  clr);
    printf("1    bold         %s      bold           \n%s", bold, clr);
/*  dk_echo("2    dim          "+ dim                 +"      dim            \n"+clr);
    dk_echo("3    italic       "+ italic              +"      italic         \n"+clr);
    dk_echo("4    underline    "+ underline           +"      underline      \n"+clr);
    dk_echo("5    blink        "+ blink               +"      blink          \n"+clr);
    dk_echo("6    fblink       "+ fblink              +"      fblink         \n"+clr);
    dk_echo("7    negative     "+ negative            +"      negative       \n"+clr);
    dk_echo("8    invisible    "+ invisible           +"      invisible      \n"+clr);
    dk_echo("9    strike       "+ strike              +"      strike         \n"+clr);
    dk_echo("10   ANSI10       "+ ANSI10              +"      UNKNOWN        \n"+clr);
    dk_echo("11   ANSI11       "+ ANSI11              +"      UNKNOWN        \n"+clr);
    dk_echo("12   ANSI12       "+ ANSI12              +"      UNKNOWN        \n"+clr);
    dk_echo("13   ANSI13       "+ ANSI13              +"      UNKNOWN        \n"+clr);
    dk_echo("14   ANSI14       "+ ANSI14              +"      UNKNOWN        \n"+clr);
    dk_echo("15   ANSI15       "+ ANSI15              +"      UNKNOWN        \n"+clr);
    dk_echo("16   ANSI16       "+ ANSI16              +"      UNKNOWN        \n"+clr);
    dk_echo("17   ANSI17       "+ ANSI17              +"      UNKNOWN        \n"+clr);
    dk_echo("18   ANSI18       "+ ANSI18              +"      UNKNOWN        \n"+clr);
    dk_echo("19   ANSI19       "+ ANSI19              +"      UNKNOWN        \n"+clr);
    dk_echo("20   ANSI20       "+ ANSI20              +"      UNKNOWN        \n"+clr);
    dk_echo("21   ANSI21       "+ ANSI21              +"      UNKNOWN        \n"+clr);
    dk_echo("22   nobold       "+ nobold              +"      nobold         \n"+clr);
    dk_echo("23   noitalic     "+ noitalic            +"      noitalic       \n"+clr);
    dk_echo("24   nounderline  "+ nounderline         +"      nounderline    \n"+clr);
    dk_echo("25   noblink      "+ noblink             +"      noblink        \n"+clr);
    dk_echo("26   ANSI26       "+ ANSI26              +"      UNKNOWN        \n"+clr);
    dk_echo("27   nonegative   "+ nonegative          +"      nonegative     \n"+clr);
    dk_echo("28   visible      "+ visible             +"      visible        \n"+clr);
    dk_echo("29   nostrike     "+ nostrike            +"      nostrike       \n"+clr);
    dk_echo("30   black        "+ black + bg_lblack   +"      black          \n"+clr);
    dk_echo("31   red          "+ red                 +"      red            \n"+clr);
    dk_echo("32   green        "+ green               +"      green          \n"+clr);
    dk_echo("33   yellow       "+ yellow              +"      yellow         \n"+clr);
    dk_echo("34   blue         "+ blue                +"      blue           \n"+clr);
    dk_echo("35   magenta      "+ magenta             +"      magenta        \n"+clr);
    dk_echo("36   cyan         "+ cyan                +"      cyan           \n"+clr);
    dk_echo("37   white        "+ white               +"      white          \n"+clr);
    dk_echo("38   RGB          "+ RGB                 +"      RGB            \n"+clr);
    dk_echo("39   default_     "+ default_            +"      default_       \n"+clr);
    dk_echo("40   bg_black     "+ bg_black   + white  +"      bg_black       \n"+clr);
    dk_echo("41   bg_red       "+ bg_red     + black  +"      bg_red         \n"+clr);
    dk_echo("42   bg_green     "+ bg_green   + black  +"      bg_green       \n"+clr);
    dk_echo("43   bg_yellow    "+ bg_yellow  + black  +"      bg_yellow      \n"+clr);
    dk_echo("44   bg_blue      "+ bg_blue    + black  +"      bg_blue        \n"+clr);
    dk_echo("45   bg_magenta   "+ bg_magenta + black  +"      bg_magenta     \n"+clr);
    dk_echo("46   bg_cyan      "+ bg_cyan    + black  +"      bg_cyan        \n"+clr);
    dk_echo("47   bg_white     "+ bg_white   + black  +"      bg_white       \n"+clr);
    dk_echo("48   bg_RGB       "+ bg_RGB     + black  +"      bg_RGB         \n"+clr);
    dk_echo("49   bg_default   "+ bg_default + white  +"      bg_default     \n"+clr);
    dk_echo("50   ANSI50       "+ ANSI50              +"      UNKNOWN        \n"+clr);
    dk_echo("51   ANSI51       "+ ANSI51              +"      UNKNOWN        \n"+clr);
    dk_echo("52   ANSI52       "+ ANSI52              +"      UNKNOWN        \n"+clr);
    dk_echo("53   ANSI53       "+ ANSI53              +"      UNKNOWN        \n"+clr);
    dk_echo("54   ANSI54       "+ ANSI54              +"      UNKNOWN        \n"+clr);
    dk_echo("55   ANSI55       "+ ANSI55              +"      UNKNOWN        \n"+clr);
    dk_echo("56   ANSI56       "+ ANSI56              +"      UNKNOWN        \n"+clr);
    dk_echo("57   ANSI57       "+ ANSI57              +"      UNKNOWN        \n"+clr);
    dk_echo("58   ANSI58       "+ ANSI58              +"      UNKNOWN        \n"+clr);
    dk_echo("59   ANSI59       "+ ANSI59              +"      UNKNOWN        \n"+clr);
    dk_echo("60   ANSI60       "+ ANSI60              +"      UNKNOWN        \n"+clr);
    dk_echo("61   ANSI61       "+ ANSI61              +"      UNKNOWN        \n"+clr);
    dk_echo("62   ANSI62       "+ ANSI62              +"      UNKNOWN        \n"+clr);
    dk_echo("63   ANSI63       "+ ANSI63              +"      UNKNOWN        \n"+clr);
    dk_echo("64   ANSI64       "+ ANSI64              +"      UNKNOWN        \n"+clr);
    dk_echo("65   ANSI65       "+ ANSI65              +"      UNKNOWN        \n"+clr);
    dk_echo("66   ANSI66       "+ ANSI66              +"      UNKNOWN        \n"+clr);
    dk_echo("67   ANSI67       "+ ANSI67              +"      UNKNOWN        \n"+clr);
    dk_echo("68   ANSI68       "+ ANSI68              +"      UNKNOWN        \n"+clr);
    dk_echo("69   ANSI69       "+ ANSI69              +"      UNKNOWN        \n"+clr);
    dk_echo("70   ANSI70       "+ ANSI70              +"      UNKNOWN        \n"+clr);
    dk_echo("71   ANSI71       "+ ANSI71              +"      UNKNOWN        \n"+clr);
    dk_echo("72   ANSI72       "+ ANSI72              +"      UNKNOWN        \n"+clr);
    dk_echo("73   ANSI73       "+ ANSI73              +"      UNKNOWN        \n"+clr);
    dk_echo("74   ANSI74       "+ ANSI74              +"      UNKNOWN        \n"+clr);
    dk_echo("75   ANSI75       "+ ANSI75              +"      UNKNOWN        \n"+clr);
    dk_echo("76   ANSI76       "+ ANSI76              +"      UNKNOWN        \n"+clr);
    dk_echo("77   ANSI77       "+ ANSI77              +"      UNKNOWN        \n"+clr);
    dk_echo("78   ANSI78       "+ ANSI78              +"      UNKNOWN        \n"+clr);
    dk_echo("79   ANSI79       "+ ANSI79              +"      UNKNOWN        \n"+clr);
    dk_echo("80   ANSI80       "+ ANSI80              +"      UNKNOWN        \n"+clr);
    dk_echo("81   ANSI81       "+ ANSI81              +"      UNKNOWN        \n"+clr);
    dk_echo("82   ANSI82       "+ ANSI82              +"      UNKNOWN        \n"+clr);
    dk_echo("83   ANSI83       "+ ANSI83              +"      UNKNOWN        \n"+clr);
    dk_echo("84   ANSI84       "+ ANSI84              +"      UNKNOWN        \n"+clr);
    dk_echo("85   ANSI85       "+ ANSI85              +"      UNKNOWN        \n"+clr);
    dk_echo("86   ANSI86       "+ ANSI86              +"      UNKNOWN        \n"+clr);
    dk_echo("87   ANSI87       "+ ANSI87              +"      UNKNOWN        \n"+clr);
    dk_echo("88   ANSI88       "+ ANSI88              +"      UNKNOWN        \n"+clr);
    dk_echo("89   ANSI89       "+ ANSI89              +"      UNKNOWN        \n"+clr);
    dk_echo("90   lblack       "+ lblack              +"      lblack         \n"+clr);
    dk_echo("91   lred         "+ lred                +"      lred           \n"+clr);
    dk_echo("92   lgreen       "+ lgreen              +"      lgreen         \n"+clr);
    dk_echo("93   lyellow      "+ lyellow             +"      lyellow        \n"+clr);
    dk_echo("94   lblue        "+ lblue               +"      lblue          \n"+clr);
    dk_echo("95   lmagenta     "+ lmagenta            +"      lmagenta       \n"+clr);
    dk_echo("96   lcyan        "+ lcyan               +"      lcyan          \n"+clr);
    dk_echo("97   lwhite       "+ lwhite              +"      lwhite         \n"+clr);
    dk_echo("98   ANSI98       "+ ANSI98              +"      UNKNOWN        \n"+clr);
    dk_echo("99   ANSI99       "+ ANSI99              +"      UNKNOWN        \n"+clr);
    dk_echo("100  bg_lblack    "+ bg_lblack   + black +"      bg_lblack      \n"+clr);
    dk_echo("101  bg_lred      "+ bg_lred     + black +"      bg_lred        \n"+clr);
    dk_echo("102  bg_lgreen    "+ bg_lgreen   + black +"      bg_lgreen      \n"+clr);
    dk_echo("103  bg_lyellow   "+ bg_lyellow  + black +"      bg_lyellow     \n"+clr);
    dk_echo("104  bg_lblue     "+ bg_lblue    + black +"      bg_lblue       \n"+clr);
    dk_echo("105  bg_lmagenta  "+ bg_lmagenta + black +"      bg_lmagenta    \n"+clr);
    dk_echo("106  bg_lcyan     "+ bg_lcyan    + black +"      bg_lcyan       \n"+clr);
    dk_echo("107  bg_lwhite    "+ bg_lwhite   + black +"      bg_lwhite      \n"+clr);
    dk_echo("108  ANSI108      "+ ANSI108             +"      UNKNOWN        \n"+clr);
    dk_echo("109  ANSI109      "+ ANSI109             +"      UNKNOWN        \n"+clr);
    dk_echo("110  ANSI110      "+ ANSI110             +"      UNKNOWN        \n"+clr);
    dk_echo("111  ANSI111      "+ ANSI111             +"      UNKNOWN        \n"+clr);
    dk_echo("112  ANSI112      "+ ANSI112             +"      UNKNOWN        \n"+clr);
    dk_echo("113  ANSI113      "+ ANSI113             +"      UNKNOWN        \n"+clr);
    dk_echo("114  ANSI114      "+ ANSI114             +"      UNKNOWN        \n"+clr);
    dk_echo("115  ANSI115      "+ ANSI115             +"      UNKNOWN        \n"+clr);
    dk_echo("116  ANSI116      "+ ANSI116             +"      UNKNOWN        \n"+clr);
    dk_echo("117  ANSI117      "+ ANSI117             +"      UNKNOWN        \n"+clr);
    dk_echo("118  ANSI118      "+ ANSI118             +"      UNKNOWN        \n"+clr);
    dk_echo("119  ANSI119      "+ ANSI119             +"      UNKNOWN        \n"+clr);
    dk_echo("120  ANSI120      "+ ANSI120             +"      UNKNOWN        \n"+clr);
    dk_echo("121  ANSI121      "+ ANSI121             +"      UNKNOWN        \n"+clr);
    dk_echo("122  ANSI122      "+ ANSI122             +"      UNKNOWN        \n"+clr);
    dk_echo("123  ANSI123      "+ ANSI123             +"      UNKNOWN        \n"+clr);
    dk_echo("124  ANSI124      "+ ANSI124             +"      UNKNOWN        \n"+clr);

    dk_echo(RGB+"255;10;10m    RGB test (255;0;10)    \n"+clr);
    dk_echo(RGB+"10;255;10m    RGB test (0;255;10)    \n"+clr);
    dk_echo(RGB+"0;0;255m    RGB test (0;0;255)     \n"+clr);
    dk_echo(RGB+"0;0;250m    RGB test (0;0;250)     \n"+clr);
    dk_echo(RGB+"0;0;245m    RGB test (0;0;245)     \n"+clr);
    dk_echo(RGB+"0;0;240m    RGB test (0;0;240)     \n"+clr);
    dk_echo(RGB+"0;0;235m    RGB test (0;0;235)     \n"+clr);
    dk_echo(RGB+"0;0;230m    RGB test (0;0;230)     \n"+clr);
    dk_echo(RGB+"0;0;225m    RGB test (0;0;225)     \n"+clr);
    dk_echo(RGB+"0;0;220m    RGB test (0;0;220)     \n"+clr);
    dk_echo(RGB+"0;0;215m    RGB test (0;0;215)     \n"+clr);
    dk_echo(RGB+"0;0;210m    RGB test (0;0;210)     \n"+clr);
    dk_echo(RGB+"0;0;205m    RGB test (0;0;205)     \n"+clr);
    dk_echo(RGB+"0;0;200m    RGB test (0;0;200)     \n"+clr);
    dk_echo(RGB+"0;0;195m    RGB test (0;0;195)     \n"+clr);
    dk_echo(RGB+"0;0;190m    RGB test (0;0;190)     \n"+clr);
    dk_echo(RGB+"0;0;185m    RGB test (0;0;185)     \n"+clr);
    dk_echo(RGB+"0;0;180m    RGB test (0;0;180)     \n"+clr);
    dk_echo(RGB+"0;0;175m    RGB test (0;0;175)     \n"+clr);
    dk_echo(RGB+"0;0;170m    RGB test (0;0;170)     \n"+clr);
    dk_echo(RGB+"0;0;165m    RGB test (0;0;165)     \n"+clr);
    dk_echo(RGB+"0;0;160m    RGB test (0;0;160)     \n"+clr);
    dk_echo(RGB+"0;0;155m    RGB test (0;0;155)     \n"+clr);
    dk_echo(RGB+"0;0;150m    RGB test (0;0;150)     \n"+clr);
    dk_echo(RGB+"0;0;145m    RGB test (0;0;145)     \n"+clr);
    dk_echo(RGB+"0;0;140m    RGB test (0;0;140)     \n"+clr);
    dk_echo(RGB+"0;0;135m    RGB test (0;0;135)     \n"+clr);
    dk_echo(RGB+"0;0;130m    RGB test (0;0;130)     \n"+clr);
    dk_echo(RGB+"0;0;125m    RGB test (0;0;125)     \n"+clr);
    dk_echo(RGB+"0;0;120m    RGB test (0;0;120)     \n"+clr);
    dk_echo(RGB+"0;0;115m    RGB test (0;0;115)     \n"+clr);
    dk_echo(RGB+"0;0;110m    RGB test (0;0;110)     \n"+clr);
    dk_echo(RGB+"0;0;105m    RGB test (0;0;105)     \n"+clr);
    dk_echo(RGB+"0;0;100m    RGB test (0;0;100)     \n"+clr);
    dk_echo(RGB+"0;0;95m    RGB test (0;0;95)      \n"+clr);
    dk_echo(RGB+"0;0;90m    RGB test (0;0;90)      \n"+clr);
    dk_echo(RGB+"0;0;85m    RGB test (0;0;85)      \n"+clr);
    dk_echo(RGB+"0;0;80m    RGB test (0;0;80)      \n"+clr);
    dk_echo(RGB+"0;0;75m    RGB test (0;0;75)      \n"+clr);
    dk_echo(RGB+"0;0;70m    RGB test (0;0;70)      \n"+clr);
    dk_echo(RGB+"0;0;65m    RGB test (0;0;65)      \n"+clr);
    dk_echo(RGB+"0;0;60m    RGB test (0;0;60)      \n"+clr);
    dk_echo(RGB+"0;0;55m    RGB test (0;0;55)      \n"+clr);
    dk_echo(RGB+"0;0;50m    RGB test (0;0;50)      \n"+clr);
    dk_echo(RGB+"0;0;45m    RGB test (0;0;45)      \n"+clr);
    dk_echo(RGB+"0;0;40m    RGB test (0;0;40)      \n"+clr);
    dk_echo(RGB+"0;0;35m    RGB test (0;0;35)      \n"+clr);
    dk_echo(RGB+"0;0;30m    RGB test (0;0;30)      \n"+clr);
    dk_echo(RGB+"0;0;25m    RGB test (0;0;25)      \n"+clr);
    dk_echo(RGB+"0;0;20m    RGB test (0;0;20)      \n"+clr);
    dk_echo(RGB+"0;0;15m    RGB test (0;0;15)      \n"+clr);
    dk_echo(RGB+"0;0;10m    RGB test (0;0;10)      \n"+clr);
    dk_echo(RGB+"0;0;5m    RGB test (0;0;5)       \n"+clr);
    dk_echo(RGB+"0;0;0m    RGB test (0;0;0)       \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo("black bg_lblack     RGB Background Colors     \n"+clr);
    dk_echo(bg_RGB+"255;10;10m    bg_RGB test (255;0;10)    \n"+clr);
    dk_echo(bg_RGB+"10;255;10m    bg_RGB test (0;255;10)    \n"+clr);
    dk_echo(bg_RGB+"0;0;255m    bg_RGB test (0;0;255)     \n"+clr);
    dk_echo(bg_RGB+"0;0;250m    bg_RGB test (0;0;250)     \n"+clr);
    dk_echo(bg_RGB+"0;0;245m    bg_RGB test (0;0;245)     \n"+clr);
    dk_echo(bg_RGB+"0;0;240m    bg_RGB test (0;0;240)     \n"+clr);
    dk_echo(bg_RGB+"0;0;235m    bg_RGB test (0;0;235)     \n"+clr);
    dk_echo(bg_RGB+"0;0;230m    bg_RGB test (0;0;230)     \n"+clr);
    dk_echo(bg_RGB+"0;0;225m    bg_RGB test (0;0;225)     \n"+clr);
    dk_echo(bg_RGB+"0;0;220m    bg_RGB test (0;0;220)     \n"+clr);
    dk_echo(bg_RGB+"0;0;215m    bg_RGB test (0;0;215)     \n"+clr);
    dk_echo(bg_RGB+"0;0;210m    bg_RGB test (0;0;210)     \n"+clr);
    dk_echo(bg_RGB+"0;0;205m    bg_RGB test (0;0;205)     \n"+clr);
    dk_echo(bg_RGB+"0;0;200m    bg_RGB test (0;0;200)     \n"+clr);
    dk_echo(bg_RGB+"0;0;195m    bg_RGB test (0;0;195)     \n"+clr);
    dk_echo(bg_RGB+"0;0;190m    bg_RGB test (0;0;190)     \n"+clr);
    dk_echo(bg_RGB+"0;0;185m    bg_RGB test (0;0;185)     \n"+clr);
    dk_echo(bg_RGB+"0;0;180m    bg_RGB test (0;0;180)     \n"+clr);
    dk_echo(bg_RGB+"0;0;175m    bg_RGB test (0;0;175)     \n"+clr);
    dk_echo(bg_RGB+"0;0;170m    bg_RGB test (0;0;170)     \n"+clr);
    dk_echo(bg_RGB+"0;0;165m    bg_RGB test (0;0;165)     \n"+clr);
    dk_echo(bg_RGB+"0;0;160m    bg_RGB test (0;0;160)     \n"+clr);
    dk_echo(bg_RGB+"0;0;155m    bg_RGB test (0;0;155)     \n"+clr);
    dk_echo(bg_RGB+"0;0;150m    bg_RGB test (0;0;150)     \n"+clr);
    dk_echo(bg_RGB+"0;0;145m    bg_RGB test (0;0;145)     \n"+clr);
    dk_echo(bg_RGB+"0;0;140m    bg_RGB test (0;0;140)     \n"+clr);
    dk_echo(bg_RGB+"0;0;135m    bg_RGB test (0;0;135)     \n"+clr);
    dk_echo(bg_RGB+"0;0;130m    bg_RGB test (0;0;130)     \n"+clr);
    dk_echo(bg_RGB+"0;0;125m    bg_RGB test (0;0;125)     \n"+clr);
    dk_echo(bg_RGB+"0;0;120m    bg_RGB test (0;0;120)     \n"+clr);
    dk_echo(bg_RGB+"0;0;115m    bg_RGB test (0;0;115)     \n"+clr);
    dk_echo(bg_RGB+"0;0;110m    bg_RGB test (0;0;110)     \n"+clr);
    dk_echo(bg_RGB+"0;0;105m    bg_RGB test (0;0;105)     \n"+clr);
    dk_echo(bg_RGB+"0;0;100m    bg_RGB test (0;0;100)     \n"+clr);
    dk_echo(bg_RGB+"0;0;95m    bg_RGB test (0;0;95)      \n"+clr);
    dk_echo(bg_RGB+"0;0;90m    bg_RGB test (0;0;90)      \n"+clr);
    dk_echo(bg_RGB+"0;0;85m    bg_RGB test (0;0;85)      \n"+clr);
    dk_echo(bg_RGB+"0;0;80m    bg_RGB test (0;0;80)      \n"+clr);
    dk_echo(bg_RGB+"0;0;75m    bg_RGB test (0;0;75)      \n"+clr);
    dk_echo(bg_RGB+"0;0;70m    bg_RGB test (0;0;70)      \n"+clr);
    dk_echo(bg_RGB+"0;0;65m    bg_RGB test (0;0;65)      \n"+clr);
    dk_echo(bg_RGB+"0;0;60m    bg_RGB test (0;0;60)      \n"+clr);
    dk_echo(bg_RGB+"0;0;55m    bg_RGB test (0;0;55)      \n"+clr);
    dk_echo(bg_RGB+"0;0;50m    bg_RGB test (0;0;50)      \n"+clr);
    dk_echo(bg_RGB+"0;0;45m    bg_RGB test (0;0;45)      \n"+clr);
    dk_echo(bg_RGB+"0;0;40m    bg_RGB test (0;0;40)      \n"+clr);
    dk_echo(bg_RGB+"0;0;35m    bg_RGB test (0;0;35)      \n"+clr);
    dk_echo(bg_RGB+"0;0;30m    bg_RGB test (0;0;30)      \n"+clr);
    dk_echo(bg_RGB+"0;0;25m    bg_RGB test (0;0;25)      \n"+clr);
    dk_echo(bg_RGB+"0;0;20m    bg_RGB test (0;0;20)      \n"+clr);
    dk_echo(bg_RGB+"0;0;15m    bg_RGB test (0;0;15)      \n"+clr);
    dk_echo(bg_RGB+"0;0;10m    bg_RGB test (0;0;10)      \n"+clr);
    dk_echo(bg_RGB+"0;0;5m    bg_RGB test (0;0;5)       \n"+clr);
    dk_echo(bg_RGB+"0;0;0m    bg_RGB test (0;0;0)       \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"          Combinations         \n"+clr);
    dk_echo("negative                             negative    inverse foreground <-> background   \n"+clr);
    dk_echo("bg_yellow red                      bg_yellow red    yellow backgroud / red foreground   \n"+clr);
    dk_echo("bg_yellow red negative           bg_yellow red negative         yellow / red inversed          \n"+clr);
    dk_echo("bg_red ..bg_green ..bg_blue      bg_red     nested   bg_green     colors    bg_blue     text    \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
    dk_echo(black+bg_lblack+"         ASCII Color Art       \n"+clr);
    dk_echo("\n");
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_blue+"   * * * * * * * *  "+bg_white+"                                   \n"+clr);
    dk_echo(bg_blue+"  * * * * * * * * * "+bg_red+"                                   \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo(bg_white+"                                                      \n"+clr);
    dk_echo(bg_red+"                                                      \n"+clr);
    dk_echo("\n");
    dk_echo("\n");
*/
}
#endif
