#dk_depend(backward-cpp)
dk_depend(stackwalker)
dk_depend(DKAssets)
dk_depend(DKCurl)
IF(HAVE_DKDuktape)
	dk_depend(DKDuktape)
ENDIF()
IF(HAVE_DKCef)
	dk_depend(DKCef)
ENDIF()

if(MSVC)
	dk_copy(${STACKWALKER}/StackWalker/StackWalker.cpp ${DKPLUGINS_DIR}/DKDebug/StackWalker.cpp)
	WIN_dk_include(${STACKWALKER}/StackWalker)
else()
	dk_remove(${DKPLUGINS_DIR}/DKDebug/StackWalker.cpp NOERROR)
endif()

dk_generateCmake(DKDebug)
dk_assets(DKDebug)

IF(DKAPP)
	IF(WIN)
		LIST(APPEND RELEASE_LINK_FLAGS /DEBUG)
	ENDIF()
ENDIF()