#dk_depend(backward-cpp)
dk_depend(stackwalker)
dk_depend(DKAssets)
dk_depend(DKCurl)
if(HAVE_DKDuktape)
	dk_depend(DKDuktape)
endif()
if(HAVE_DKCef)
	dk_depend(DKCef)
endif()

if(MSVC)
	dk_copy(${STACKWALKER}/StackWalker/StackWalker.cpp ${DKPLUGINS_DIR}/DKDebug/StackWalker.cpp)
	WIN_dk_include(${STACKWALKER}/StackWalker)
else()
	dk_remove(${DKPLUGINS_DIR}/DKDebug/StackWalker.cpp NOERROR)
endif()

dk_generateCmake(DKDebug)
dk_assets(DKDebug)

if(DKAPP)
	if(WIN)
		LIST(APPEND RELEASE_LINK_FLAGS /DEBUG)
	endif()
endif()