#dk_depend(backward-cpp)
dk_depend(stackwalker)
dk_depend(DKAssets)
dk_depend(DKCurl)
IF(HAVE_DKDuktape)
	dk_depend(DKDuktape)
ENDIF()
IF(HAVE_DKCef)
	dk_depend(DKCef)
ENDIF()

dk_generateCmake(DKDebug)
dk_assets(DKDebug)

IF(DKAPP)
	IF(WIN)
		LIST(APPEND RELEASE_LINK_FLAGS /DEBUG)
	ENDIF()
ENDIF()