DKDEPEND(moment)
DKDEPEND(chart.js)

if(MOMENT)
	dk_copy(${MOMENT}/ ${DKPLUGINS}/DKChart/ FALSE)
	dk_rename(${DKPLUGINS}/DKChart/moment.js ${DKPLUGINS}/DKChart/moment.min.js TRUE)
endif()
if(CHART.JS)
	dk_copy(${CHART.JS}/ ${DKPLUGINS}/DKChart/ FALSE)
	dk_rename(${DKPLUGINS}/DKChart/chart.js-Chart.min.js ${DKPLUGINS}/DKChart/chart.min.js TRUE)
endif()
DKASSETS(DKChart)
