dk_depend(moment)
dk_depend(chart.js)

if(MOMENT)
	dk_copy(${MOMENT}/ ${DKPLUGINS}/DKChart/)
	dk_rename(${DKPLUGINS}/DKChart/moment.js ${DKPLUGINS}/DKChart/moment.min.js OVERWRITE)
endif()
if(CHART.JS)
	dk_copy(${CHART.JS}/ ${DKPLUGINS}/DKChart/)
	dk_rename(${DKPLUGINS}/DKChart/chart.js-Chart.min.js ${DKPLUGINS}/DKChart/chart.min.js OVERWRITE)
endif()
dk_assets(DKChart)
