DKDEPEND(moment)
DKDEPEND(chart.js)

if(MOMENT)
	DKCOPY(${MOMENT}/ ${DKPLUGINS}/DKChart/ FALSE)
endif()
if(CHART.JS)
	DKCOPY(${CHART.JS}/ ${DKPLUGINS}/DKChart/ FALSE)
	DKRENAME(${DKPLUGINS}/DKChart/chart.js-Chart.min.js ${DKPLUGINS}/DKChart/chart.min.js TRUE)
endif()
DKASSETS(DKChart)
