DKDEPEND(DK)
DKDLL(DKPlugin1)
DKASSETS(DKPlugin1)

IF(WIN_32)
	DKCOPY(${DKPLUGINS}/DKPlugin1/win32/Release/DKPlugin1.dll ${DKPROJECT}/assets/DKPlugin1 TRUE)
ENDIF()

IF(WIN_64)
	DKCOPY(${DKPLUGINS}/DKPlugin1/win64/Release/DKPlugin1.dll ${DKPROJECT}/assets/DKPlugin1 TRUE)
ENDIF()
