dk_depend(duktape)
dk_depend(ncurses)
dk_depend(DK)
if(USE_babel)
	dk_depend(babel)
endif()


#NOTE: include duktape.c in DKDuktapeB
#if(NOT EXISTS ${DKPLUGINS}/DKDuktapeB/duktape.cpp)
	#dk_copy(${DUKTAPE}/dist/src/duk_config.h 	${DKPLUGINS}/DKDuktapeB/duk_config.h OVERWRITE)
	#dk_copy(${DUKTAPE}/dist/src/duktape.h 		${DKPLUGINS}/DKDuktapeB/duktape.h 	OVERWRITE)
	#dk_copy(${DUKTAPE}/dist/src/duktape.c 		${DKPLUGINS}/DKDuktapeB/duktape.cpp 	OVERWRITE)
#endif()
	
#dk_set(ENABLE_eventloop ON)
if(ENABLE_eventloop)
	dk_define(HAVE_eventloop)
	if(NOT EXISTS ${DKPLUGINS}/DKDuktapeB/poll.cpp)
		dk_copy(${DUKTAPE}/examples/eventloop/poll.c ${DKPLUGINS}/DKDuktapeB/poll.cpp)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktapeB/c_eventloop.cpp)
		dk_copy(${DUKTAPE}/examples/eventloop/c_eventloop.c ${DKPLUGINS}/DKDuktapeB/c_eventloop.cpp)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktapeB/c_eventloop.js)
		dk_copy(${DUKTAPE}/examples/eventloop/c_eventloop.js ${DKPLUGINS}/DKDuktapeB/c_eventloop.js)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktapeB/ecma_eventloop.js)
		dk_copy(${DUKTAPE}/examples/eventloop/ecma_eventloop.js ${DKPLUGINS}/DKDuktapeB/ecma_eventloop.js)
	endif()
else()
	if(EXISTS ${DKPLUGINS}/DKDuktapeB/poll.cpp)
		dk_remove(${DKPLUGINS}/DKDuktapeB/poll.cpp)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktapeB/c_eventloop.cpp)
		dk_remove(${DKPLUGINS}/DKDuktapeB/c_eventloop.cpp)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktapeB/c_eventloop.js)
		dk_remove(${DKPLUGINS}/DKDuktapeB/c_eventloop.js)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktapeB/ecma_eventloop.js)
		dk_remove(${DKPLUGINS}/DKDuktapeB/ecma_eventloop.js)
	endif()
endif()


dk_include(${DKPLUGINS}/DKDuktapeB)
dk_include(${DUKTAPE}/src)
dk_define(HAVE_DKDuktapeB)

dk_generateCmake(DKDuktapeB)
dk_assets(DKDuktapeB)
