dk_depend(duktape)
dk_depend(ncurses)
dk_depend(DK)
if(USE_babel)
	dk_depend(babel)
endif()


#NOTE: include duktape.c in DKDuktape
#if(NOT EXISTS ${DKPLUGINS}/DKDuktape/duktape.cpp)
	#dk_copy(${DUKTAPE}/dist/src/duk_config.h 	${DKPLUGINS}/DKDuktape/duk_config.h OVERWRITE)
	#dk_copy(${DUKTAPE}/dist/src/duktape.h 		${DKPLUGINS}/DKDuktape/duktape.h 	OVERWRITE)
	#dk_copy(${DUKTAPE}/dist/src/duktape.c 		${DKPLUGINS}/DKDuktape/duktape.cpp 	OVERWRITE)
#endif()
	
#dk_set(ENABLE_eventloop ON)
if(ENABLE_eventloop)
	dk_define(HAVE_eventloop)
	if(NOT EXISTS ${DKPLUGINS}/DKDuktape/poll.cpp)
		dk_copy(${DUKTAPE}/examples/eventloop/poll.c ${DKPLUGINS}/DKDuktape/poll.cpp)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktape/c_eventloop.cpp)
		dk_copy(${DUKTAPE}/examples/eventloop/c_eventloop.c ${DKPLUGINS}/DKDuktape/c_eventloop.cpp)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktape/c_eventloop.js)
		dk_copy(${DUKTAPE}/examples/eventloop/c_eventloop.js ${DKPLUGINS}/DKDuktape/c_eventloop.js)
	endif()
	if(NOT EXISTS ${DKPLUGINS}/DKDuktape/ecma_eventloop.js)
		dk_copy(${DUKTAPE}/examples/eventloop/ecma_eventloop.js ${DKPLUGINS}/DKDuktape/ecma_eventloop.js)
	endif()
else()
	if(EXISTS ${DKPLUGINS}/DKDuktape/poll.cpp)
		dk_remove(${DKPLUGINS}/DKDuktape/poll.cpp)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktape/c_eventloop.cpp)
		dk_remove(${DKPLUGINS}/DKDuktape/c_eventloop.cpp)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktape/c_eventloop.js)
		dk_remove(${DKPLUGINS}/DKDuktape/c_eventloop.js)
	endif()
	if(EXISTS ${DKPLUGINS}/DKDuktape/ecma_eventloop.js)
		dk_remove(${DKPLUGINS}/DKDuktape/ecma_eventloop.js)
	endif()
endif()


dk_include(${DKPLUGINS}/DKDuktape)
dk_include(${DUKTAPE}/src)
dk_define(HAVE_DKDuktape)

dk_generateCmake(DKDuktape)
dk_assets(DKDuktape)
