dk_depend(rmlui)
dk_depend(DKCurl)
dk_depend(DKFile)
dk_depend(DKWindow)
dk_depend(DKXml)
dk_depend(tidy-html5)
IF(HAVE_DKDuktape)
	dk_depend(DKDuktape)
ENDIF()
IF(HAVE_DKCef)
	dk_depend(DKCef)
ENDIF()

dk_generateCmake(DKRmlInterface)
dk_assets(DKRmlInterface)
