dk_depend(rmlui)
dk_depend(DKCurl)
dk_depend(DKFile)
dk_depend(DKWindow)
dk_depend(DKXml)
dk_depend(tidy-html5)
if(HAVE_DKDuktape)
	dk_depend(DKDuktape)
endif()
if(HAVE_DKCef)
	dk_depend(DKCef)
endif()
if(HAVE_DKSdlRmlDocument)
	dk_depend(DKSdlRmlDocument)	# LINUX FIX:
endif()

dk_generateCmake(DKRmlInterface)
dk_assets(DKRmlInterface)
